// TEMPORARY DESIGN DATA. Delete the whole src/devMocks folder before submitting for review.
// Rows use the program_catalog shape so they flow through the same mapping as real programs.

export const MOCK_PROGRAMS: Record<string, unknown>[] = [
  {
    id: 'mock-hypertrophy-v-taper',
    title: 'V-Taper Hypertrophy Block',
    discipline: 'Hypertrophy',
    days_per_week: 5,
    focus: 'Upper chest and lat width focus with controlled eccentrics and weekly volume progression.',
    price_cents: 4900,
    tier: 'Intermediate',
    duration_label: '8 weeks',
    split_label: 'Upper / Lower / Push / Pull / Legs',
    equipment: 'Full gym',
    cover_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=1200&auto=format&fit=crop&q=80',
    week_one: [
      'Upper push: incline DB press, cable fly, lateral raise',
      'Lower: hack squat, RDL, leg curl',
      'Pull: pulldown, chest-supported row, rear delt',
      'Push: flat press, dips, overhead press',
      'Legs and arms: split squat, curls, pushdowns',
    ],
    catalog_coach_id: 'marcus_reid',
  },
  {
    id: 'mock-hypertrophy-starter',
    title: 'Hypertrophy Foundations',
    discipline: 'Hypertrophy',
    days_per_week: 3,
    focus: 'Three full-body sessions a week to learn the main lifts and build a base.',
    price_cents: 0,
    tier: 'Beginner',
    duration_label: '4 weeks',
    split_label: 'Full body',
    equipment: 'Dumbbells and machines',
    cover_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=1200&auto=format&fit=crop&q=80',
    week_one: [
      'Full body A: goblet squat, DB press, seated row',
      'Full body B: leg press, incline press, pulldown',
      'Full body C: RDL, machine press, cable row',
    ],
    catalog_coach_id: 'marcus_reid',
  },
  {
    id: 'mock-mobility-hips',
    title: 'Hip & Shoulder Mobility Reset',
    discipline: 'Mobility',
    days_per_week: 4,
    focus: 'Daily joint work for hips and shoulders. 20 minutes a session, no heavy equipment.',
    price_cents: 0,
    tier: 'All levels',
    duration_label: '6 weeks',
    split_label: 'Joint focus rotation',
    equipment: 'Band and mat',
    cover_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&auto=format&fit=crop&q=80',
    week_one: [
      'Hips: 90/90 flow, capsule CARs, couch stretch',
      'Shoulders: band distraction, scap pulls, wall slides',
      'Spine: cat-cow, thoracic openers, hollow hold',
      'Full flow: all three, slower tempo',
    ],
    catalog_coach_id: 'elena_vasquez',
  },
  {
    id: 'mock-yoga-recovery',
    title: 'Recovery Yoga Flow',
    discipline: 'Yoga',
    days_per_week: 3,
    focus: 'Slow flows for recovery days to restore range of motion and calm the nervous system.',
    price_cents: 2900,
    tier: 'All levels',
    duration_label: '4 weeks',
    split_label: 'Flow sessions',
    equipment: 'Mat',
    cover_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&auto=format&fit=crop&q=80',
    week_one: [
      'Lower body flow: pigeon, lizard, low lunge',
      'Upper body flow: thread the needle, puppy pose',
      'Full flow and breath work',
    ],
    catalog_coach_id: 'elena_vasquez',
  },
  {
    id: 'mock-strength-squat',
    title: 'Low-Bar Squat Strength Cycle',
    discipline: 'Strength',
    days_per_week: 4,
    focus: 'A strength cycle built around the squat with technique checkpoints each week.',
    price_cents: 5900,
    tier: 'Advanced',
    duration_label: '10 weeks',
    split_label: 'Squat / Bench / Deadlift / Accessory',
    equipment: 'Barbell and rack',
    cover_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&auto=format&fit=crop&q=80',
    week_one: [
      'Squat: top single, 4x4 back-off',
      'Bench: 5x5, close-grip',
      'Deadlift: 3x3, paused pulls',
      'Accessory: split squat, rows, core',
    ],
    catalog_coach_id: 'dr_jason_reed',
  },
  {
    id: 'mock-hyrox-race',
    title: 'Hyrox Race Prep',
    discipline: 'Hyrox',
    days_per_week: 5,
    focus: 'Compromised running, station pacing, and sled transitions for your next race.',
    price_cents: 6900,
    tier: 'Intermediate',
    duration_label: '12 weeks',
    split_label: 'Run / Stations / Engine',
    equipment: 'SkiErg, sled, rower',
    cover_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200&auto=format&fit=crop&q=80',
    week_one: [
      'Run intervals: 8 x 1 km at race pace',
      'Stations: sled push and pull, wall balls',
      'Engine: SkiErg and row ladders',
      'Compromised run: station then 1 km',
      'Long aerobic run',
    ],
    catalog_coach_id: 'anya_petrova',
  },
];
