import type { StoryArchetype } from '../components/modals/ProgramReelsModal';

export const MOCK_ARCHETYPE_STORIES: StoryArchetype[] = [
  {
    id: 'story-1',
    name: 'Elite Reels',
    archetypeTitle: 'Elite Tactical Reels',
    creatorHandle: '@elite.tactical',
    verified: true,
    backgroundAsset: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80',
    focusMuscles: ['Full-Body Kinetic Chain', 'CNS Potentiation', 'VO2 Max Conditioning'],
    splitOverview: {
      daysPerWeek: '7-Day Hybrid Microcycle',
      targetFocus: 'Tactical Strength & Conditioning',
      intensity: 'RPE 8.5-9.5 Peak Potentiation',
      protocol: 'Dynamic athletic foundation combining compound lifting, high-intensity intervals, and metabolic conditioning.',
      keyLifts: [
        'Barbell Front Squat (3x6)',
        'Heavy Trap Bar Deadlift (4x5)',
        'Tactical Pull-Ups (4x8)',
        'Echo Bike Sprints (10 Rounds)',
      ],
    },
  },
  {
    id: 'story-2',
    name: 'V-TAPER Sculptor',
    archetypeTitle: 'V-TAPER Sculptor',
    creatorHandle: '@apex.hypertrophy',
    verified: true,
    backgroundAsset: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80',
    focusMuscles: ['Clavicular Upper Pecs', 'Latissimus Flare', 'Lateral Deltoids'],
    splitOverview: {
      daysPerWeek: '5-Day Upper Bias Periodization',
      targetFocus: 'Torso Width & Clavicular Expansion',
      intensity: 'RPE 8.0-9.0 Hypertrophy Focus',
      protocol: 'Clavicular bias pressing paired with mechanical tension pulldowns and high-frequency side delt volume.',
      keyLifts: [
        'Incline Barbell Press 30° (4x8)',
        'Neutral-Grip Lat Pulldown (4x10)',
        'Chest-Supported T-Bar Row (3x10)',
        'Cable Lateral Raises (4x15)',
      ],
    },
  },
  {
    id: 'story-3',
    name: 'Booty Builder',
    archetypeTitle: 'Booty Builder',
    creatorHandle: '@biomechanic.lab',
    verified: true,
    backgroundAsset: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=900&q=80',
    focusMuscles: ['Gluteus Maximus', 'Pelvic Stabilizers', 'Hamstring Tie-In'],
    splitOverview: {
      daysPerWeek: '4-Day Lower Body Periodization',
      targetFocus: 'Glute Hypertrophy & Pelvic Alignment',
      intensity: 'RPE 8.5-9.5 Progressive Overload',
      protocol: 'Heavy horizontal hip abduction and extension paired with unilateral eccentric loading.',
      keyLifts: [
        'Barbell Hip Thrust (4x10)',
        'Kas Glute Bridge 3s Pause (3x12)',
        'Romanian Deadlift RDL (4x8)',
        'Bulgarian Split Squat (3x10/leg)',
      ],
    },
  },
  {
    id: 'story-4',
    name: 'Greek God',
    archetypeTitle: 'Greek God Archetype',
    creatorHandle: '@classical.ratio',
    verified: true,
    backgroundAsset: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80',
    focusMuscles: ['Boulder Deltoids', 'Upper Chest Shelf', 'Quads & Core V-Line'],
    splitOverview: {
      daysPerWeek: '5-Day Push / Pull / Legs Split',
      targetFocus: 'Golden Ratio 1.618 Symmetry',
      intensity: 'RPE 8.5 Heavy Compound Potentiation',
      protocol: 'Classical physique periodization prioritizing heavy overhead pressing, weighted calisthenics, and high-squat volume.',
      keyLifts: [
        'Standing Barbell OHP (5x5)',
        'Weighted Neutral Pull-Ups (4x6)',
        'Incline Dumbbell Press (4x8)',
        'High-Bar Back Squat (4x6)',
      ],
    },
  },
  {
    id: 'story-5',
    name: 'HOURGLASS',
    archetypeTitle: 'Hourglass Taper',
    creatorHandle: '@taper.physique',
    verified: true,
    backgroundAsset: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80',
    focusMuscles: ['Waist Taper & Core V-Line', 'Glute-Ham Extension', 'Lat Flare'],
    splitOverview: {
      daysPerWeek: '5-Day Silhouette Sculpt',
      targetFocus: 'Waist Compression & Posterior Chain',
      intensity: 'RPE 8.0-9.0 Metabolic Hypertrophy',
      protocol: 'Strategic lat and glute development while utilizing isometric core compression to minimize waist circumference.',
      keyLifts: [
        'Barbell Hip Thrust Pyramid (4x12,10,8,6)',
        'Deficit Reverse Lunges (3x12)',
        'Wide-Grip Cable Rows (3x12)',
        'Cable Pallof Hold (3x30s)',
      ],
    },
  },
];
