import type { ExploreCoach, ExploreReelItem } from '../features/reels/reelTypes';

export const MOCK_COACHES: Record<string, ExploreCoach> = {
  o1fc_support: {
    id: 'o1fc_support',
    name: 'Oblivion 1 Systems',
    handle: '@oblivion1.official',
    avatar: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&auto=format&fit=crop&crop=center&q=80',
    verified: true,
    specialtyTitle: 'Official Club Systems & Digital Intelligence',
    rating: 0,
    reviewCount: 0,
    certificationPill: 'O1FC CORE SYSTEM • DIGITAL TRAINING ARCHITECTURE',
    rate: 'Included',
    slotsRemaining: 99,
    bio: 'Official feature walkthroughs, strain telemetry guides, and biometric operation protocols for Oblivion 1 Fitness Club members.',
    disciplines: ['Vitals Architecture', 'Active Logging', 'Biomechanical Audit', 'Spotter Beacon'],
  },
  elena_vasquez: {
    id: 'elena_vasquez',
    name: 'Elena Vasquez',
    handle: '@elena.vasquez.pt',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    verified: true,
    specialtyTitle: 'Doctor of Physical Therapy • Mobility & Joints',
    rating: 0,
    reviewCount: 0,
    certificationPill: 'FRCMS LEVEL 2',
    rate: '$135/mo',
    slotsRemaining: 3,
    bio: 'Former clinical orthopedic physical therapist specializing in hip capsule mobility, rotator cuff decompression, and injury-proof kinetic mechanics.',
    disciplines: ['Hip Mobility', 'FRC Kinetic Flow', 'Rotator Cuff Rehab', 'Joint Longevity'],
    physiquePhotos: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=1000&auto=format&fit=crop&q=80',
    ],
    physiqueStats: {
      height: "170 cm (5'7\")",
      weight: '61 kg',
      bodyFatEst: '14.5% Athletic',
      experienceYears: 9,
      competitionLifts: [
        { label: 'FRC Hip Internal', value: '45° Active' },
        { label: 'Overhead Squat', value: '85 kg' },
        { label: 'Trap Bar Deadlift', value: '145 kg' },
      ],
    },
  },
  marcus_reid: {
    id: 'marcus_reid',
    name: 'Marcus Reid',
    handle: '@marcus.reid.iron',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    verified: true,
    specialtyTitle: 'Hypertrophy & Kinetic Alignment Specialist',
    rating: 0,
    reviewCount: 0,
    certificationPill: 'IFBB PRO • CSCS',
    rate: '$150/mo',
    slotsRemaining: 2,
    bio: 'Natural classic physique specialist focusing on clavicular upper chest fiber alignment, lat flare mechanics, and standardized tension curves.',
    disciplines: ['Hypertrophy Science', 'Biomechanic PPO', 'Contest Prep', 'V-Taper Architecture'],
    physiquePhotos: [
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=1000&auto=format&fit=crop&q=80',
    ],
    physiqueStats: {
      height: "185 cm (6'1\")",
      weight: '94 kg (Comp: 88 kg)',
      bodyFatEst: '7.2% Stage',
      experienceYears: 12,
      competitionLifts: [
        { label: 'Barbell Back Squat', value: '255 kg' },
        { label: 'Pause Bench Press', value: '185 kg' },
        { label: 'Conventional Deadlift', value: '310 kg' },
        { label: 'Standing OHP', value: '115 kg' },
      ],
    },
  },
  dr_jason_reed: {
    id: 'dr_jason_reed',
    name: 'Dr. Jason Reed',
    handle: '@dr.reed.biomechanics',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    verified: true,
    specialtyTitle: 'Biomechanics Director & Sports Scientist',
    rating: 0,
    reviewCount: 0,
    certificationPill: 'PHD APPLIED BIOMECHANICS • EXOS',
    rate: '$165/mo',
    slotsRemaining: 4,
    bio: 'Lead sports scientist analyzing ground reaction vectors, patellar shear mitigation, low-bar torque dynamics, and rate of force development.',
    disciplines: ['Ground Vector Physics', 'Knee Torque Mitigation', 'Squat Analysis', 'Kinematic Profiling'],
    physiquePhotos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=1000&auto=format&fit=crop&q=80',
    ],
    physiqueStats: {
      height: "182 cm (6'0\")",
      weight: '89 kg',
      bodyFatEst: '11.8% Athletic',
      experienceYears: 14,
      competitionLifts: [
        { label: 'Low-Bar Squat', value: '235 kg' },
        { label: 'Bench Press', value: '165 kg' },
        { label: 'Trap Bar Deadlift', value: '280 kg' },
      ],
    },
  },
  anya_petrova: {
    id: 'anya_petrova',
    name: 'Anya Petrova',
    handle: '@anya.petrova.hyrox',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    verified: true,
    specialtyTitle: 'Endurance & Hyrox Master Instructor',
    rating: 0,
    reviewCount: 0,
    certificationPill: 'OLYMPIC TRIATHLETE • HYROX MASTER INSTRUCTOR',
    rate: '$140/mo',
    slotsRemaining: 5,
    bio: 'Olympic-level endurance coach breaking down compromised running pacing, sled transition speed, lactate threshold buffering, and SkiErg mechanics.',
    disciplines: ['Hyrox Race Pacing', 'Lactate Buffering', 'Sled Push Vectoring', 'Aerobic Engine'],
    physiquePhotos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=1000&auto=format&fit=crop&q=80',
    ],
    physiqueStats: {
      height: "175 cm (5'9\")",
      weight: '64 kg',
      bodyFatEst: '13.2% Athletic',
      experienceYears: 10,
      competitionLifts: [
        { label: 'Hyrox Pro Time', value: '1h 04m' },
        { label: 'Sled Push 152kg', value: '3m 12s' },
        { label: '5,000m Pace', value: '3:35 /km' },
      ],
    },
  },
};

export const MOCK_REELS: ExploreReelItem[] = [
  {
    id: 'reel-tut-vitals',
    title: '01. Daily Vitals, Tensile Strain & Cardio Syncing',
    category: 'TUTORIAL',
    filterTag: 'TUTORIAL',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1510519138161-58474ebf8804?w=800&auto=format&fit=crop&crop=center&q=80',
    views: '--',
    duration: '0:45',
    cues: 'Tap the Cosmic Vitals Ring to audit tensile strain breakdown. Connect Cardio scanner to calculate heart rate variability and real-time caloric burn across workouts.',
    coach: MOCK_COACHES.o1fc_support,
    filmstripClips: [
      {
        id: 'clip-tut-1',
        title: 'Cosmic Strain & Daily Kcal',
        duration: '0:45',
        thumbnail: 'https://images.unsplash.com/photo-1510519138161-58474ebf8804?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Vitals HUD',
        badge: 'FEATURE',
      },
      {
        id: 'clip-tut-2',
        title: 'Cardio Camera Scanner',
        duration: '0:32',
        thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Scanner',
        badge: 'CUE',
      },
      {
        id: 'clip-tut-3',
        title: 'HRV & Recovery Diagnostics',
        duration: '0:38',
        thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Telemetry',
        badge: 'PHOTO',
      },
      {
        id: 'clip-tut-4',
        title: 'App Directives',
        duration: 'Guide',
        thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'System',
        badge: 'DOCS',
      },
    ],
  },
  {
    id: 'reel-tut-activelog',
    title: '02. Active Workout Logging, KG Dials & Rest Timers',
    category: 'TUTORIAL',
    filterTag: 'TUTORIAL',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&crop=center&q=80',
    views: '--',
    duration: '0:50',
    cues: 'Scroll down to the Active Log. Spin the tactile KG dial, tap completed checkmarks to log sets, and adjust RPE/RIR to automatically compute your tonnage curve.',
    coach: MOCK_COACHES.o1fc_support,
    filmstripClips: [
      {
        id: 'clip-tut-log-1',
        title: 'Tactile KG Dial & Rep Entry',
        duration: '0:50',
        thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Log Entry',
        badge: 'FEATURE',
      },
      {
        id: 'clip-tut-log-2',
        title: 'RPE & Fatigue Management',
        duration: '0:34',
        thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Fatigue Matrix',
        badge: 'CUE',
      },
      {
        id: 'clip-tut-log-3',
        title: 'Auto Rest Interval Timer',
        duration: '0:29',
        thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Rest Timer',
        badge: 'PHOTO',
      },
    ],
  },
  {
    id: 'reel-tut-coach',
    title: '03. Intel Biomechanical Coach & Periodization Blueprints',
    category: 'TUTORIAL',
    filterTag: 'TUTORIAL',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&crop=center&q=80',
    views: '--',
    duration: '0:55',
    cues: 'Expand Intel Coach to view real-time form directives or load complete workout blueprints. Tap Load to push full exercise protocols directly to your active training session.',
    coach: MOCK_COACHES.o1fc_support,
    filmstripClips: [
      {
        id: 'clip-tut-coach-1',
        title: 'Loading Workout Blueprints',
        duration: '0:55',
        thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Blueprints',
        badge: 'FEATURE',
      },
      {
        id: 'clip-tut-coach-2',
        title: 'AI Directives & Form Audits',
        duration: '0:41',
        thumbnail: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        tag: 'Form Audit',
        badge: 'CUE',
      },
    ],
  },
  {
    id: 'reel-tut-fuel-radar',
    title: '04. Fuel Macro Radar & Club Floor Spotter Beacon',
    category: 'TUTORIAL',
    filterTag: 'TUTORIAL',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&auto=format&fit=crop&crop=center&q=80',
    views: '--',
    duration: '0:48',
    cues: 'Switch to the Fuel tab to scan nutrition barcodes and calculate targeted protein macros. Use the Radar tab to find certified spotters and review active floor congestion.',
    coach: MOCK_COACHES.o1fc_support,
    filmstripClips: [
      {
        id: 'clip-tut-fuel-1',
        title: 'Macro Radar & Fuel Scanner',
        duration: '0:48',
        thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        tag: 'Fuel Tab',
        badge: 'FEATURE',
      },
      {
        id: 'clip-tut-fuel-2',
        title: 'Radar Floor & Spotter Beacon',
        duration: '0:35',
        thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&crop=center&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Radar Tab',
        badge: 'CUE',
      },
    ],
  },
  {
    id: 'reel-hip-9090',
    title: 'Hip 90/90 Internal Rotation & Capsule Flow',
    category: 'MOBILITY',
    filterTag: 'QUADS & GLUTES',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:48',
    cues: 'Pins both ischial tuberosities to the floor. Rotate rear hip internally without lumbar flexion to restore anterior femoral acetabular clearance.',
    coach: MOCK_COACHES.elena_vasquez,
    filmstripClips: [
      {
        id: 'clip-hip-1',
        title: 'Hip 90/90 Flow',
        duration: '0:48',
        thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Full Flow',
        badge: 'DRILL',
      },
      {
        id: 'clip-hip-2',
        title: 'Scapular Pitch',
        duration: '0:35',
        thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Isometric Tension',
        badge: 'CUE',
      },
      {
        id: 'clip-hip-3',
        title: 'Clinical Lab',
        duration: '0:40',
        thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Form Audit',
        badge: 'PHOTO',
      },
      {
        id: 'clip-hip-4',
        title: '2 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-lat-stretch',
    title: 'Scapular Depressed Lat Pulldown Flare',
    category: 'HYPERTROPHY',
    filterTag: 'BACK & BICEPS',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:52',
    cues: 'Depress clavicle and pack lower traps prior to elbow descent. Pull humeral head toward iliac crest rather than behind torso to maximize lat fiber recruitment.',
    coach: MOCK_COACHES.marcus_reid,
    filmstripClips: [
      {
        id: 'clip-lat-1',
        title: 'Master Execution Cue',
        duration: '0:52',
        thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Execution',
        badge: 'DRILL',
      },
      {
        id: 'clip-lat-2',
        title: 'Scapular Pack Slow-Mo',
        duration: '0:28',
        thumbnail: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Slow-Mo Cue',
        badge: 'CUE',
      },
      {
        id: 'clip-lat-3',
        title: 'Neutral-Grip Angle Flare',
        duration: '0:36',
        thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Grip Variant',
        badge: 'PHOTO',
      },
      {
        id: 'clip-lat-4',
        title: '2 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-squat-torque',
    title: 'Foot Screw & Patellar Torque in Low-Bar Squats',
    category: 'BIOMECHANICS',
    filterTag: 'QUADS & GLUTES',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '1:04',
    cues: 'Screw big toe, pinky toe, and calcaneus into platform to generate external rotational torque at the hip socket before descending into the hole.',
    coach: MOCK_COACHES.dr_jason_reed,
    filmstripClips: [
      {
        id: 'clip-sq-1',
        title: 'Tripod Foot Engagement',
        duration: '1:04',
        thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Biomechanics',
        badge: 'DRILL',
      },
      {
        id: 'clip-sq-2',
        title: 'Femur Angle & Knee Tracking',
        duration: '0:38',
        thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Vector Check',
        badge: 'CUE',
      },
      {
        id: 'clip-sq-3',
        title: 'Clinical Lab',
        duration: '0:45',
        thumbnail: 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Concentric Drive',
        badge: 'PHOTO',
      },
      {
        id: 'clip-sq-4',
        title: '3 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'Consultation',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-sled-hyrox',
    title: 'Compromised Running & Sled Transition Strategy',
    category: 'STRENGTH',
    filterTag: 'HYROX / CONDITIONING',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:58',
    cues: 'Lower center of mass 45-degrees into sled poles. Short, driving piston strides reduce metabolic lactate spikes by 22% entering the 1km run segment.',
    coach: MOCK_COACHES.anya_petrova,
    filmstripClips: [
      {
        id: 'clip-sled-1',
        title: 'Sled Push 45° Drive',
        duration: '0:58',
        thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'Hyrox Engine',
        badge: 'DRILL',
      },
      {
        id: 'clip-sled-2',
        title: 'Sled Pull Harness Rhythm',
        duration: '0:44',
        thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Pull Phase',
        badge: 'CUE',
      },
      {
        id: 'clip-sled-3',
        title: 'Clinical Lab',
        duration: '0:36',
        thumbnail: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Cadence Recovery',
        badge: 'PHOTO',
      },
      {
        id: 'clip-sled-4',
        title: '2 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-shoulder-rehab',
    title: 'Subacromial Decompression & Rotator Cuff Floss',
    category: 'REHAB',
    filterTag: 'SHOULDERS & ARMS',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:46',
    cues: 'Light traction band distracts humeral head inferiorly while performing 15-degree external rotations to eliminate impingement pinching on heavy benching days.',
    coach: MOCK_COACHES.elena_vasquez,
    filmstripClips: [
      {
        id: 'clip-sh-1',
        title: 'Subacromial Floss Sequence',
        duration: '0:46',
        thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        tag: 'Joint Rehab',
        badge: 'DRILL',
      },
      {
        id: 'clip-sh-2',
        title: 'Banded Glenohumeral Distraction',
        duration: '0:34',
        thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Distraction',
        badge: 'CUE',
      },
      {
        id: 'clip-sh-3',
        title: 'Clinical Lab',
        duration: '0:40',
        thumbnail: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Scapular Control',
        badge: 'PHOTO',
      },
      {
        id: 'clip-sh-4',
        title: '2 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-incline-bench',
    title: '30-Degree Incline Clavicular Dumbbell Press',
    category: 'HYPERTROPHY',
    filterTag: 'CHEST & TRICEPS',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:54',
    cues: 'Retract and lock scapula with sternal elevation. Align forearm vertical with wrist stacked directly over elbow to route pure tension across the clavicular pectoralis.',
    coach: MOCK_COACHES.marcus_reid,
    filmstripClips: [
      {
        id: 'clip-inc-1',
        title: 'Clavicular Vector Setup',
        duration: '0:54',
        thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Chest Isolation',
        badge: 'DRILL',
      },
      {
        id: 'clip-inc-2',
        title: '3-Second Controlled Eccentric',
        duration: '0:38',
        thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Tempo Control',
        badge: 'CUE',
      },
      {
        id: 'clip-inc-3',
        title: 'Clinical Lab',
        duration: '0:42',
        thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Joint Safety',
        badge: 'PHOTO',
      },
      {
        id: 'clip-inc-4',
        title: '2 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-back-lat',
    title: 'Deficit Deadlift & Lat Latency Control',
    category: 'STRENGTH',
    filterTag: 'BACK & BICEPS',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:55',
    cues: 'Engage lats as internal stabilizers by bending the bar into your shins. Maintain neutral cervical spine through full hip extension lock.',
    coach: MOCK_COACHES.dr_jason_reed,
    filmstripClips: [
      {
        id: 'clip-bl-1',
        title: 'Deficit Setup & Wedge',
        duration: '0:55',
        thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Deadlift Wedge',
        badge: 'DRILL',
      },
      {
        id: 'clip-bl-2',
        title: 'Lat Tension Bar Bend',
        duration: '0:34',
        thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Lat Lock',
        badge: 'CUE',
      },
      {
        id: 'clip-bl-3',
        title: 'Clinical Lab',
        duration: '0:42',
        thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Lockout Vector',
        badge: 'PHOTO',
      },
      {
        id: 'clip-bl-4',
        title: '3 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
  {
    id: 'reel-core-burn',
    title: 'Anterior Pelvic Tilt Correction & Core Hollow',
    category: 'MOBILITY',
    filterTag: 'MOBILITY & REHAB',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    views: '--',
    duration: '0:49',
    cues: 'Exhale fully to depress the ribcage into pelvis. Eliminate lumbar space against floor to activate deep transverse abdominis layers.',
    coach: MOCK_COACHES.elena_vasquez,
    filmstripClips: [
      {
        id: 'clip-cb-1',
        title: 'Hollow Body Progression',
        duration: '0:49',
        thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        tag: 'Hollow Hold',
        badge: 'DRILL',
      },
      {
        id: 'clip-cb-2',
        title: 'Diaphragm Rib Down Cue',
        duration: '0:33',
        thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        tag: 'Breathing',
        badge: 'CUE',
      },
      {
        id: 'clip-cb-3',
        title: 'Clinical Lab',
        duration: '0:41',
        thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        tag: 'Pelvic Neutral',
        badge: 'PHOTO',
      },
      {
        id: 'clip-cb-4',
        title: '2 Plans',
        duration: 'Consult',
        thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        tag: 'Programs',
        badge: 'PROGRAMS & Consult',
      },
    ],
  },
];
