import { DisciplineType } from '../../../types/workout';

export const CATEGORIES_BY_DISCIPLINE: Record<DisciplineType, string[]> = {
  lift: [
    'CHEST',
    'BACK & LATS',
    'SHOULDERS & DELTS',
    'ARMS & BICEPS',
    'ARMS & TRICEPS',
    'QUADS',
    'HAMSTRINGS',
    'GLUTES',
    'CALVES',
    'ABS & CORE',
    'OLYMPIC WEIGHTLIFTING',
    'POWERLIFTING PRIMES',
    'CALISTHENICS & GYMNASTICS',
    'STRONGMAN & HEAVY STONE',
  ],
  sports: [
    'SPEED & SPRINT',
    'HYROX',
    'AGILITY & FOOTWORK',
    'EXPLOSIVE POWER',
    'PLYOMETRICS',
    'STAMINA & ENGINE',
    'ROTATIONAL POWER',
    'GRIP & CARRY',
    'COMBAT & STRIKING',
    'WRESTLING & GRAPPLING',
    'KETTLEBELL PROTOCOL',
    'TRACK & FIELD ACCELERATION',
    'ROWING & ERG POWER',
    'ENDURANCE ENGINE',
  ],
  recovery: [
    'FULL MOBILITY',
    'SPINE & DECOMPRESS',
    'HIPS & PELVIS',
    'HAMSTRING & CALVES',
    'KNEES & ANKLES',
    'SHOULDER & THORACIC',
    'NECK & TRAPS',
    'PARASYMPATHETIC BREATHWORK',
    'MYOFASCIAL RELEASE',
    'ISOMETRIC REHAB & TENDON',
    'POSTURAL RESTORATION',
    'ACTIVE RECOVERY FLUSH',
  ],
};

export const EQUIPMENT_FILTERS = [
  'All',
  'Barbell',
  'Dumbbell',
  'Cable',
  'Machine',
  'Turf',
  'Mat',
  'Bodyweight',
  'Drill',
];
