import { RegionalFoodMap } from './types';

export const AFRICA_GLOBAL_FOODS: RegionalFoodMap = {
  "ZA": {
    "protein": [
      {
        "id": "za-prot-1",
        "name": "Free Range Ostrich Fillet Steak Grilled",
        "brand": "Klein Karoo ZA",
        "calories": 115,
        "protein": 27.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "100g steak",
        "serving_grams": 100,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-2",
        "name": "Traditional Beef Biltong Lean Slices",
        "brand": "Woolworths ZA",
        "calories": 260,
        "protein": 52.0,
        "carbs": 1.2,
        "fats": 5.5,
        "serving_size": "100g pack",
        "serving_grams": 100,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-3",
        "name": "Woolworths Fresh Skinless Chicken Breast Fillets",
        "brand": "Woolworths ZA",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-4",
        "name": "Grilled Cape Hake White Fish Fillet",
        "brand": "I&J Seafood ZA",
        "calories": 95,
        "protein": 20.5,
        "carbs": 0.0,
        "fats": 1.2,
        "serving_size": "100g fillet",
        "serving_grams": 100,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-5",
        "name": "Lucky Star Pilchards in Tomato Sauce",
        "brand": "Lucky Star ZA",
        "calories": 145,
        "protein": 18.0,
        "carbs": 2.0,
        "fats": 7.5,
        "serving_size": "100g serve",
        "serving_grams": 100,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-6",
        "name": "USN BlueLab 100% Whey Protein Vanilla",
        "brand": "USN South Africa",
        "calories": 125,
        "protein": 24.5,
        "carbs": 2.5,
        "fats": 2.0,
        "serving_size": "1 scoop (34g)",
        "serving_grams": 34,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-7",
        "name": "Free Range Jumbo Eggs (2 eggs)",
        "brand": "Farmer Brown ZA",
        "calories": 145,
        "protein": 13.0,
        "carbs": 0.8,
        "fats": 10.0,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "ZA"
      },
      {
        "id": "za-prot-8",
        "name": "Danone Ultra Mel Greek Style Plain Yoghurt",
        "brand": "Danone ZA",
        "calories": 85,
        "protein": 10.0,
        "carbs": 5.5,
        "fats": 2.5,
        "serving_size": "150g tub",
        "serving_grams": 150,
        "category": "protein",
        "country": "ZA"
      }
    ],
    "carbs": [
      {
        "id": "za-carb-1",
        "name": "Traditional White Maize Meal Mieliepap",
        "brand": "Ace / White Star ZA",
        "calories": 130,
        "protein": 2.8,
        "carbs": 28.0,
        "fats": 0.4,
        "serving_size": "1 cup cooked (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "ZA"
      },
      {
        "id": "za-carb-2",
        "name": "Jungle Traditional Rolled Oats Large Flakes",
        "brand": "Jungle Oats ZA",
        "calories": 150,
        "protein": 5.0,
        "carbs": 26.5,
        "fats": 2.8,
        "serving_size": "40g portion",
        "serving_grams": 40,
        "category": "carbs",
        "country": "ZA"
      },
      {
        "id": "za-carb-3",
        "name": "Tastic Parboiled Long Grain White Rice",
        "brand": "Tastic ZA",
        "calories": 170,
        "protein": 3.5,
        "carbs": 37.0,
        "fats": 0.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "ZA"
      },
      {
        "id": "za-carb-4",
        "name": "Orange Flesh Sweet Potato Steamed",
        "brand": "Woolworths ZA",
        "calories": 90,
        "protein": 1.6,
        "carbs": 21.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "ZA"
      },
      {
        "id": "za-carb-5",
        "name": "Woolworths Multiseed Brown Bread Sliced",
        "brand": "Woolworths ZA",
        "calories": 170,
        "protein": 7.5,
        "carbs": 28.0,
        "fats": 2.5,
        "serving_size": "2 slices (75g)",
        "serving_grams": 75,
        "category": "carbs",
        "country": "ZA"
      },
      {
        "id": "za-carb-6",
        "name": "Roasted Butternut Squash Cubes",
        "brand": "Fresh Produce ZA",
        "calories": 65,
        "protein": 1.2,
        "carbs": 15.0,
        "fats": 0.2,
        "serving_size": "150g roasted",
        "serving_grams": 150,
        "category": "carbs",
        "country": "ZA"
      }
    ],
    "fats": [
      {
        "id": "za-fats-1",
        "name": "Willow Creek Estate Extra Virgin Olive Oil",
        "brand": "Willow Creek ZA",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "ZA"
      },
      {
        "id": "za-fats-2",
        "name": "Black Cat Smooth 100% Peanut Butter",
        "brand": "Black Cat ZA",
        "calories": 185,
        "protein": 8.0,
        "carbs": 6.0,
        "fats": 15.5,
        "serving_size": "2 tbsp (30g)",
        "serving_grams": 30,
        "category": "fats",
        "country": "ZA"
      },
      {
        "id": "za-fats-3",
        "name": "Fresh South African Hass Avocado",
        "brand": "Westfalia ZA",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "ZA"
      },
      {
        "id": "za-fats-4",
        "name": "Raw South African Macadamia Nuts",
        "brand": "Green Farms ZA",
        "calories": 205,
        "protein": 2.5,
        "carbs": 4.0,
        "fats": 21.5,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "ZA"
      }
    ],
    "fastfood": [
      {
        "id": "za-fast-1",
        "name": "Nando's SA Quarter Chicken Peri-Peri Breast",
        "brand": "Nando's ZA",
        "calories": 295,
        "protein": 38.0,
        "carbs": 1.5,
        "fats": 15.0,
        "serving_size": "1 quarter (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "ZA"
      },
      {
        "id": "za-fast-2",
        "name": "Steers 100% Pure Beef Burger",
        "brand": "Steers ZA",
        "calories": 420,
        "protein": 24.0,
        "carbs": 38.0,
        "fats": 20.0,
        "serving_size": "1 burger (190g)",
        "serving_grams": 190,
        "category": "fastfood",
        "country": "ZA"
      },
      {
        "id": "za-fast-3",
        "name": "Chicken Licken SoulBites Naked (4 pcs)",
        "brand": "Chicken Licken ZA",
        "calories": 280,
        "protein": 32.0,
        "carbs": 8.0,
        "fats": 14.0,
        "serving_size": "4 pieces (160g)",
        "serving_grams": 160,
        "category": "fastfood",
        "country": "ZA"
      },
      {
        "id": "za-fast-4",
        "name": "Wimpy Double Quick Cheeseburger",
        "brand": "Wimpy ZA",
        "calories": 460,
        "protein": 26.0,
        "carbs": 36.0,
        "fats": 24.0,
        "serving_size": "1 burger (195g)",
        "serving_grams": 195,
        "category": "fastfood",
        "country": "ZA"
      }
    ],
    "drinks": [
      {
        "id": "za-drin-1",
        "name": "Freshpak Pure Rooibos Herbal Tea No Sugar",
        "brand": "Freshpak ZA",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 mug (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "ZA"
      },
      {
        "id": "za-drin-2",
        "name": "Appletiser 100% Sparkling Apple Juice",
        "brand": "Appletiser ZA",
        "calories": 120,
        "protein": 0.0,
        "carbs": 29.0,
        "fats": 0.0,
        "serving_size": "275ml bottle",
        "serving_grams": 275,
        "category": "drinks",
        "country": "ZA"
      },
      {
        "id": "za-drin-3",
        "name": "Powerade Zero Sugar Mountain Blast",
        "brand": "Powerade ZA",
        "calories": 5,
        "protein": 0.0,
        "carbs": 1.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "ZA"
      },
      {
        "id": "za-drin-4",
        "name": "Sparletta Sparberry Zero Calorie Drink",
        "brand": "Coca-Cola ZA",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "330ml can",
        "serving_grams": 330,
        "category": "drinks",
        "country": "ZA"
      }
    ]
  },
  "GLOBAL": {
    "protein": [
      {
        "id": "global-prot-1",
        "name": "100% Pure Whey Protein Isolate (Unflavored)",
        "brand": "Pure Athletics Global",
        "calories": 110,
        "protein": 26.0,
        "carbs": 0.5,
        "fats": 0.5,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-2",
        "name": "Micellar Casein Slow-Digesting Protein",
        "brand": "Optimal Nutrition",
        "calories": 120,
        "protein": 24.0,
        "carbs": 2.0,
        "fats": 1.0,
        "serving_size": "1 scoop (32g)",
        "serving_grams": 32,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-3",
        "name": "Hydrolyzed Collagen Peptides Pure Powder",
        "brand": "BioActive Peptides",
        "calories": 70,
        "protein": 18.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "2 scoops (20g)",
        "serving_grams": 20,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-4",
        "name": "Skinless Chicken Breast Fillet (Grilled)",
        "brand": "Pure Poultry Global",
        "calories": 165,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.6,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-5",
        "name": "Wild Alaskan Salmon Fillet (Baked)",
        "brand": "Ocean Caught Global",
        "calories": 195,
        "protein": 23.0,
        "carbs": 0.0,
        "fats": 11.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-6",
        "name": "95/5 Extra Lean Ground Beef",
        "brand": "Butcher Selection",
        "calories": 137,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 4.5,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-7",
        "name": "Atlantic Cod White Fish Fillet (Steamed)",
        "brand": "Wild Catch Seafood",
        "calories": 82,
        "protein": 18.0,
        "carbs": 0.0,
        "fats": 0.7,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-8",
        "name": "Organic Extra Firm Soybean Tofu",
        "brand": "Plant Pure Global",
        "calories": 125,
        "protein": 14.5,
        "carbs": 1.5,
        "fats": 7.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-9",
        "name": "Pasteurized Liquid Egg Whites 100%",
        "brand": "Pure Whites Global",
        "calories": 50,
        "protein": 11.0,
        "carbs": 0.7,
        "fats": 0.2,
        "serving_size": "100g (approx 3 whites)",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-10",
        "name": "Solid White Albacore Tuna in Water",
        "brand": "Fisherman Select",
        "calories": 110,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "100g drained",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-11",
        "name": "Organic Hemp Seed Protein Powder 50%",
        "brand": "EcoHarvest Global",
        "calories": 120,
        "protein": 15.0,
        "carbs": 8.0,
        "fats": 3.5,
        "serving_size": "30g scoop",
        "serving_grams": 30,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-12",
        "name": "Low Fat Cottage Cheese (1% Milkfat)",
        "brand": "Dairy Pure Global",
        "calories": 72,
        "protein": 12.5,
        "carbs": 2.8,
        "fats": 1.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-13",
        "name": "Authentic Strained Plain 0% Greek Skyr",
        "brand": "Nordic Dairy Global",
        "calories": 65,
        "protein": 11.5,
        "carbs": 4.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-14",
        "name": "Grass-Fed Beef Tenderloin Fillet Mignon",
        "brand": "Prime Angus Global",
        "calories": 185,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 8.5,
        "serving_size": "100g grilled",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      },
      {
        "id": "global-prot-15",
        "name": "Steamed King Prawns / Shrimps",
        "brand": "Ocean Harvest",
        "calories": 99,
        "protein": 21.5,
        "carbs": 0.5,
        "fats": 1.1,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "GLOBAL"
      }
    ],
    "carbs": [
      {
        "id": "global-carb-1",
        "name": "Whole Grain Rolled Oats 100% Natural",
        "brand": "Oat Harvest Global",
        "calories": 150,
        "protein": 5.0,
        "carbs": 27.0,
        "fats": 2.5,
        "serving_size": "40g dry",
        "serving_grams": 40,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-2",
        "name": "Organic Brown Basmati Rice Cooked",
        "brand": "Golden Grain Global",
        "calories": 165,
        "protein": 3.5,
        "carbs": 35.0,
        "fats": 1.0,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-3",
        "name": "Steamed Jasmine Fragrant White Rice",
        "brand": "Sun Grain Global",
        "calories": 170,
        "protein": 3.2,
        "carbs": 38.0,
        "fats": 0.4,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-4",
        "name": "Baked Russet Potato with Skin",
        "brand": "Farm Fresh Global",
        "calories": 93,
        "protein": 2.5,
        "carbs": 21.0,
        "fats": 0.1,
        "serving_size": "100g baked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-5",
        "name": "Roasted Orange Sweet Potato",
        "brand": "Organic Harvest Global",
        "calories": 86,
        "protein": 1.6,
        "carbs": 20.0,
        "fats": 0.1,
        "serving_size": "100g roasted",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-6",
        "name": "Organic Tri-Color Royal Quinoa Cooked",
        "brand": "Andes Harvest Global",
        "calories": 120,
        "protein": 4.4,
        "carbs": 21.3,
        "fats": 1.9,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-7",
        "name": "100% Spelt Wholegrain Sourdough Bread",
        "brand": "Artisan Bakery Global",
        "calories": 180,
        "protein": 7.5,
        "carbs": 33.0,
        "fats": 1.8,
        "serving_size": "2 slices (75g)",
        "serving_grams": 75,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-8",
        "name": "Boiled Red Kidney Beans Organic",
        "brand": "Harvest Beans Global",
        "calories": 127,
        "protein": 8.7,
        "carbs": 22.8,
        "fats": 0.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-9",
        "name": "Boiled Green Brown Lentils",
        "brand": "Whole Pulses Global",
        "calories": 116,
        "protein": 9.0,
        "carbs": 20.0,
        "fats": 0.4,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-10",
        "name": "Fresh Cavendish Banana",
        "brand": "Tropical Produce Global",
        "calories": 105,
        "protein": 1.3,
        "carbs": 27.0,
        "fats": 0.3,
        "serving_size": "1 medium (118g)",
        "serving_grams": 118,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-11",
        "name": "Fresh Wild Blueberries",
        "brand": "Berry Farms Global",
        "calories": 57,
        "protein": 0.7,
        "carbs": 14.5,
        "fats": 0.3,
        "serving_size": "100g berries",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GLOBAL"
      },
      {
        "id": "global-carb-12",
        "name": "Organic Medjool Premium Dates",
        "brand": "Desert Date Palms",
        "calories": 135,
        "protein": 0.8,
        "carbs": 36.0,
        "fats": 0.2,
        "serving_size": "2 dates (48g)",
        "serving_grams": 48,
        "category": "carbs",
        "country": "GLOBAL"
      }
    ],
    "fats": [
      {
        "id": "global-fats-1",
        "name": "Extra Virgin Olive Oil First Cold Pressed",
        "brand": "Mediterranean Olive Global",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-2",
        "name": "Pure Ripe Hass Avocado Flesh",
        "brand": "Avocado Orchards Global",
        "calories": 160,
        "protein": 2.0,
        "carbs": 8.5,
        "fats": 14.7,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-3",
        "name": "Raw Whole California Almonds",
        "brand": "Orchard Select Global",
        "calories": 165,
        "protein": 6.0,
        "carbs": 6.0,
        "fats": 14.0,
        "serving_size": "28g handful",
        "serving_grams": 28,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-4",
        "name": "Raw English Walnut Halves",
        "brand": "Nut Harvest Global",
        "calories": 195,
        "protein": 4.5,
        "carbs": 4.0,
        "fats": 19.5,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-5",
        "name": "100% Pure Natural Smooth Peanut Butter",
        "brand": "Pure Nut Global",
        "calories": 185,
        "protein": 8.0,
        "carbs": 6.0,
        "fats": 16.0,
        "serving_size": "2 tbsp (32g)",
        "serving_grams": 32,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-6",
        "name": "100% Raw Almond Butter (No Salt)",
        "brand": "Pure Nut Global",
        "calories": 190,
        "protein": 7.0,
        "carbs": 6.0,
        "fats": 17.0,
        "serving_size": "2 tbsp (32g)",
        "serving_grams": 32,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-7",
        "name": "Organic Black Chia Seeds",
        "brand": "Super Seeds Global",
        "calories": 135,
        "protein": 4.9,
        "carbs": 1.1,
        "fats": 8.7,
        "serving_size": "1 tbsp (28g)",
        "serving_grams": 28,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-8",
        "name": "Raw Golden Flax Seeds Milled",
        "brand": "Seed Harvest Global",
        "calories": 150,
        "protein": 5.0,
        "carbs": 8.0,
        "fats": 12.0,
        "serving_size": "2 tbsp (28g)",
        "serving_grams": 28,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-9",
        "name": "Pure C8/C10 MCT Oil Brain Fuel",
        "brand": "Keto Nutrition Global",
        "calories": 125,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-10",
        "name": "Grass-Fed Clarified Butter Ghee",
        "brand": "Traditional Pure Dairy",
        "calories": 112,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 12.5,
        "serving_size": "1 tbsp (14g)",
        "serving_grams": 14,
        "category": "fats",
        "country": "GLOBAL"
      },
      {
        "id": "global-fats-11",
        "name": "Raw Green Pumpkin Seeds Pepitas",
        "brand": "Whole Seeds Global",
        "calories": 165,
        "protein": 8.5,
        "carbs": 4.0,
        "fats": 14.0,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "GLOBAL"
      }
    ],
    "fastfood": [
      {
        "id": "global-fast-1",
        "name": "Classic Grilled Chicken & Brown Rice Bowl",
        "brand": "Athletic Prep Kitchen",
        "calories": 520,
        "protein": 46.0,
        "carbs": 58.0,
        "fats": 11.0,
        "serving_size": "1 bowl (420g)",
        "serving_grams": 420,
        "category": "fastfood",
        "country": "GLOBAL"
      },
      {
        "id": "global-fast-2",
        "name": "Double Lean Beef Burger Lettuce Wrap (No Bun)",
        "brand": "Gourmet Grill",
        "calories": 440,
        "protein": 36.0,
        "carbs": 4.0,
        "fats": 31.0,
        "serving_size": "1 wrap (250g)",
        "serving_grams": 250,
        "category": "fastfood",
        "country": "GLOBAL"
      },
      {
        "id": "global-fast-3",
        "name": "Fresh Salmon Poke Bowl with Edamame & Rice",
        "brand": "Pacific Poke",
        "calories": 550,
        "protein": 34.0,
        "carbs": 62.0,
        "fats": 17.0,
        "serving_size": "1 bowl (400g)",
        "serving_grams": 400,
        "category": "fastfood",
        "country": "GLOBAL"
      },
      {
        "id": "global-fast-4",
        "name": "Mediterranean Chicken Shawarma with Hummus",
        "brand": "Levant Express",
        "calories": 480,
        "protein": 38.0,
        "carbs": 42.0,
        "fats": 16.0,
        "serving_size": "1 plate (350g)",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "GLOBAL"
      },
      {
        "id": "global-fast-5",
        "name": "Subway 6-Inch Lean Turkey Breast on Wheat",
        "brand": "Subway Global",
        "calories": 280,
        "protein": 18.0,
        "carbs": 42.0,
        "fats": 3.5,
        "serving_size": "6-inch (220g)",
        "serving_grams": 220,
        "category": "fastfood",
        "country": "GLOBAL"
      },
      {
        "id": "global-fast-6",
        "name": "California Salmon & Avocado Sushi Roll (8 pcs)",
        "brand": "Sushi Bar Global",
        "calories": 320,
        "protein": 14.0,
        "carbs": 48.0,
        "fats": 8.5,
        "serving_size": "8 rolls (220g)",
        "serving_grams": 220,
        "category": "fastfood",
        "country": "GLOBAL"
      },
      {
        "id": "global-fast-7",
        "name": "Grilled Chicken Breast Caesar Salad (Light Dressing)",
        "brand": "Fresh Greens Global",
        "calories": 360,
        "protein": 36.0,
        "carbs": 12.0,
        "fats": 18.0,
        "serving_size": "1 bowl (300g)",
        "serving_grams": 300,
        "category": "fastfood",
        "country": "GLOBAL"
      }
    ],
    "drinks": [
      {
        "id": "global-drin-1",
        "name": "Pure Spring Mineral Water with Electrolytes",
        "brand": "Alpine Springs Global",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-2",
        "name": "Cold Brew Pure Black Coffee (Zero Sugar)",
        "brand": "Artisan Roast Global",
        "calories": 5,
        "protein": 0.5,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "350ml cup",
        "serving_grams": 350,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-3",
        "name": "Japanese Ceremonial Matcha Green Tea",
        "brand": "Zen Matcha Global",
        "calories": 5,
        "protein": 0.6,
        "carbs": 0.8,
        "fats": 0.0,
        "serving_size": "200ml cup",
        "serving_grams": 200,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-4",
        "name": "Unsweetened Plain Almond Milk",
        "brand": "Pure Plant Global",
        "calories": 30,
        "protein": 1.0,
        "carbs": 1.0,
        "fats": 2.5,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-5",
        "name": "100% Pure Raw Coconut Water",
        "brand": "Island Pure Global",
        "calories": 50,
        "protein": 1.0,
        "carbs": 11.0,
        "fats": 0.0,
        "serving_size": "330ml carton",
        "serving_grams": 330,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-6",
        "name": "BCAA Amino Hydration Zero Sugar Drink",
        "brand": "FitNutrition Global",
        "calories": 10,
        "protein": 2.5,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-7",
        "name": "Tart Cherry Muscle Recovery 100% Juice",
        "brand": "Orchard Select Global",
        "calories": 130,
        "protein": 1.5,
        "carbs": 31.0,
        "fats": 0.2,
        "serving_size": "240ml glass",
        "serving_grams": 240,
        "category": "drinks",
        "country": "GLOBAL"
      },
      {
        "id": "global-drin-8",
        "name": "Sparkling Natural Mineral Water with Fresh Lemon",
        "brand": "Pure Fizz Global",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "330ml bottle",
        "serving_grams": 330,
        "category": "drinks",
        "country": "GLOBAL"
      }
    ]
  }
};
