import { RegionalFoodMap } from './types';

export const AMERICAS_FOODS: RegionalFoodMap = {
  "US": {
    "protein": [
      {
        "id": "us-prot-1",
        "name": "Optimum Nutrition Gold Standard Whey Double Rich Choc",
        "brand": "Optimum Nutrition US",
        "calories": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fats": 1.5,
        "serving_size": "1 scoop (30.4g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-2",
        "name": "Fairlife Nutrition Plan 30g Protein Shake Chocolate",
        "brand": "Fairlife US",
        "calories": 150,
        "protein": 30.0,
        "carbs": 3.0,
        "fats": 2.5,
        "serving_size": "1 bottle (340ml)",
        "serving_grams": 340,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-3",
        "name": "Kirkland Signature Boneless Skinless Chicken Breast",
        "brand": "Costco Kirkland US",
        "calories": 140,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 3.0,
        "serving_size": "4 oz (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-4",
        "name": "Certified Angus Beef 93/7 Lean Ground Beef",
        "brand": "Certified Angus US",
        "calories": 170,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 8.0,
        "serving_size": "4 oz (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-5",
        "name": "Wild Alaskan Sockeye Salmon Fillet",
        "brand": "Trader Joe's / Whole Foods",
        "calories": 180,
        "protein": 25.0,
        "carbs": 0.0,
        "fats": 9.0,
        "serving_size": "4 oz (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-6",
        "name": "Dannon Light & Fit Greek Yogurt Vanilla",
        "brand": "Dannon US",
        "calories": 80,
        "protein": 12.0,
        "carbs": 8.0,
        "fats": 0.0,
        "serving_size": "1 cup (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-7",
        "name": "Eggland's Best 100% Liquid Egg Whites",
        "brand": "Eggland's Best US",
        "calories": 25,
        "protein": 5.0,
        "carbs": 1.0,
        "fats": 0.0,
        "serving_size": "3 tbsp (46g)",
        "serving_grams": 46,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-8",
        "name": "Jennie-O Extra Lean 99% Ground Turkey Breast",
        "brand": "Jennie-O US",
        "calories": 120,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 1.5,
        "serving_size": "4 oz (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-9",
        "name": "Wild Planet Albacore Wild Tuna in Water",
        "brand": "Wild Planet US",
        "calories": 130,
        "protein": 29.0,
        "carbs": 0.0,
        "fats": 1.5,
        "serving_size": "1 can (142g)",
        "serving_grams": 142,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-10",
        "name": "Quest Nutrition Chocolate Chip Cookie Dough Bar",
        "brand": "Quest Nutrition US",
        "calories": 200,
        "protein": 21.0,
        "carbs": 22.0,
        "fats": 9.0,
        "serving_size": "1 bar (60g)",
        "serving_grams": 60,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-11",
        "name": "Premier Protein High Protein Shake Cafe Latte",
        "brand": "Premier Protein US",
        "calories": 160,
        "protein": 30.0,
        "carbs": 4.0,
        "fats": 3.0,
        "serving_size": "1 shake (325ml)",
        "serving_grams": 325,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-12",
        "name": "USDA Choice Center-Cut Top Sirloin Steak",
        "brand": "USDA Choice US",
        "calories": 190,
        "protein": 27.0,
        "carbs": 0.0,
        "fats": 8.5,
        "serving_size": "4 oz (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-13",
        "name": "Nasoya Organic Extra Firm Tofu Super Protein",
        "brand": "Nasoya US",
        "calories": 130,
        "protein": 14.0,
        "carbs": 3.0,
        "fats": 7.0,
        "serving_size": "3 oz (85g)",
        "serving_grams": 85,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-14",
        "name": "Good Culture Organic Low Fat Cottage Cheese 2%",
        "brand": "Good Culture US",
        "calories": 90,
        "protein": 14.0,
        "carbs": 3.0,
        "fats": 2.5,
        "serving_size": "1/2 cup (110g)",
        "serving_grams": 110,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-15",
        "name": "Fresh Wild Caught Gulf White Shrimp",
        "brand": "Whole Foods US",
        "calories": 100,
        "protein": 23.0,
        "carbs": 1.0,
        "fats": 1.0,
        "serving_size": "4 oz (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-16",
        "name": "Vital Farms Pasture-Raised Large Eggs (2 eggs)",
        "brand": "Vital Farms US",
        "calories": 140,
        "protein": 12.0,
        "carbs": 0.0,
        "fats": 10.0,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-17",
        "name": "Ghost Whey Protein Powder Cereal Milk",
        "brand": "Ghost Lifestyle US",
        "calories": 130,
        "protein": 25.0,
        "carbs": 4.0,
        "fats": 1.5,
        "serving_size": "1 scoop (34.5g)",
        "serving_grams": 35,
        "category": "protein",
        "country": "US"
      },
      {
        "id": "us-prot-18",
        "name": "Applegate Natural Uncured Turkey Bacon",
        "brand": "Applegate US",
        "calories": 70,
        "protein": 12.0,
        "carbs": 0.0,
        "fats": 3.0,
        "serving_size": "2 slices (28g)",
        "serving_grams": 28,
        "category": "protein",
        "country": "US"
      }
    ],
    "carbs": [
      {
        "id": "us-carb-1",
        "name": "Quaker Old Fashioned Rolled Oats 100% Whole Grain",
        "brand": "Quaker US",
        "calories": 150,
        "protein": 5.0,
        "carbs": 27.0,
        "fats": 2.5,
        "serving_size": "1/2 cup dry (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-2",
        "name": "Uncle Ben's Ready Rice Whole Grain Brown",
        "brand": "Ben's Original US",
        "calories": 220,
        "protein": 5.0,
        "carbs": 45.0,
        "fats": 2.5,
        "serving_size": "1 cup (140g)",
        "serving_grams": 140,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-3",
        "name": "Large Idaho Russet Baking Potato",
        "brand": "Idaho Potato US",
        "calories": 168,
        "protein": 4.5,
        "carbs": 38.0,
        "fats": 0.2,
        "serving_size": "1 medium (173g)",
        "serving_grams": 173,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-4",
        "name": "Organic Jewel Sweet Potato Baked",
        "brand": "Organic US Produce",
        "calories": 103,
        "protein": 2.3,
        "carbs": 24.0,
        "fats": 0.2,
        "serving_size": "1 medium (114g)",
        "serving_grams": 114,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-5",
        "name": "Dave's Killer Bread 21 Whole Grains and Seeds",
        "brand": "Dave's Killer Bread",
        "calories": 110,
        "protein": 5.0,
        "carbs": 22.0,
        "fats": 1.5,
        "serving_size": "1 slice (45g)",
        "serving_grams": 45,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-6",
        "name": "Banza Chickpea Pasta Rotini (High Protein)",
        "brand": "Banza US",
        "calories": 190,
        "protein": 11.0,
        "carbs": 35.0,
        "fats": 3.0,
        "serving_size": "2 oz dry (56g)",
        "serving_grams": 56,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-7",
        "name": "Kodiak Cakes Power Cakes Flapjack Mix",
        "brand": "Kodiak Cakes US",
        "calories": 190,
        "protein": 14.0,
        "carbs": 30.0,
        "fats": 2.0,
        "serving_size": "1/2 cup mix (53g)",
        "serving_grams": 53,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-8",
        "name": "Lundberg Organic Wild Blend Gourmet Rice",
        "brand": "Lundberg US",
        "calories": 160,
        "protein": 4.0,
        "carbs": 34.0,
        "fats": 1.0,
        "serving_size": "1/4 cup dry (45g)",
        "serving_grams": 45,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-9",
        "name": "Fresh Honeycrisp Apple",
        "brand": "Stemilt US Produce",
        "calories": 95,
        "protein": 0.5,
        "carbs": 25.0,
        "fats": 0.3,
        "serving_size": "1 medium (182g)",
        "serving_grams": 182,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-10",
        "name": "Bush's Best Canned Black Beans Low Sodium",
        "brand": "Bush's US",
        "calories": 110,
        "protein": 7.0,
        "carbs": 20.0,
        "fats": 0.5,
        "serving_size": "1/2 cup (130g)",
        "serving_grams": 130,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-11",
        "name": "Thomas' 100% Whole Wheat Plain Bagel",
        "brand": "Thomas' US",
        "calories": 240,
        "protein": 10.0,
        "carbs": 48.0,
        "fats": 1.5,
        "serving_size": "1 bagel (98g)",
        "serving_grams": 98,
        "category": "carbs",
        "country": "US"
      },
      {
        "id": "us-carb-12",
        "name": "Mission Carb Balance Soft Taco Whole Wheat",
        "brand": "Mission Foods US",
        "calories": 70,
        "protein": 5.0,
        "carbs": 19.0,
        "fats": 2.5,
        "serving_size": "1 tortilla (42g)",
        "serving_grams": 42,
        "category": "carbs",
        "country": "US"
      }
    ],
    "fats": [
      {
        "id": "us-fats-1",
        "name": "Kirkland Signature Organic Extra Virgin Olive Oil",
        "brand": "Costco Kirkland US",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-2",
        "name": "Jif Natural Creamy Peanut Butter (90% Peanuts)",
        "brand": "Jif US",
        "calories": 190,
        "protein": 7.0,
        "carbs": 8.0,
        "fats": 16.0,
        "serving_size": "2 tbsp (33g)",
        "serving_grams": 33,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-3",
        "name": "Fresh California Hass Avocado Ripe",
        "brand": "California Avocado Comm",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-4",
        "name": "Blue Diamond Whole Natural Raw Almonds",
        "brand": "Blue Diamond US",
        "calories": 160,
        "protein": 6.0,
        "carbs": 6.0,
        "fats": 14.0,
        "serving_size": "28 nuts (28g)",
        "serving_grams": 28,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-5",
        "name": "Wonderful Pistachios Roasted & Lightly Salted",
        "brand": "Wonderful US",
        "calories": 160,
        "protein": 6.0,
        "carbs": 8.0,
        "fats": 13.0,
        "serving_size": "1/2 cup with shells",
        "serving_grams": 30,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-6",
        "name": "Kerrygold Pure Irish Salted Butter",
        "brand": "Kerrygold US",
        "calories": 100,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 11.0,
        "serving_size": "1 tbsp (14g)",
        "serving_grams": 14,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-7",
        "name": "Navitas Organics Chia Seeds Superfood",
        "brand": "Navitas US",
        "calories": 60,
        "protein": 2.0,
        "carbs": 5.0,
        "fats": 3.5,
        "serving_size": "1 tbsp (12g)",
        "serving_grams": 12,
        "category": "fats",
        "country": "US"
      },
      {
        "id": "us-fats-8",
        "name": "Philadelphia Whipped Original Cream Cheese",
        "brand": "Philadelphia US",
        "calories": 50,
        "protein": 1.0,
        "carbs": 1.0,
        "fats": 4.5,
        "serving_size": "2 tbsp (22g)",
        "serving_grams": 22,
        "category": "fats",
        "country": "US"
      }
    ],
    "fastfood": [
      {
        "id": "us-fast-1",
        "name": "Chipotle Chicken Burrito Bowl (Brown Rice & Black Beans)",
        "brand": "Chipotle Mexican Grill",
        "calories": 650,
        "protein": 53.0,
        "carbs": 68.0,
        "fats": 18.0,
        "serving_size": "1 bowl (470g)",
        "serving_grams": 470,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-2",
        "name": "Chipotle Barbacoa Salad Bowl with Guacamole",
        "brand": "Chipotle Mexican Grill",
        "calories": 580,
        "protein": 42.0,
        "carbs": 24.0,
        "fats": 36.0,
        "serving_size": "1 salad bowl",
        "serving_grams": 410,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-3",
        "name": "Chick-fil-A Grilled Chicken Breast Sandwich",
        "brand": "Chick-fil-A US",
        "calories": 390,
        "protein": 28.0,
        "carbs": 44.0,
        "fats": 12.0,
        "serving_size": "1 sandwich (218g)",
        "serving_grams": 218,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-4",
        "name": "In-N-Out Double-Double Protein Style (Lettuce Wrapped)",
        "brand": "In-N-Out Burger",
        "calories": 520,
        "protein": 33.0,
        "carbs": 11.0,
        "fats": 39.0,
        "serving_size": "1 burger (330g)",
        "serving_grams": 330,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-5",
        "name": "In-N-Out Double-Double with Onion Traditional",
        "brand": "In-N-Out Burger",
        "calories": 670,
        "protein": 37.0,
        "carbs": 39.0,
        "fats": 41.0,
        "serving_size": "1 burger (330g)",
        "serving_grams": 330,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-6",
        "name": "Panda Express String Bean Chicken Breast",
        "brand": "Panda Express US",
        "calories": 190,
        "protein": 14.0,
        "carbs": 13.0,
        "fats": 9.0,
        "serving_size": "1 serving (160g)",
        "serving_grams": 160,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-7",
        "name": "Wendy's Classic Large Rich & Meaty Chili",
        "brand": "Wendy's US",
        "calories": 340,
        "protein": 22.0,
        "carbs": 31.0,
        "fats": 15.0,
        "serving_size": "1 large cup (340g)",
        "serving_grams": 340,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-8",
        "name": "Subway 6-Inch Oven Roasted Turkey Breast Sub",
        "brand": "Subway US",
        "calories": 270,
        "protein": 18.0,
        "carbs": 41.0,
        "fats": 3.5,
        "serving_size": "6-inch (219g)",
        "serving_grams": 219,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-9",
        "name": "McDonald's US Egg McMuffin Breakfast Sandwich",
        "brand": "McDonald's US",
        "calories": 310,
        "protein": 17.0,
        "carbs": 30.0,
        "fats": 13.0,
        "serving_size": "1 sandwich (136g)",
        "serving_grams": 136,
        "category": "fastfood",
        "country": "US"
      },
      {
        "id": "us-fast-10",
        "name": "Five Guys Little Bacon Burger (No Bun / Bowl)",
        "brand": "Five Guys US",
        "calories": 390,
        "protein": 24.0,
        "carbs": 1.0,
        "fats": 32.0,
        "serving_size": "1 bowl (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "US"
      }
    ],
    "drinks": [
      {
        "id": "us-drin-1",
        "name": "Fairlife 2% Ultra-Filtered High Protein Milk",
        "brand": "Fairlife US",
        "calories": 120,
        "protein": 13.0,
        "carbs": 6.0,
        "fats": 4.5,
        "serving_size": "1 cup (240ml)",
        "serving_grams": 240,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-2",
        "name": "Gatorade Zero Sugar Thirst Quencher Glacier Cherry",
        "brand": "Gatorade US",
        "calories": 5,
        "protein": 0.0,
        "carbs": 1.0,
        "fats": 0.0,
        "serving_size": "20 fl oz (591ml)",
        "serving_grams": 591,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-3",
        "name": "Celsius Sparkling Arctic Vibe Energy Drink",
        "brand": "Celsius US",
        "calories": 10,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "12 fl oz (355ml)",
        "serving_grams": 355,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-4",
        "name": "Starbucks Nitro Cold Brew Unsweetened Black",
        "brand": "Starbucks US",
        "calories": 5,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 can (285ml)",
        "serving_grams": 285,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-5",
        "name": "Prime Hydration Drink Ice Pop Electrolytes",
        "brand": "Prime Beverages US",
        "calories": 20,
        "protein": 0.0,
        "carbs": 5.0,
        "fats": 0.0,
        "serving_size": "1 bottle (500ml)",
        "serving_grams": 500,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-6",
        "name": "Core Power Elite 42g High Protein Milk Shake",
        "brand": "Fairlife US",
        "calories": 230,
        "protein": 42.0,
        "carbs": 8.0,
        "fats": 3.5,
        "serving_size": "14 fl oz (414ml)",
        "serving_grams": 414,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-7",
        "name": "Vita Coco 100% Pure Coconut Water",
        "brand": "Vita Coco US",
        "calories": 60,
        "protein": 1.0,
        "carbs": 15.0,
        "fats": 0.0,
        "serving_size": "1 bottle (330ml)",
        "serving_grams": 330,
        "category": "drinks",
        "country": "US"
      },
      {
        "id": "us-drin-8",
        "name": "Liquid I.V. Hydration Multiplier Lemon Lime",
        "brand": "Liquid I.V. US",
        "calories": 45,
        "protein": 0.0,
        "carbs": 11.0,
        "fats": 0.0,
        "serving_size": "1 packet in 500ml",
        "serving_grams": 500,
        "category": "drinks",
        "country": "US"
      }
    ]
  },
  "CA": {
    "protein": [
      {
        "id": "ca-prot-1",
        "name": "Maple Leaf Prime Fresh Boneless Chicken Breast",
        "brand": "Maple Leaf CA",
        "calories": 140,
        "protein": 27.0,
        "carbs": 0.0,
        "fats": 3.0,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-2",
        "name": "Burnbrae Farms Naturegg Liquid Egg Whites",
        "brand": "Burnbrae Farms CA",
        "calories": 50,
        "protein": 11.0,
        "carbs": 1.0,
        "fats": 0.0,
        "serving_size": "100ml",
        "serving_grams": 100,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-3",
        "name": "President's Choice Extra Lean Ground Beef 90/10",
        "brand": "PC Loblaws CA",
        "calories": 160,
        "protein": 23.0,
        "carbs": 0.0,
        "fats": 7.5,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-4",
        "name": "Canadian Fresh Atlantic Salmon Fillet",
        "brand": "Jail Island CA",
        "calories": 205,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 12.5,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-5",
        "name": "Oikos 0% Greek Yogurt Plain High Protein",
        "brand": "Danone Oikos CA",
        "calories": 90,
        "protein": 17.0,
        "carbs": 6.0,
        "fats": 0.0,
        "serving_size": "175g serving",
        "serving_grams": 175,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-6",
        "name": "Pure Protein Chocolate Deluxe High Protein Bar",
        "brand": "Pure Protein CA",
        "calories": 180,
        "protein": 20.0,
        "carbs": 16.0,
        "fats": 4.5,
        "serving_size": "1 bar (50g)",
        "serving_grams": 50,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-7",
        "name": "Whey Gourmet 100% Whey Protein Isolate",
        "brand": "Whey Gourmet CA",
        "calories": 120,
        "protein": 25.0,
        "carbs": 2.0,
        "fats": 1.0,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-8",
        "name": "Kirkland Signature Solid White Albacore Tuna",
        "brand": "Costco Kirkland CA",
        "calories": 130,
        "protein": 30.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "1 can (142g)",
        "serving_grams": 142,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-9",
        "name": "Black Diamond Natural Marble Cheddar Cheese",
        "brand": "Black Diamond CA",
        "calories": 200,
        "protein": 12.0,
        "carbs": 0.5,
        "fats": 17.0,
        "serving_size": "50g serve",
        "serving_grams": 50,
        "category": "protein",
        "country": "CA"
      },
      {
        "id": "ca-prot-10",
        "name": "Sunrise Soya Foods Organic Extra Firm Tofu",
        "brand": "Sunrise Soya CA",
        "calories": 130,
        "protein": 15.0,
        "carbs": 2.0,
        "fats": 7.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "CA"
      }
    ],
    "carbs": [
      {
        "id": "ca-carb-1",
        "name": "Quaker Canadian 100% Whole Grain Large Rolled Oats",
        "brand": "Quaker CA",
        "calories": 150,
        "protein": 5.0,
        "carbs": 27.0,
        "fats": 2.5,
        "serving_size": "1/3 cup dry (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "CA"
      },
      {
        "id": "ca-carb-2",
        "name": "Prince Edward Island Russet Baking Potatoes",
        "brand": "PEI Potatoes CA",
        "calories": 160,
        "protein": 4.0,
        "carbs": 37.0,
        "fats": 0.2,
        "serving_size": "1 medium (170g)",
        "serving_grams": 170,
        "category": "carbs",
        "country": "CA"
      },
      {
        "id": "ca-carb-3",
        "name": "Dempster's 100% Whole Grains Multigrain Bread",
        "brand": "Dempster's CA",
        "calories": 110,
        "protein": 5.0,
        "carbs": 20.0,
        "fats": 1.5,
        "serving_size": "1 slice (43g)",
        "serving_grams": 43,
        "category": "carbs",
        "country": "CA"
      },
      {
        "id": "ca-carb-4",
        "name": "President's Choice Blue Menu 100% Organic Quinoa",
        "brand": "PC Loblaws CA",
        "calories": 170,
        "protein": 6.0,
        "carbs": 31.0,
        "fats": 2.5,
        "serving_size": "1/4 cup dry (45g)",
        "serving_grams": 45,
        "category": "carbs",
        "country": "CA"
      },
      {
        "id": "ca-carb-5",
        "name": "Pure Canadian Maple Syrup Grade A Amber",
        "brand": "PC Organics CA",
        "calories": 105,
        "protein": 0.0,
        "carbs": 27.0,
        "fats": 0.0,
        "serving_size": "2 tbsp (30ml)",
        "serving_grams": 30,
        "category": "carbs",
        "country": "CA"
      },
      {
        "id": "ca-carb-6",
        "name": "Uncle Ben's Bistro Express Long Grain & Wild",
        "brand": "Ben's Original CA",
        "calories": 210,
        "protein": 5.0,
        "carbs": 44.0,
        "fats": 2.0,
        "serving_size": "1 cup (125g)",
        "serving_grams": 125,
        "category": "carbs",
        "country": "CA"
      },
      {
        "id": "ca-carb-7",
        "name": "McCain Sweet Potato Superfries Baked",
        "brand": "McCain CA",
        "calories": 140,
        "protein": 1.5,
        "carbs": 23.0,
        "fats": 5.0,
        "serving_size": "85g serve",
        "serving_grams": 85,
        "category": "carbs",
        "country": "CA"
      }
    ],
    "fats": [
      {
        "id": "ca-fats-1",
        "name": "Kraft Smooth Natural 100% Peanut Butter",
        "brand": "Kraft CA",
        "calories": 190,
        "protein": 8.0,
        "carbs": 6.0,
        "fats": 16.0,
        "serving_size": "2 tbsp (30g)",
        "serving_grams": 30,
        "category": "fats",
        "country": "CA"
      },
      {
        "id": "ca-fats-2",
        "name": "President's Choice 100% First Cold Pressed EVOO",
        "brand": "PC Loblaws CA",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "CA"
      },
      {
        "id": "ca-fats-3",
        "name": "Manitoba Harvest Organic Shelled Hemp Hearts",
        "brand": "Manitoba Harvest CA",
        "calories": 180,
        "protein": 10.0,
        "carbs": 1.0,
        "fats": 15.0,
        "serving_size": "3 tbsp (30g)",
        "serving_grams": 30,
        "category": "fats",
        "country": "CA"
      },
      {
        "id": "ca-fats-4",
        "name": "Fresh Ripe Hass Avocado Mexico/CA",
        "brand": "Produce CA",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "CA"
      },
      {
        "id": "ca-fats-5",
        "name": "Kirkland Signature Roasted Almonds Unsalted",
        "brand": "Costco CA",
        "calories": 160,
        "protein": 6.0,
        "carbs": 6.0,
        "fats": 14.0,
        "serving_size": "28g handful",
        "serving_grams": 28,
        "category": "fats",
        "country": "CA"
      },
      {
        "id": "ca-fats-6",
        "name": "Gay Lea Pure Salted Canadian Dairy Butter",
        "brand": "Gay Lea CA",
        "calories": 100,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 11.0,
        "serving_size": "1 tbsp (14g)",
        "serving_grams": 14,
        "category": "fats",
        "country": "CA"
      }
    ],
    "fastfood": [
      {
        "id": "ca-fast-1",
        "name": "Tim Hortons Turkey Bacon Club Sandwich",
        "brand": "Tim Hortons CA",
        "calories": 490,
        "protein": 26.0,
        "carbs": 52.0,
        "fats": 20.0,
        "serving_size": "1 sandwich (235g)",
        "serving_grams": 235,
        "category": "fastfood",
        "country": "CA"
      },
      {
        "id": "ca-fast-2",
        "name": "Tim Hortons Farmer's Breakfast Wrap (Egg & Bacon)",
        "brand": "Tim Hortons CA",
        "calories": 510,
        "protein": 20.0,
        "carbs": 41.0,
        "fats": 30.0,
        "serving_size": "1 wrap (210g)",
        "serving_grams": 210,
        "category": "fastfood",
        "country": "CA"
      },
      {
        "id": "ca-fast-3",
        "name": "Classic Montreal Smoked Meat Sandwich on Rye",
        "brand": "Schwartz's Montreal",
        "calories": 580,
        "protein": 42.0,
        "carbs": 38.0,
        "fats": 28.0,
        "serving_size": "1 sandwich (280g)",
        "serving_grams": 280,
        "category": "fastfood",
        "country": "CA"
      },
      {
        "id": "ca-fast-4",
        "name": "Harvey's Original Flame-Grilled Beef Burger",
        "brand": "Harvey's CA",
        "calories": 370,
        "protein": 19.0,
        "carbs": 33.0,
        "fats": 18.0,
        "serving_size": "1 burger (155g)",
        "serving_grams": 155,
        "category": "fastfood",
        "country": "CA"
      },
      {
        "id": "ca-fast-5",
        "name": "Swiss Chalet Quarter Chicken Dinner (Skin Off)",
        "brand": "Swiss Chalet CA",
        "calories": 420,
        "protein": 46.0,
        "carbs": 28.0,
        "fats": 14.0,
        "serving_size": "1 plate",
        "serving_grams": 340,
        "category": "fastfood",
        "country": "CA"
      },
      {
        "id": "ca-fast-6",
        "name": "A&W Canada Teen Burger with Cheddar",
        "brand": "A&W Canada",
        "calories": 500,
        "protein": 25.0,
        "carbs": 40.0,
        "fats": 28.0,
        "serving_size": "1 burger (215g)",
        "serving_grams": 215,
        "category": "fastfood",
        "country": "CA"
      }
    ],
    "drinks": [
      {
        "id": "ca-drin-1",
        "name": "BioSteel Sports Hydration Drink Blue Raspberry",
        "brand": "BioSteel CA",
        "calories": 15,
        "protein": 0.0,
        "carbs": 3.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "CA"
      },
      {
        "id": "ca-drin-2",
        "name": "Fairlife Canada 2% Ultrafiltered High Protein Milk",
        "brand": "Fairlife CA",
        "calories": 120,
        "protein": 13.0,
        "carbs": 6.0,
        "fats": 4.5,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "CA"
      },
      {
        "id": "ca-drin-3",
        "name": "Canada Dry Zero Sugar Ginger Ale",
        "brand": "Canada Dry CA",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "355ml can",
        "serving_grams": 355,
        "category": "drinks",
        "country": "CA"
      },
      {
        "id": "ca-drin-4",
        "name": "Oasis 100% Pure Orange Juice with Pulp",
        "brand": "Lassonde Oasis CA",
        "calories": 110,
        "protein": 2.0,
        "carbs": 26.0,
        "fats": 0.0,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "CA"
      },
      {
        "id": "ca-drin-5",
        "name": "Tim Hortons Fresh Brewed Dark Roast Coffee",
        "brand": "Tim Hortons CA",
        "calories": 5,
        "protein": 0.5,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "Medium (414ml)",
        "serving_grams": 414,
        "category": "drinks",
        "country": "CA"
      },
      {
        "id": "ca-drin-6",
        "name": "Silk Canada Unsweetened Almond Milk",
        "brand": "Silk CA",
        "calories": 30,
        "protein": 1.0,
        "carbs": 1.0,
        "fats": 2.5,
        "serving_size": "250ml cup",
        "serving_grams": 250,
        "category": "drinks",
        "country": "CA"
      }
    ]
  },
  "MX": {
    "protein": [
      {
        "id": "mx-prot-1",
        "name": "Pechuga de Pollo Fresca a la Plancha Sin Piel",
        "brand": "Bachoco MX",
        "calories": 165,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.6,
        "serving_size": "100g cocida",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-2",
        "name": "Bistec de Res Diezmillo Limpio Asado",
        "brand": "Sukarne MX",
        "calories": 185,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 8.5,
        "serving_size": "100g asado",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-3",
        "name": "Huevos San Juan Blancos Frescos (2 piezas)",
        "brand": "San Juan MX",
        "calories": 140,
        "protein": 12.0,
        "carbs": 0.8,
        "fats": 9.5,
        "serving_size": "2 piezas (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-4",
        "name": "Atún Dolores en Agua Aleta Amarilla",
        "brand": "Dolores MX",
        "calories": 115,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "1 lata (140g)",
        "serving_grams": 140,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-5",
        "name": "Queso Panela Lala Light Reducido en Grasa",
        "brand": "Lala MX",
        "calories": 180,
        "protein": 18.0,
        "carbs": 3.0,
        "fats": 10.5,
        "serving_size": "100g rebanada",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-6",
        "name": "Frijoles Negros Enteros Cocidos Caseros",
        "brand": "La Costeña MX",
        "calories": 120,
        "protein": 8.5,
        "carbs": 21.0,
        "fats": 0.6,
        "serving_size": "1 taza (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-7",
        "name": "Proteína Vegetal en Polvo Birdman Falcon",
        "brand": "Birdman MX",
        "calories": 130,
        "protein": 24.0,
        "carbs": 3.0,
        "fats": 2.5,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-8",
        "name": "Filete de Huachinango Pescado Blanco a la Talla",
        "brand": "Mercado del Mar MX",
        "calories": 110,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 2.0,
        "serving_size": "100g filete",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-9",
        "name": "Requesón Fresco Artesanal de Rancho",
        "brand": "Lácteos MX",
        "calories": 140,
        "protein": 14.0,
        "carbs": 4.0,
        "fats": 7.5,
        "serving_size": "100g porción",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      },
      {
        "id": "mx-prot-10",
        "name": "Cecina de Yecapixtla Magra Asada al Carbón",
        "brand": "Tradición Morelos MX",
        "calories": 195,
        "protein": 30.0,
        "carbs": 0.0,
        "fats": 8.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "MX"
      }
    ],
    "carbs": [
      {
        "id": "mx-carb-1",
        "name": "Tortilla de Maíz Nixtamalizada Tradicional (2 pzas)",
        "brand": "Tortillería MX",
        "calories": 110,
        "protein": 2.8,
        "carbs": 24.0,
        "fats": 1.0,
        "serving_size": "2 tortillas (50g)",
        "serving_grams": 50,
        "category": "carbs",
        "country": "MX"
      },
      {
        "id": "mx-carb-2",
        "name": "Arroz Rojo Mexicano Casero con Jitomate",
        "brand": "Receta Casera MX",
        "calories": 160,
        "protein": 3.0,
        "carbs": 34.0,
        "fats": 2.0,
        "serving_size": "1 taza (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "MX"
      },
      {
        "id": "mx-carb-3",
        "name": "Camote Amarillo Horneado con Canela",
        "brand": "Mercado MX",
        "calories": 95,
        "protein": 1.8,
        "carbs": 22.0,
        "fats": 0.2,
        "serving_size": "100g horneado",
        "serving_grams": 100,
        "category": "carbs",
        "country": "MX"
      },
      {
        "id": "mx-carb-4",
        "name": "Avena en Hojuelas Integral Quaker México",
        "brand": "Quaker MX",
        "calories": 150,
        "protein": 5.0,
        "carbs": 27.0,
        "fats": 2.5,
        "serving_size": "40g porción",
        "serving_grams": 40,
        "category": "carbs",
        "country": "MX"
      },
      {
        "id": "mx-carb-5",
        "name": "Totopos Horneados Saníssimo de Maíz sin Grasa",
        "brand": "Saníssimo MX",
        "calories": 75,
        "protein": 2.0,
        "carbs": 16.0,
        "fats": 0.5,
        "serving_size": "4 piezas (20g)",
        "serving_grams": 20,
        "category": "carbs",
        "country": "MX"
      },
      {
        "id": "mx-carb-6",
        "name": "Elote Amarillo Desgranado con Sal y Limón",
        "brand": "Mercado MX",
        "calories": 125,
        "protein": 4.2,
        "carbs": 27.0,
        "fats": 1.5,
        "serving_size": "1 taza (140g)",
        "serving_grams": 140,
        "category": "carbs",
        "country": "MX"
      },
      {
        "id": "mx-carb-7",
        "name": "Pan Tostado Integral Clásico Bimbo",
        "brand": "Bimbo MX",
        "calories": 80,
        "protein": 3.0,
        "carbs": 15.0,
        "fats": 1.0,
        "serving_size": "1 rebanada (25g)",
        "serving_grams": 25,
        "category": "carbs",
        "country": "MX"
      }
    ],
    "fats": [
      {
        "id": "mx-fats-1",
        "name": "Aguacate Hass Mexicano Michoacano Maduro",
        "brand": "Aguacates de México",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 pieza (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "MX"
      },
      {
        "id": "mx-fats-2",
        "name": "Pepitas de Calabaza Tostadas con Sal de Mar",
        "brand": "Verde Valle MX",
        "calories": 165,
        "protein": 8.5,
        "carbs": 4.0,
        "fats": 14.0,
        "serving_size": "30g porción",
        "serving_grams": 30,
        "category": "fats",
        "country": "MX"
      },
      {
        "id": "mx-fats-3",
        "name": "Aceite de Oliva Extra Virgen La Gitana",
        "brand": "La Gitana MX",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 cda (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "MX"
      },
      {
        "id": "mx-fats-4",
        "name": "Cacahuates Tostados Sin Sal Añadida",
        "brand": "Mafer MX",
        "calories": 170,
        "protein": 7.5,
        "carbs": 5.0,
        "fats": 14.5,
        "serving_size": "30g puñado",
        "serving_grams": 30,
        "category": "fats",
        "country": "MX"
      },
      {
        "id": "mx-fats-5",
        "name": "Crema Lala Reducida en Grasa Clásica",
        "brand": "Lala MX",
        "calories": 45,
        "protein": 0.8,
        "carbs": 1.2,
        "fats": 4.2,
        "serving_size": "2 cdas (30g)",
        "serving_grams": 30,
        "category": "fats",
        "country": "MX"
      },
      {
        "id": "mx-fats-6",
        "name": "Mantequilla Gloria Pura con Sal",
        "brand": "Gloria MX",
        "calories": 100,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 11.0,
        "serving_size": "1 cda (14g)",
        "serving_grams": 14,
        "category": "fats",
        "country": "MX"
      }
    ],
    "fastfood": [
      {
        "id": "mx-fast-1",
        "name": "Tacos al Pastor con Piña y Cebolla (Orden de 3)",
        "brand": "Taquería Tradicional MX",
        "calories": 390,
        "protein": 26.0,
        "carbs": 38.0,
        "fats": 15.0,
        "serving_size": "3 tacos (210g)",
        "serving_grams": 210,
        "category": "fastfood",
        "country": "MX"
      },
      {
        "id": "mx-fast-2",
        "name": "Tacos de Barbacoa de Res Estilo Hidalgo (2 pzas)",
        "brand": "El Pica MX",
        "calories": 320,
        "protein": 28.0,
        "carbs": 26.0,
        "fats": 12.0,
        "serving_size": "2 tacos (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "MX"
      },
      {
        "id": "mx-fast-3",
        "name": "Quesadilla de Comal con Flor de Calabaza y Queso",
        "brand": "Antojitos MX",
        "calories": 220,
        "protein": 11.0,
        "carbs": 24.0,
        "fats": 9.0,
        "serving_size": "1 pieza (140g)",
        "serving_grams": 140,
        "category": "fastfood",
        "country": "MX"
      },
      {
        "id": "mx-fast-4",
        "name": "Pollo Asado al Carbón Pechuga sin Piel",
        "brand": "Pollo Feliz MX",
        "calories": 280,
        "protein": 48.0,
        "carbs": 0.0,
        "fats": 9.5,
        "serving_size": "1/4 pechuga (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "MX"
      },
      {
        "id": "mx-fast-5",
        "name": "Burrito Norteño de Carne Asada al Carbón",
        "brand": "Taquería Sonora MX",
        "calories": 520,
        "protein": 36.0,
        "carbs": 48.0,
        "fats": 19.0,
        "serving_size": "1 pieza (300g)",
        "serving_grams": 300,
        "category": "fastfood",
        "country": "MX"
      },
      {
        "id": "mx-fast-6",
        "name": "Tacos de Pescado Rebosado Estilo Ensenada (2 pzas)",
        "brand": "Baja Fish Tacos MX",
        "calories": 380,
        "protein": 22.0,
        "carbs": 42.0,
        "fats": 14.0,
        "serving_size": "2 tacos (220g)",
        "serving_grams": 220,
        "category": "fastfood",
        "country": "MX"
      }
    ],
    "drinks": [
      {
        "id": "mx-drin-1",
        "name": "Agua Fresca de Flor de Jamaica Sin Azúcar",
        "brand": "Tradición MX",
        "calories": 5,
        "protein": 0.0,
        "carbs": 1.0,
        "fats": 0.0,
        "serving_size": "1 vaso (350ml)",
        "serving_grams": 350,
        "category": "drinks",
        "country": "MX"
      },
      {
        "id": "mx-drin-2",
        "name": "Leche Lala 100 Sin Lactosa Proteína 54g",
        "brand": "Lala MX",
        "calories": 130,
        "protein": 13.5,
        "carbs": 6.0,
        "fats": 5.0,
        "serving_size": "250ml vaso",
        "serving_grams": 250,
        "category": "drinks",
        "country": "MX"
      },
      {
        "id": "mx-drin-3",
        "name": "Tehuacán Brillante Agua Mineral de Manantial",
        "brand": "Peñafiel MX",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "600ml botella",
        "serving_grams": 600,
        "category": "drinks",
        "country": "MX"
      },
      {
        "id": "mx-drin-4",
        "name": "Café de Olla Tradicional con Canela Sin Azúcar",
        "brand": "Café Mexicano",
        "calories": 10,
        "protein": 0.5,
        "carbs": 2.0,
        "fats": 0.0,
        "serving_size": "1 taza (240ml)",
        "serving_grams": 240,
        "category": "drinks",
        "country": "MX"
      },
      {
        "id": "mx-drin-5",
        "name": "Electrolit Suero Rehidratante Coco / Fresa",
        "brand": "Pisa Farmacéutica MX",
        "calories": 50,
        "protein": 0.0,
        "carbs": 12.0,
        "fats": 0.0,
        "serving_size": "625ml botella",
        "serving_grams": 625,
        "category": "drinks",
        "country": "MX"
      },
      {
        "id": "mx-drin-6",
        "name": "Sidral Mundet Refresco de Manzana Light Zero",
        "brand": "Coca-Cola MX",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "355ml lata",
        "serving_grams": 355,
        "category": "drinks",
        "country": "MX"
      }
    ]
  },
  "BR": {
    "protein": [
      {
        "id": "br-prot-1",
        "name": "Peito de Frango Sadia Grelhado sem Pele",
        "brand": "Sadia BR",
        "calories": 165,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.6,
        "serving_size": "100g grelhado",
        "serving_grams": 100,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-2",
        "name": "Picanha Bovina sem Gordura Grelhada",
        "brand": "Friboi BR",
        "calories": 210,
        "protein": 28.0,
        "carbs": 0.0,
        "fats": 10.5,
        "serving_size": "100g bife",
        "serving_grams": 100,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-3",
        "name": "Patinho Moído Extra Magro 100% Carne",
        "brand": "Seara BR",
        "calories": 155,
        "protein": 25.0,
        "carbs": 0.0,
        "fats": 5.5,
        "serving_size": "100g cozido",
        "serving_grams": 100,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-4",
        "name": "100% Whey Protein Concentrado Max Titanium",
        "brand": "Max Titanium BR",
        "calories": 125,
        "protein": 24.0,
        "carbs": 3.5,
        "fats": 1.8,
        "serving_size": "1 dosador (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-5",
        "name": "Filé de Tilápia Grelhado no Azeite",
        "brand": "Copacol BR",
        "calories": 128,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 2.5,
        "serving_size": "100g filé",
        "serving_grams": 100,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-6",
        "name": "Ovos Caipiras Grandes Mantiqueira (2 ovos)",
        "brand": "Mantiqueira BR",
        "calories": 142,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 ovos (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-7",
        "name": "Iogurte Natural Desnatado Nestlé 160g",
        "brand": "Nestlé BR",
        "calories": 70,
        "protein": 7.2,
        "carbs": 9.5,
        "fats": 0.5,
        "serving_size": "1 pote (160g)",
        "serving_grams": 160,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-8",
        "name": "Queijo Minas Frescal Light Tirolez",
        "brand": "Tirolez BR",
        "calories": 175,
        "protein": 17.5,
        "carbs": 2.5,
        "fats": 10.5,
        "serving_size": "100g fatia",
        "serving_grams": 100,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-9",
        "name": "Atum Sólido ao Natural em Água Coqueiro",
        "brand": "Coqueiro BR",
        "calories": 110,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 0.8,
        "serving_size": "1 lata (170g)",
        "serving_grams": 170,
        "category": "protein",
        "country": "BR"
      },
      {
        "id": "br-prot-10",
        "name": "Feijão Preto Carioca Cozido Tradicional",
        "brand": "Camil BR",
        "calories": 115,
        "protein": 7.8,
        "carbs": 20.0,
        "fats": 0.6,
        "serving_size": "1 concha (140g)",
        "serving_grams": 140,
        "category": "protein",
        "country": "BR"
      }
    ],
    "carbs": [
      {
        "id": "br-carb-1",
        "name": "Arroz Integral Tio João 100% Grãos Nobres",
        "brand": "Tio João BR",
        "calories": 160,
        "protein": 3.5,
        "carbs": 34.0,
        "fats": 1.2,
        "serving_size": "1 escumadeira (120g)",
        "serving_grams": 120,
        "category": "carbs",
        "country": "BR"
      },
      {
        "id": "br-carb-2",
        "name": "Mandioca Cozida na Água e Sal (Aipim)",
        "brand": "Hortifruti BR",
        "calories": 145,
        "protein": 1.4,
        "carbs": 35.0,
        "fats": 0.3,
        "serving_size": "100g cozida",
        "serving_grams": 100,
        "category": "carbs",
        "country": "BR"
      },
      {
        "id": "br-carb-3",
        "name": "Batata Doce Roxa Cozida no Vapor",
        "brand": "Hortifruti BR",
        "calories": 95,
        "protein": 1.6,
        "carbs": 22.0,
        "fats": 0.2,
        "serving_size": "100g cozida",
        "serving_grams": 100,
        "category": "carbs",
        "country": "BR"
      },
      {
        "id": "br-carb-4",
        "name": "Goma de Tapioca Hidratada Da Terrinha",
        "brand": "Da Terrinha BR",
        "calories": 135,
        "protein": 0.0,
        "carbs": 33.0,
        "fats": 0.0,
        "serving_size": "2 colheres sopa (50g)",
        "serving_grams": 50,
        "category": "carbs",
        "country": "BR"
      },
      {
        "id": "br-carb-5",
        "name": "Aveia em Flocos Finos Quaker Brasil",
        "brand": "Quaker BR",
        "calories": 145,
        "protein": 5.0,
        "carbs": 26.0,
        "fats": 2.5,
        "serving_size": "40g porção",
        "serving_grams": 40,
        "category": "carbs",
        "country": "BR"
      },
      {
        "id": "br-carb-6",
        "name": "Açaí Puro Polpa Congelada sem Xarope",
        "brand": "Frooty BR",
        "calories": 70,
        "protein": 1.5,
        "carbs": 6.0,
        "fats": 4.5,
        "serving_size": "100g polpa",
        "serving_grams": 100,
        "category": "carbs",
        "country": "BR"
      },
      {
        "id": "br-carb-7",
        "name": "Cuscuz Nordestino de Milho Cozido",
        "brand": "Flocão Sinhá BR",
        "calories": 150,
        "protein": 3.5,
        "carbs": 32.0,
        "fats": 1.0,
        "serving_size": "1 fatia média (100g)",
        "serving_grams": 100,
        "category": "carbs",
        "country": "BR"
      }
    ],
    "fats": [
      {
        "id": "br-fats-1",
        "name": "Castanha-do-Pará Crua Selecionada (Brazil Nuts)",
        "brand": "Nutty Bavarian BR",
        "calories": 195,
        "protein": 4.2,
        "carbs": 3.5,
        "fats": 19.5,
        "serving_size": "30g porção",
        "serving_grams": 30,
        "category": "fats",
        "country": "BR"
      },
      {
        "id": "br-fats-2",
        "name": "Azeite de Oliva Extra Virgem Gallo Clássico",
        "brand": "Gallo BR",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 colher sopa (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "BR"
      },
      {
        "id": "br-fats-3",
        "name": "Pasta de Amendoim Integral 100% Dr. Peanut",
        "brand": "Dr. Peanut BR",
        "calories": 180,
        "protein": 8.5,
        "carbs": 5.0,
        "fats": 15.0,
        "serving_size": "2 colheres (30g)",
        "serving_grams": 30,
        "category": "fats",
        "country": "BR"
      },
      {
        "id": "br-fats-4",
        "name": "Abacate Manteiga Brasileiro Maduro",
        "brand": "Hortifruti BR",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "100g porção",
        "serving_grams": 100,
        "category": "fats",
        "country": "BR"
      },
      {
        "id": "br-fats-5",
        "name": "Manteiga Extra de Primeira Qualidade Aviação",
        "brand": "Aviação BR",
        "calories": 105,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 11.5,
        "serving_size": "1 colher (15g)",
        "serving_grams": 15,
        "category": "fats",
        "country": "BR"
      },
      {
        "id": "br-fats-6",
        "name": "Castanha de Caju Torrada sem Sal",
        "brand": "Hortifruti BR",
        "calories": 170,
        "protein": 5.5,
        "carbs": 9.0,
        "fats": 13.5,
        "serving_size": "30g punhado",
        "serving_grams": 30,
        "category": "fats",
        "country": "BR"
      }
    ],
    "fastfood": [
      {
        "id": "br-fast-1",
        "name": "Prato Feito Fit Frango Grelhado, Arroz e Feijão",
        "brand": "Restaurante Por Quilo",
        "calories": 480,
        "protein": 44.0,
        "carbs": 56.0,
        "fats": 10.0,
        "serving_size": "1 prato (400g)",
        "serving_grams": 400,
        "category": "fastfood",
        "country": "BR"
      },
      {
        "id": "br-fast-2",
        "name": "Pão de Queijo Mineiro Tradicional (2 unidades)",
        "brand": "Forno de Minas BR",
        "calories": 190,
        "protein": 4.5,
        "carbs": 23.0,
        "fats": 9.0,
        "serving_size": "2 unidades (60g)",
        "serving_grams": 60,
        "category": "fastfood",
        "country": "BR"
      },
      {
        "id": "br-fast-3",
        "name": "Coxinha de Frango Assada sem Fritura",
        "brand": "Lanchonete BR",
        "calories": 220,
        "protein": 12.0,
        "carbs": 26.0,
        "fats": 7.5,
        "serving_size": "1 unidade (120g)",
        "serving_grams": 120,
        "category": "fastfood",
        "country": "BR"
      },
      {
        "id": "br-fast-4",
        "name": "Subway Brasil Frango Teriyaki Pão Integral 15cm",
        "brand": "Subway BR",
        "calories": 340,
        "protein": 25.0,
        "carbs": 48.0,
        "fats": 4.5,
        "serving_size": "15cm (230g)",
        "serving_grams": 230,
        "category": "fastfood",
        "country": "BR"
      },
      {
        "id": "br-fast-5",
        "name": "Giraffas Filé de Peito de Frango com Salada",
        "brand": "Giraffas BR",
        "calories": 320,
        "protein": 38.0,
        "carbs": 12.0,
        "fats": 12.0,
        "serving_size": "1 refeição",
        "serving_grams": 280,
        "category": "fastfood",
        "country": "BR"
      },
      {
        "id": "br-fast-6",
        "name": "Pastel de Carne Moída Assado no Forno",
        "brand": "Pastelaria BR",
        "calories": 260,
        "protein": 14.0,
        "carbs": 31.0,
        "fats": 9.0,
        "serving_size": "1 unidade (140g)",
        "serving_grams": 140,
        "category": "fastfood",
        "country": "BR"
      }
    ],
    "drinks": [
      {
        "id": "br-drin-1",
        "name": "Guaraná Antarctica Zero Açúcar",
        "brand": "Ambev BR",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "350ml lata",
        "serving_grams": 350,
        "category": "drinks",
        "country": "BR"
      },
      {
        "id": "br-drin-2",
        "name": "Água de Coco Do Bem 100% Pura e Natural",
        "brand": "Do Bem BR",
        "calories": 40,
        "protein": 0.0,
        "carbs": 10.0,
        "fats": 0.0,
        "serving_size": "200ml caixinha",
        "serving_grams": 200,
        "category": "drinks",
        "country": "BR"
      },
      {
        "id": "br-drin-3",
        "name": "Whey Pronto Bebida Láctea Piracanjuba 23g Proteína",
        "brand": "Piracanjuba BR",
        "calories": 170,
        "protein": 23.0,
        "carbs": 15.0,
        "fats": 2.0,
        "serving_size": "250ml garrafa",
        "serving_grams": 250,
        "category": "drinks",
        "country": "BR"
      },
      {
        "id": "br-drin-4",
        "name": "Café Pilão Tradicional Coado sem Açúcar",
        "brand": "Pilão BR",
        "calories": 4,
        "protein": 0.3,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 xícara (150ml)",
        "serving_grams": 150,
        "category": "drinks",
        "country": "BR"
      },
      {
        "id": "br-drin-5",
        "name": "Chá Matte Leão Natural Gelado sem Açúcar",
        "brand": "Leão Alimentos BR",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "300ml copo",
        "serving_grams": 300,
        "category": "drinks",
        "country": "BR"
      },
      {
        "id": "br-drin-6",
        "name": "Suco de Laranja Integral 100% Natural Prats",
        "brand": "Prats BR",
        "calories": 115,
        "protein": 1.8,
        "carbs": 26.0,
        "fats": 0.2,
        "serving_size": "250ml copo",
        "serving_grams": 250,
        "category": "drinks",
        "country": "BR"
      }
    ]
  }
};
