import { RegionalFoodMap } from './types';

export const ASIA_FOODS: RegionalFoodMap = {
  "IN": {
    "protein": [
      {
        "id": "in-prot-1",
        "name": "Fresh Cow Milk Paneer Malai Block",
        "brand": "Amul / Mother Dairy IN",
        "calories": 265,
        "protein": 18.5,
        "carbs": 3.5,
        "fats": 20.0,
        "serving_size": "100g cube",
        "serving_grams": 100,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-2",
        "name": "Amul High Protein Buttermilk (15g Protein)",
        "brand": "Amul IN",
        "calories": 85,
        "protein": 15.0,
        "carbs": 4.5,
        "fats": 0.5,
        "serving_size": "200ml pack",
        "serving_grams": 200,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-3",
        "name": "Amul High Protein Lassi Rose Flavour (15g)",
        "brand": "Amul IN",
        "calories": 115,
        "protein": 15.0,
        "carbs": 12.0,
        "fats": 0.5,
        "serving_size": "200ml tetra pack",
        "serving_grams": 200,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-4",
        "name": "MuscleBlaze Biozyme Performance Whey Chocolate",
        "brand": "MuscleBlaze IN",
        "calories": 130,
        "protein": 25.0,
        "carbs": 3.2,
        "fats": 1.8,
        "serving_size": "1 scoop (36g)",
        "serving_grams": 36,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-5",
        "name": "Nutrela Soya Chunks 52% Protein (Boiled)",
        "brand": "Patanjali Nutrela IN",
        "calories": 120,
        "protein": 18.0,
        "carbs": 10.0,
        "fats": 0.5,
        "serving_size": "100g boiled",
        "serving_grams": 100,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-6",
        "name": "Tandoori Chicken Breast Tikka (Skinless)",
        "brand": "Tandoori Grill IN",
        "calories": 175,
        "protein": 32.0,
        "carbs": 2.0,
        "fats": 4.5,
        "serving_size": "100g tikka",
        "serving_grams": 100,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-7",
        "name": "Boiled Desi Farm Eggs (2 eggs)",
        "brand": "Fresh Farm Eggs IN",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-8",
        "name": "Yellow Moong Dal Cooked with Jeera Tadka",
        "brand": "Home Kitchen IN",
        "calories": 115,
        "protein": 8.5,
        "carbs": 18.0,
        "fats": 1.5,
        "serving_size": "1 katori (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-9",
        "name": "Toor Dal Arhar Dal Cooked with Tomatoes",
        "brand": "Home Kitchen IN",
        "calories": 120,
        "protein": 8.0,
        "carbs": 19.0,
        "fats": 1.8,
        "serving_size": "1 katori (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-10",
        "name": "Epigamia Natural Greek Yogurt No Added Sugar",
        "brand": "Epigamia IN",
        "calories": 80,
        "protein": 10.0,
        "carbs": 6.0,
        "fats": 2.0,
        "serving_size": "1 cup (120g)",
        "serving_grams": 120,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-11",
        "name": "Chana Masala Boiled White Chickpeas",
        "brand": "Home Kitchen IN",
        "calories": 140,
        "protein": 8.5,
        "carbs": 22.0,
        "fats": 2.5,
        "serving_size": "1 katori (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-12",
        "name": "Surmai Kingfish Curry / Tawa Fry",
        "brand": "Coastal Kitchen IN",
        "calories": 145,
        "protein": 23.0,
        "carbs": 1.0,
        "fats": 5.5,
        "serving_size": "100g slice",
        "serving_grams": 100,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-13",
        "name": "Paneer Bhurji Spiced Scrambled Cottage Cheese",
        "brand": "Home Kitchen IN",
        "calories": 220,
        "protein": 16.0,
        "carbs": 5.0,
        "fats": 15.0,
        "serving_size": "150g serve",
        "serving_grams": 150,
        "category": "protein",
        "country": "IN"
      },
      {
        "id": "in-prot-14",
        "name": "Egg Curry with Onion Tomato Gravy (2 eggs)",
        "brand": "Home Kitchen IN",
        "calories": 210,
        "protein": 14.0,
        "carbs": 8.0,
        "fats": 13.0,
        "serving_size": "1 portion (200g)",
        "serving_grams": 200,
        "category": "protein",
        "country": "IN"
      }
    ],
    "carbs": [
      {
        "id": "in-carb-1",
        "name": "India Gate Classic Basmati Rice (Cooked)",
        "brand": "India Gate IN",
        "calories": 170,
        "protein": 3.5,
        "carbs": 37.0,
        "fats": 0.5,
        "serving_size": "1 katori (130g)",
        "serving_grams": 130,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-2",
        "name": "Whole Wheat Phulka / Roti (No Ghee, 2 rotis)",
        "brand": "Aashirvaad Atta IN",
        "calories": 140,
        "protein": 4.5,
        "carbs": 28.0,
        "fats": 0.8,
        "serving_size": "2 rotis (60g)",
        "serving_grams": 60,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-3",
        "name": "Steamed Rice Idli (2 pieces) with Sambhar",
        "brand": "Udupi Kitchen IN",
        "calories": 130,
        "protein": 4.0,
        "carbs": 27.0,
        "fats": 0.5,
        "serving_size": "2 idlis (100g)",
        "serving_grams": 100,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-4",
        "name": "Poha Flattened Rice with Peanuts & Mustard",
        "brand": "Home Kitchen IN",
        "calories": 180,
        "protein": 4.2,
        "carbs": 33.0,
        "fats": 3.8,
        "serving_size": "1 bowl (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-5",
        "name": "Boiled Kala Chana (Brown Chickpeas Chat)",
        "brand": "Home Kitchen IN",
        "calories": 130,
        "protein": 7.8,
        "carbs": 21.0,
        "fats": 1.5,
        "serving_size": "1 katori (120g)",
        "serving_grams": 120,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-6",
        "name": "Sweet Potato Shakarkandi Roasted Chaat",
        "brand": "Street Style IN",
        "calories": 110,
        "protein": 2.0,
        "carbs": 25.0,
        "fats": 0.2,
        "serving_size": "1 bowl (120g)",
        "serving_grams": 120,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-7",
        "name": "Jowar Bhakri Sorghum Flatbread (1 roti)",
        "brand": "Home Kitchen IN",
        "calories": 115,
        "protein": 3.8,
        "carbs": 24.0,
        "fats": 0.8,
        "serving_size": "1 bhakri (50g)",
        "serving_grams": 50,
        "category": "carbs",
        "country": "IN"
      },
      {
        "id": "in-carb-8",
        "name": "Quaker Oats Masala Flavoured Porridge",
        "brand": "Quaker IN",
        "calories": 145,
        "protein": 4.8,
        "carbs": 25.0,
        "fats": 2.8,
        "serving_size": "1 sachet (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "IN"
      }
    ],
    "fats": [
      {
        "id": "in-fats-1",
        "name": "Amul Pure Cow Desi Ghee",
        "brand": "Amul IN",
        "calories": 112,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 12.5,
        "serving_size": "1 tbsp (14g)",
        "serving_grams": 14,
        "category": "fats",
        "country": "IN"
      },
      {
        "id": "in-fats-2",
        "name": "Patanjali Pure Desi Cow Ghee",
        "brand": "Patanjali IN",
        "calories": 112,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 12.5,
        "serving_size": "1 tbsp (14g)",
        "serving_grams": 14,
        "category": "fats",
        "country": "IN"
      },
      {
        "id": "in-fats-3",
        "name": "Fortune Kachi Ghani Pure Mustard Oil",
        "brand": "Fortune Adani IN",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "IN"
      },
      {
        "id": "in-fats-4",
        "name": "Rostaa California Raw Whole Almonds",
        "brand": "Rostaa IN",
        "calories": 165,
        "protein": 6.0,
        "carbs": 6.0,
        "fats": 14.0,
        "serving_size": "28g handful",
        "serving_grams": 28,
        "category": "fats",
        "country": "IN"
      },
      {
        "id": "in-fats-5",
        "name": "Fresh Raw Coconut Flesh Grated (Nariyal)",
        "brand": "Fresh Produce IN",
        "calories": 140,
        "protein": 1.3,
        "carbs": 6.0,
        "fats": 13.5,
        "serving_size": "40g portion",
        "serving_grams": 40,
        "category": "fats",
        "country": "IN"
      },
      {
        "id": "in-fats-6",
        "name": "Haldiram's Roasted & Salted Cashews",
        "brand": "Haldiram's IN",
        "calories": 170,
        "protein": 5.5,
        "carbs": 9.0,
        "fats": 13.5,
        "serving_size": "30g portion",
        "serving_grams": 30,
        "category": "fats",
        "country": "IN"
      }
    ],
    "fastfood": [
      {
        "id": "in-fast-1",
        "name": "Chicken Dum Biryani with Spiced Raita",
        "brand": "Biryani Blues / Behrouz",
        "calories": 560,
        "protein": 38.0,
        "carbs": 64.0,
        "fats": 16.0,
        "serving_size": "1 portion (420g)",
        "serving_grams": 420,
        "category": "fastfood",
        "country": "IN"
      },
      {
        "id": "in-fast-2",
        "name": "Subway India Paneer Tikka Sub Multigrain",
        "brand": "Subway India",
        "calories": 390,
        "protein": 21.0,
        "carbs": 48.0,
        "fats": 13.0,
        "serving_size": "6-inch (240g)",
        "serving_grams": 240,
        "category": "fastfood",
        "country": "IN"
      },
      {
        "id": "in-fast-3",
        "name": "Haldiram's Grilled Paneer Tikka Platter",
        "brand": "Haldiram's IN",
        "calories": 320,
        "protein": 22.0,
        "carbs": 10.0,
        "fats": 21.0,
        "serving_size": "1 plate (220g)",
        "serving_grams": 220,
        "category": "fastfood",
        "country": "IN"
      },
      {
        "id": "in-fast-4",
        "name": "KFC India Smoky Grilled Chicken Piece",
        "brand": "KFC India",
        "calories": 190,
        "protein": 25.0,
        "carbs": 3.0,
        "fats": 9.0,
        "serving_size": "1 piece (110g)",
        "serving_grams": 110,
        "category": "fastfood",
        "country": "IN"
      },
      {
        "id": "in-fast-5",
        "name": "Steamed Chicken Momos with Spicy Chutney (6 pcs)",
        "brand": "Wow! Momo IN",
        "calories": 240,
        "protein": 18.0,
        "carbs": 32.0,
        "fats": 4.5,
        "serving_size": "6 pcs (150g)",
        "serving_grams": 150,
        "category": "fastfood",
        "country": "IN"
      },
      {
        "id": "in-fast-6",
        "name": "McDonald's India McAloo Tikki Burger",
        "brand": "McDonald's India",
        "calories": 335,
        "protein": 7.5,
        "carbs": 52.0,
        "fats": 11.0,
        "serving_size": "1 burger (145g)",
        "serving_grams": 145,
        "category": "fastfood",
        "country": "IN"
      }
    ],
    "drinks": [
      {
        "id": "in-drin-1",
        "name": "Fresh Tender Coconut Water (Nariyal Pani)",
        "brand": "Fresh Coconut IN",
        "calories": 45,
        "protein": 1.0,
        "carbs": 10.5,
        "fats": 0.2,
        "serving_size": "1 whole coconut (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "IN"
      },
      {
        "id": "in-drin-2",
        "name": "Amul Kool Kesar Badam Flavoured Milk",
        "brand": "Amul IN",
        "calories": 155,
        "protein": 6.5,
        "carbs": 23.0,
        "fats": 4.0,
        "serving_size": "180ml can",
        "serving_grams": 180,
        "category": "drinks",
        "country": "IN"
      },
      {
        "id": "in-drin-3",
        "name": "Fresh Mint Masala Chaas Spiced Buttermilk",
        "brand": "Mother Dairy IN",
        "calories": 55,
        "protein": 3.5,
        "carbs": 5.0,
        "fats": 2.0,
        "serving_size": "200ml glass",
        "serving_grams": 200,
        "category": "drinks",
        "country": "IN"
      },
      {
        "id": "in-drin-4",
        "name": "Raw Pressery Valencia Orange Cold Pressed",
        "brand": "Raw Pressery IN",
        "calories": 110,
        "protein": 1.8,
        "carbs": 25.0,
        "fats": 0.0,
        "serving_size": "250ml bottle",
        "serving_grams": 250,
        "category": "drinks",
        "country": "IN"
      },
      {
        "id": "in-drin-5",
        "name": "Traditional Desi Masala Chai (No Added Sugar)",
        "brand": "Chai Point IN",
        "calories": 50,
        "protein": 2.8,
        "carbs": 4.5,
        "fats": 2.2,
        "serving_size": "1 cup (150ml)",
        "serving_grams": 150,
        "category": "drinks",
        "country": "IN"
      },
      {
        "id": "in-drin-6",
        "name": "Paper Boat Aam Panna Traditional Drink",
        "brand": "Paper Boat IN",
        "calories": 85,
        "protein": 0.2,
        "carbs": 21.0,
        "fats": 0.0,
        "serving_size": "200ml pouch",
        "serving_grams": 200,
        "category": "drinks",
        "country": "IN"
      }
    ]
  },
  "SG": {
    "protein": [
      {
        "id": "sg-prot-1",
        "name": "CP Marinated Skinless Chicken Breast",
        "brand": "CP Foods SG",
        "calories": 150,
        "protein": 29.0,
        "carbs": 1.5,
        "fats": 3.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "SG"
      },
      {
        "id": "sg-prot-2",
        "name": "Fortune Japanese Silken Tofu Smooth",
        "brand": "Fortune Tofu SG",
        "calories": 75,
        "protein": 8.5,
        "carbs": 2.0,
        "fats": 3.5,
        "serving_size": "150g block",
        "serving_grams": 150,
        "category": "protein",
        "country": "SG"
      },
      {
        "id": "sg-prot-3",
        "name": "Fresh Barramundi Seabass Fillet Steamed",
        "brand": "Kühlbarra SG",
        "calories": 115,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 2.5,
        "serving_size": "100g fillet",
        "serving_grams": 100,
        "category": "protein",
        "country": "SG"
      },
      {
        "id": "sg-prot-4",
        "name": "Dodo Fish Balls Boiled (6 pieces)",
        "brand": "Dodo SG",
        "calories": 95,
        "protein": 13.0,
        "carbs": 7.5,
        "fats": 1.5,
        "serving_size": "6 balls (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "SG"
      },
      {
        "id": "sg-prot-5",
        "name": "FairPrice Fresh Eggs Pasar (2 eggs)",
        "brand": "FairPrice SG",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "SG"
      },
      {
        "id": "sg-prot-6",
        "name": "Ayam Brand Tuna in Water Light Meat",
        "brand": "Ayam Brand SG",
        "calories": 105,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "1 can (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "SG"
      },
      {
        "id": "sg-prot-7",
        "name": "Myprotein Impact Whey Isolate SG",
        "brand": "Myprotein SG",
        "calories": 95,
        "protein": 22.0,
        "carbs": 0.6,
        "fats": 0.3,
        "serving_size": "1 scoop (25g)",
        "serving_grams": 25,
        "category": "protein",
        "country": "SG"
      }
    ],
    "carbs": [
      {
        "id": "sg-carb-1",
        "name": "Royal Umbrella Thai Hom Mali Jasmine Rice",
        "brand": "Royal Umbrella SG",
        "calories": 175,
        "protein": 3.2,
        "carbs": 38.0,
        "fats": 0.4,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "SG"
      },
      {
        "id": "sg-carb-2",
        "name": "Koka Purple Wheat Noodles Steamed",
        "brand": "Koka SG",
        "calories": 160,
        "protein": 5.0,
        "carbs": 31.0,
        "fats": 1.5,
        "serving_size": "1 serving (60g)",
        "serving_grams": 60,
        "category": "carbs",
        "country": "SG"
      },
      {
        "id": "sg-carb-3",
        "name": "Sunshine Wholemeal Extra Fine Bread",
        "brand": "Sunshine SG",
        "calories": 155,
        "protein": 7.2,
        "carbs": 28.0,
        "fats": 1.8,
        "serving_size": "2 slices (70g)",
        "serving_grams": 70,
        "category": "carbs",
        "country": "SG"
      },
      {
        "id": "sg-carb-4",
        "name": "FairPrice Rolled Oats Whole Grain",
        "brand": "FairPrice SG",
        "calories": 145,
        "protein": 5.0,
        "carbs": 26.0,
        "fats": 2.5,
        "serving_size": "40g serve",
        "serving_grams": 40,
        "category": "carbs",
        "country": "SG"
      },
      {
        "id": "sg-carb-5",
        "name": "Steamed Sweet Purple Yam / Taro",
        "brand": "Wet Market SG",
        "calories": 95,
        "protein": 1.5,
        "carbs": 22.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "SG"
      }
    ],
    "fats": [
      {
        "id": "sg-fats-1",
        "name": "Chee Seng 100% Pure White Sesame Oil",
        "brand": "Chee Seng SG",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "SG"
      },
      {
        "id": "sg-fats-2",
        "name": "Tong Garden Natural Whole Roasted Almonds",
        "brand": "Tong Garden SG",
        "calories": 170,
        "protein": 6.0,
        "carbs": 6.0,
        "fats": 14.5,
        "serving_size": "30g pack",
        "serving_grams": 30,
        "category": "fats",
        "country": "SG"
      },
      {
        "id": "sg-fats-3",
        "name": "Fresh Ripe Hass Avocado",
        "brand": "Cold Storage SG",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "SG"
      },
      {
        "id": "sg-fats-4",
        "name": "Knife Brand Pure Cooking Oil Blend",
        "brand": "Lam Soon SG",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "SG"
      }
    ],
    "fastfood": [
      {
        "id": "sg-fast-1",
        "name": "Hainanese Steamed Chicken Breast Rice",
        "brand": "Hawker Centre SG",
        "calories": 520,
        "protein": 38.0,
        "carbs": 62.0,
        "fats": 12.0,
        "serving_size": "1 plate (380g)",
        "serving_grams": 380,
        "category": "fastfood",
        "country": "SG"
      },
      {
        "id": "sg-fast-2",
        "name": "Ban Mian Soup with Minced Pork & Spinach",
        "brand": "Hawker Centre SG",
        "calories": 380,
        "protein": 24.0,
        "carbs": 48.0,
        "fats": 9.5,
        "serving_size": "1 bowl (450g)",
        "serving_grams": 450,
        "category": "fastfood",
        "country": "SG"
      },
      {
        "id": "sg-fast-3",
        "name": "McDonald's Singapore McSpicy Chicken Burger",
        "brand": "McDonald's SG",
        "calories": 525,
        "protein": 24.0,
        "carbs": 48.0,
        "fats": 26.0,
        "serving_size": "1 burger (210g)",
        "serving_grams": 210,
        "category": "fastfood",
        "country": "SG"
      },
      {
        "id": "sg-fast-4",
        "name": "Ya Kun Kaya Toast with Butter (2 slices)",
        "brand": "Ya Kun SG",
        "calories": 260,
        "protein": 5.0,
        "carbs": 36.0,
        "fats": 10.5,
        "serving_size": "1 serving (80g)",
        "serving_grams": 80,
        "category": "fastfood",
        "country": "SG"
      },
      {
        "id": "sg-fast-5",
        "name": "Din Tai Fung Steamed Pork Xiaolongbao (6 pcs)",
        "brand": "Din Tai Fung SG",
        "calories": 310,
        "protein": 16.0,
        "carbs": 28.0,
        "fats": 14.0,
        "serving_size": "6 pcs (150g)",
        "serving_grams": 150,
        "category": "fastfood",
        "country": "SG"
      }
    ],
    "drinks": [
      {
        "id": "sg-drin-1",
        "name": "Pokka Japanese Jasmine Green Tea No Sugar",
        "brand": "Pokka SG",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "SG"
      },
      {
        "id": "sg-drin-2",
        "name": "Yeo's 100% Soy Bean Milk Less Sugar",
        "brand": "Yeo's SG",
        "calories": 95,
        "protein": 6.5,
        "carbs": 12.0,
        "fats": 2.2,
        "serving_size": "250ml packet",
        "serving_grams": 250,
        "category": "drinks",
        "country": "SG"
      },
      {
        "id": "sg-drin-3",
        "name": "Kopi-O Kosong Traditional Black Coffee",
        "brand": "Hawker Kopitiam",
        "calories": 5,
        "protein": 0.3,
        "carbs": 0.5,
        "fats": 0.0,
        "serving_size": "1 cup (200ml)",
        "serving_grams": 200,
        "category": "drinks",
        "country": "SG"
      },
      {
        "id": "sg-drin-4",
        "name": "Fresh Young Thai Coconut Water",
        "brand": "Fruit Stall SG",
        "calories": 50,
        "protein": 1.0,
        "carbs": 11.5,
        "fats": 0.2,
        "serving_size": "1 coconut (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "SG"
      }
    ]
  },
  "JP": {
    "protein": [
      {
        "id": "jp-prot-1",
        "name": "7-Eleven Salad Chicken Herb (サラダチキン)",
        "brand": "7-Eleven Japan",
        "calories": 125,
        "protein": 27.5,
        "carbs": 0.3,
        "fats": 1.2,
        "serving_size": "1 pack (115g)",
        "serving_grams": 115,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-2",
        "name": "Meiji Savas Whey Protein Cocoa 100",
        "brand": "Meiji Savas JP",
        "calories": 115,
        "protein": 20.0,
        "carbs": 3.2,
        "fats": 1.6,
        "serving_size": "1 scoop (28g)",
        "serving_grams": 28,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-3",
        "name": "Fresh Sashimi Atlantic Salmon Fillet (生サーモン)",
        "brand": "Sushiro / Supermarket",
        "calories": 195,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 11.5,
        "serving_size": "100g sashimi",
        "serving_grams": 100,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-4",
        "name": "Fresh Sashimi Hon Maguro Tuna (本マグロ赤身)",
        "brand": "Tsukiji Market JP",
        "calories": 125,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 1.4,
        "serving_size": "100g sashimi",
        "serving_grams": 100,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-5",
        "name": "Momen Firm Soybean Tofu (木綿豆腐)",
        "brand": "House Foods JP",
        "calories": 110,
        "protein": 10.5,
        "carbs": 2.5,
        "fats": 6.0,
        "serving_size": "1/2 block (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-6",
        "name": "Natto Fermented Soybeans with Dashi (納豆)",
        "brand": "Mizkan JP",
        "calories": 90,
        "protein": 8.5,
        "carbs": 5.5,
        "fats": 4.5,
        "serving_size": "1 pack (45g)",
        "serving_grams": 45,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-7",
        "name": "Boiled Green Edamame Soybeans in Pod",
        "brand": "Produce JP",
        "calories": 110,
        "protein": 9.5,
        "carbs": 8.0,
        "fats": 4.0,
        "serving_size": "100g in pods",
        "serving_grams": 100,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-8",
        "name": "Morinaga Oikos High Protein Greek Yogurt",
        "brand": "Morinaga JP",
        "calories": 92,
        "protein": 10.0,
        "carbs": 12.0,
        "fats": 0.0,
        "serving_size": "1 cup (113g)",
        "serving_grams": 113,
        "category": "protein",
        "country": "JP"
      },
      {
        "id": "jp-prot-9",
        "name": "Yakitori Grilled Chicken Breast Skewers Shio (2 pcs)",
        "brand": "Torikizoku JP",
        "calories": 140,
        "protein": 25.0,
        "carbs": 0.5,
        "fats": 4.0,
        "serving_size": "2 skewers (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "JP"
      }
    ],
    "carbs": [
      {
        "id": "jp-carb-1",
        "name": "Japanese Koshihikari Steamed White Rice (コシヒカリ)",
        "brand": "Niigata Rice JP",
        "calories": 168,
        "protein": 2.8,
        "carbs": 37.0,
        "fats": 0.3,
        "serving_size": "1 bowl (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "JP"
      },
      {
        "id": "jp-carb-2",
        "name": "Japanese Brown Rice Genmai (玄米ごはん)",
        "brand": "7-Eleven JP",
        "calories": 165,
        "protein": 3.5,
        "carbs": 35.0,
        "fats": 1.0,
        "serving_size": "1 pack (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "JP"
      },
      {
        "id": "jp-carb-3",
        "name": "Nissin 100% Buckwheat Soba Noodles Boiled",
        "brand": "Nissin JP",
        "calories": 150,
        "protein": 6.5,
        "carbs": 29.0,
        "fats": 1.0,
        "serving_size": "1 bowl (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "JP"
      },
      {
        "id": "jp-carb-4",
        "name": "7-Eleven Salmon Rice Ball Onigiri (鮭おにぎり)",
        "brand": "7-Eleven JP",
        "calories": 175,
        "protein": 4.8,
        "carbs": 36.0,
        "fats": 1.2,
        "serving_size": "1 onigiri (110g)",
        "serving_grams": 110,
        "category": "carbs",
        "country": "JP"
      },
      {
        "id": "jp-carb-5",
        "name": "Yaki-Imo Roasted Japanese Sweet Potato (焼き芋)",
        "brand": "Street Stall JP",
        "calories": 140,
        "protein": 2.0,
        "carbs": 32.0,
        "fats": 0.3,
        "serving_size": "100g roasted",
        "serving_grams": 100,
        "category": "carbs",
        "country": "JP"
      },
      {
        "id": "jp-carb-6",
        "name": "Lawson Natural Bran Bread Roll (ブランパン)",
        "brand": "Lawson JP",
        "calories": 65,
        "protein": 5.7,
        "carbs": 2.2,
        "fats": 2.7,
        "serving_size": "1 piece (30g)",
        "serving_grams": 30,
        "category": "carbs",
        "country": "JP"
      }
    ],
    "fats": [
      {
        "id": "jp-fats-1",
        "name": "Kadoya 100% Pure Roasted Sesame Oil (ごま油)",
        "brand": "Kadoya JP",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "JP"
      },
      {
        "id": "jp-fats-2",
        "name": "Kewpie Half Mayo (50% Calorie Cut)",
        "brand": "Kewpie JP",
        "calories": 49,
        "protein": 0.4,
        "carbs": 0.5,
        "fats": 5.1,
        "serving_size": "1 tbsp (15g)",
        "serving_grams": 15,
        "category": "fats",
        "country": "JP"
      },
      {
        "id": "jp-fats-3",
        "name": "Toasted White Sesame Seeds (白ごま)",
        "brand": "Kuki JP",
        "calories": 175,
        "protein": 5.5,
        "carbs": 3.5,
        "fats": 16.0,
        "serving_size": "30g portion",
        "serving_grams": 30,
        "category": "fats",
        "country": "JP"
      },
      {
        "id": "jp-fats-4",
        "name": "Fresh Hass Avocado",
        "brand": "AEON Produce JP",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "JP"
      }
    ],
    "fastfood": [
      {
        "id": "jp-fast-1",
        "name": "Yoshinoya Gyudon Beef Bowl Regular (牛丼並盛)",
        "brand": "Yoshinoya JP",
        "calories": 635,
        "protein": 20.0,
        "carbs": 88.0,
        "fats": 23.0,
        "serving_size": "1 bowl (330g)",
        "serving_grams": 330,
        "category": "fastfood",
        "country": "JP"
      },
      {
        "id": "jp-fast-2",
        "name": "Sushiro Salmon & Maguro Nigiri Set (4 pcs)",
        "brand": "Sushiro JP",
        "calories": 240,
        "protein": 14.0,
        "carbs": 36.0,
        "fats": 4.5,
        "serving_size": "4 pieces (140g)",
        "serving_grams": 140,
        "category": "fastfood",
        "country": "JP"
      },
      {
        "id": "jp-fast-3",
        "name": "Matsuya Grilled Pork with Ginger Bowl (豚生姜焼き)",
        "brand": "Matsuya JP",
        "calories": 580,
        "protein": 28.0,
        "carbs": 72.0,
        "fats": 18.0,
        "serving_size": "1 bowl (350g)",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "JP"
      },
      {
        "id": "jp-fast-4",
        "name": "Mos Burger Teriyaki Chicken Burger",
        "brand": "Mos Burger JP",
        "calories": 300,
        "protein": 17.5,
        "carbs": 31.0,
        "fats": 12.0,
        "serving_size": "1 burger (155g)",
        "serving_grams": 155,
        "category": "fastfood",
        "country": "JP"
      },
      {
        "id": "jp-fast-5",
        "name": "FamilyMart Famichiki Boneless Fried Chicken",
        "brand": "FamilyMart JP",
        "calories": 252,
        "protein": 13.5,
        "carbs": 14.0,
        "fats": 16.0,
        "serving_size": "1 piece (90g)",
        "serving_grams": 90,
        "category": "fastfood",
        "country": "JP"
      }
    ],
    "drinks": [
      {
        "id": "jp-drin-1",
        "name": "Ito En Oi Ocha Unsweetened Green Tea (お〜いお茶)",
        "brand": "Ito En JP",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "JP"
      },
      {
        "id": "jp-drin-2",
        "name": "Savas Milk Protein Fat-Free Drink 20g Cocoa",
        "brand": "Meiji JP",
        "calories": 102,
        "protein": 20.0,
        "carbs": 5.5,
        "fats": 0.0,
        "serving_size": "430ml bottle",
        "serving_grams": 430,
        "category": "drinks",
        "country": "JP"
      },
      {
        "id": "jp-drin-3",
        "name": "Suntory Tokucha Body Fat Green Tea (特茶)",
        "brand": "Suntory JP",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "JP"
      },
      {
        "id": "jp-drin-4",
        "name": "Pocari Sweat Ion Supply Drink Low Calorie",
        "brand": "Otsuka JP",
        "calories": 55,
        "protein": 0.0,
        "carbs": 13.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "JP"
      },
      {
        "id": "jp-drin-5",
        "name": "Asahi Super Dry 0.00 Non-Alcoholic Beer",
        "brand": "Asahi Breweries JP",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "350ml can",
        "serving_grams": 350,
        "category": "drinks",
        "country": "JP"
      }
    ]
  },
  "AE": {
    "protein": [
      {
        "id": "ae-prot-1",
        "name": "Grilled Shish Tawook Chicken Breast Skewers",
        "brand": "Shamiat Grill AE",
        "calories": 185,
        "protein": 32.0,
        "carbs": 1.0,
        "fats": 5.0,
        "serving_size": "150g serve",
        "serving_grams": 150,
        "category": "protein",
        "country": "AE"
      },
      {
        "id": "ae-prot-2",
        "name": "Almarai Fresh Laban High Protein Up Drink",
        "brand": "Almarai AE",
        "calories": 140,
        "protein": 18.0,
        "carbs": 10.0,
        "fats": 1.5,
        "serving_size": "330ml bottle",
        "serving_grams": 330,
        "category": "protein",
        "country": "AE"
      },
      {
        "id": "ae-prot-3",
        "name": "Fresh Hamour White Fish Fillet Grilled",
        "brand": "Dubai Fish Market",
        "calories": 110,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 2.0,
        "serving_size": "100g fillet",
        "serving_grams": 100,
        "category": "protein",
        "country": "AE"
      },
      {
        "id": "ae-prot-4",
        "name": "Al Rawdah Fresh Skinless Chicken Breast",
        "brand": "Al Rawdah AE",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "AE"
      },
      {
        "id": "ae-prot-5",
        "name": "Foul Mudammas Fava Beans Cooked with Cumin",
        "brand": "Americana AE",
        "calories": 110,
        "protein": 8.5,
        "carbs": 17.5,
        "fats": 0.8,
        "serving_size": "150g bowl",
        "serving_grams": 150,
        "category": "protein",
        "country": "AE"
      },
      {
        "id": "ae-prot-6",
        "name": "Nada High Protein Milk 27g Protein Vanilla",
        "brand": "Nada Dairy AE",
        "calories": 165,
        "protein": 27.0,
        "carbs": 12.0,
        "fats": 1.0,
        "serving_size": "320ml bottle",
        "serving_grams": 320,
        "category": "protein",
        "country": "AE"
      },
      {
        "id": "ae-prot-7",
        "name": "Grilled Halloumi Cheese Light Slices",
        "brand": "Almarai AE",
        "calories": 190,
        "protein": 16.0,
        "carbs": 2.0,
        "fats": 13.0,
        "serving_size": "80g slice",
        "serving_grams": 80,
        "category": "protein",
        "country": "AE"
      }
    ],
    "carbs": [
      {
        "id": "ae-carb-1",
        "name": "Whole Wheat Arabic Khubz Flatbread (1 loaf)",
        "brand": "Hot Bread Kitchen AE",
        "calories": 160,
        "protein": 6.0,
        "carbs": 34.0,
        "fats": 1.0,
        "serving_size": "1 loaf (65g)",
        "serving_grams": 65,
        "category": "carbs",
        "country": "AE"
      },
      {
        "id": "ae-carb-2",
        "name": "Mehran Super Kernel Basmati Rice Steamed",
        "brand": "Mehran AE",
        "calories": 170,
        "protein": 3.5,
        "carbs": 37.0,
        "fats": 0.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AE"
      },
      {
        "id": "ae-carb-3",
        "name": "Freekeh Ancient Smoked Green Wheat Cooked",
        "brand": "Levant Harvest AE",
        "calories": 145,
        "protein": 6.0,
        "carbs": 28.0,
        "fats": 1.2,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AE"
      },
      {
        "id": "ae-carb-4",
        "name": "Organic Medjool Premium Dates (2 dates)",
        "brand": "Bateel AE",
        "calories": 135,
        "protein": 0.8,
        "carbs": 36.0,
        "fats": 0.2,
        "serving_size": "2 dates (48g)",
        "serving_grams": 48,
        "category": "carbs",
        "country": "AE"
      },
      {
        "id": "ae-carb-5",
        "name": "Hummus Pure Chickpea Dip with Tahini",
        "brand": "Chtaura Park AE",
        "calories": 165,
        "protein": 5.5,
        "carbs": 14.0,
        "fats": 10.5,
        "serving_size": "100g dip",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AE"
      }
    ],
    "fats": [
      {
        "id": "ae-fats-1",
        "name": "Al Wazir Extra Virgin First Cold Pressed Olive Oil",
        "brand": "Al Wazir AE",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "AE"
      },
      {
        "id": "ae-fats-2",
        "name": "Alkanater 100% Pure Ground Sesame Tahina",
        "brand": "Alkanater AE",
        "calories": 180,
        "protein": 5.0,
        "carbs": 3.0,
        "fats": 17.0,
        "serving_size": "2 tbsp (30g)",
        "serving_grams": 30,
        "category": "fats",
        "country": "AE"
      },
      {
        "id": "ae-fats-3",
        "name": "Al Rifai Raw California Walnuts & Pistachios",
        "brand": "Al Rifai AE",
        "calories": 195,
        "protein": 5.5,
        "carbs": 6.0,
        "fats": 17.5,
        "serving_size": "30g pack",
        "serving_grams": 30,
        "category": "fats",
        "country": "AE"
      },
      {
        "id": "ae-fats-4",
        "name": "Fresh Hass Avocado",
        "brand": "Lulu Hypermarket AE",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "AE"
      }
    ],
    "fastfood": [
      {
        "id": "ae-fast-1",
        "name": "Chicken Shawarma Plate with Pickles & Hummus",
        "brand": "Automatic Restaurant AE",
        "calories": 490,
        "protein": 42.0,
        "carbs": 36.0,
        "fats": 18.0,
        "serving_size": "1 plate (350g)",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "AE"
      },
      {
        "id": "ae-fast-2",
        "name": "Al Baik Famous Crispy Chicken Fillet (4 pcs)",
        "brand": "Al Baik UAE",
        "calories": 480,
        "protein": 34.0,
        "carbs": 32.0,
        "fats": 24.0,
        "serving_size": "4 pcs (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "AE"
      },
      {
        "id": "ae-fast-3",
        "name": "Operation Falafel Stuffed Falafel Platter",
        "brand": "Operation Falafel AE",
        "calories": 360,
        "protein": 12.0,
        "carbs": 44.0,
        "fats": 16.0,
        "serving_size": "1 platter (220g)",
        "serving_grams": 220,
        "category": "fastfood",
        "country": "AE"
      },
      {
        "id": "ae-fast-4",
        "name": "Zaatar w Zeit Famous Grilled Chicken Wrap",
        "brand": "Zaatar w Zeit AE",
        "calories": 460,
        "protein": 34.0,
        "carbs": 46.0,
        "fats": 14.0,
        "serving_size": "1 wrap (260g)",
        "serving_grams": 260,
        "category": "fastfood",
        "country": "AE"
      }
    ],
    "drinks": [
      {
        "id": "ae-drin-1",
        "name": "Fresh Mint Lemonade No Sugar Added",
        "brand": "Levant Drinks AE",
        "calories": 40,
        "protein": 0.5,
        "carbs": 9.0,
        "fats": 0.0,
        "serving_size": "300ml glass",
        "serving_grams": 300,
        "category": "drinks",
        "country": "AE"
      },
      {
        "id": "ae-drin-2",
        "name": "Almarai Fresh 100% Orange Juice with Pulp",
        "brand": "Almarai AE",
        "calories": 110,
        "protein": 1.8,
        "carbs": 25.0,
        "fats": 0.0,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "AE"
      },
      {
        "id": "ae-drin-3",
        "name": "Traditional Arabic Qahwa Spiced Cardamom Coffee",
        "brand": "Qahwa AE",
        "calories": 5,
        "protein": 0.2,
        "carbs": 0.5,
        "fats": 0.0,
        "serving_size": "1 finjan (60ml)",
        "serving_grams": 60,
        "category": "drinks",
        "country": "AE"
      },
      {
        "id": "ae-drin-4",
        "name": "Barbican Non-Alcoholic Apple Malt Beverage",
        "brand": "Aujan AE",
        "calories": 115,
        "protein": 0.0,
        "carbs": 28.0,
        "fats": 0.0,
        "serving_size": "330ml bottle",
        "serving_grams": 330,
        "category": "drinks",
        "country": "AE"
      }
    ]
  },
  "MY": {
    "protein": [
      {
        "id": "my-prot-1",
        "name": "Ayam Dada Segar Halal Dada Ayam Rebus",
        "brand": "Ayamas MY",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "MY"
      },
      {
        "id": "my-prot-2",
        "name": "Ikan Kembung Bakar Air Asam Segar",
        "brand": "Pasar Basah MY",
        "calories": 140,
        "protein": 22.0,
        "carbs": 0.5,
        "fats": 5.5,
        "serving_size": "1 ekor (120g)",
        "serving_grams": 120,
        "category": "protein",
        "country": "MY"
      },
      {
        "id": "my-prot-3",
        "name": "Telur Ayam Gred A Bersih (2 biji)",
        "brand": "CP Malaysia",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 biji (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "MY"
      },
      {
        "id": "my-prot-4",
        "name": "Tauhu Keras Basah Organik",
        "brand": "Nutrisoy MY",
        "calories": 110,
        "protein": 12.0,
        "carbs": 2.5,
        "fats": 6.0,
        "serving_size": "1 keping (120g)",
        "serving_grams": 120,
        "category": "protein",
        "country": "MY"
      },
      {
        "id": "my-prot-5",
        "name": "Tempeh Soya Segar Asli Potong",
        "brand": "Tempeh MY",
        "calories": 160,
        "protein": 16.0,
        "carbs": 8.5,
        "fats": 7.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "MY"
      },
      {
        "id": "my-prot-6",
        "name": "Ayam Brand Tuna dalam Air Mineral",
        "brand": "Ayam Brand MY",
        "calories": 105,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "1 tin (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "MY"
      }
    ],
    "carbs": [
      {
        "id": "my-carb-1",
        "name": "Beras Basmati Jasmine Sunwhite Cooked",
        "brand": "Jasmine MY",
        "calories": 170,
        "protein": 3.5,
        "carbs": 37.0,
        "fats": 0.5,
        "serving_size": "1 mangkuk (130g)",
        "serving_grams": 130,
        "category": "carbs",
        "country": "MY"
      },
      {
        "id": "my-carb-2",
        "name": "Capati Gandum Tulen Panas (1 keping)",
        "brand": "Restoran Mamak",
        "calories": 120,
        "protein": 3.8,
        "carbs": 24.0,
        "fats": 1.2,
        "serving_size": "1 keping (50g)",
        "serving_grams": 50,
        "category": "carbs",
        "country": "MY"
      },
      {
        "id": "my-carb-3",
        "name": "Ubi Keledek Manis Rebus Lembut",
        "brand": "Pasar Malam MY",
        "calories": 90,
        "protein": 1.6,
        "carbs": 21.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "MY"
      },
      {
        "id": "my-carb-4",
        "name": "Quaker Rolled Oats Malaysia",
        "brand": "Quaker MY",
        "calories": 145,
        "protein": 5.0,
        "carbs": 26.0,
        "fats": 2.5,
        "serving_size": "40g",
        "serving_grams": 40,
        "category": "carbs",
        "country": "MY"
      },
      {
        "id": "my-carb-5",
        "name": "Pisang Berangan Segar Manis",
        "brand": "Buah Tempatan MY",
        "calories": 95,
        "protein": 1.2,
        "carbs": 24.0,
        "fats": 0.2,
        "serving_size": "1 biji (100g)",
        "serving_grams": 100,
        "category": "carbs",
        "country": "MY"
      }
    ],
    "fats": [
      {
        "id": "my-fats-1",
        "name": "Tong Garden Roasted Whole California Almonds",
        "brand": "Tong Garden MY",
        "calories": 170,
        "protein": 6.0,
        "carbs": 6.0,
        "fats": 14.5,
        "serving_size": "30g",
        "serving_grams": 30,
        "category": "fats",
        "country": "MY"
      },
      {
        "id": "my-fats-2",
        "name": "Borges Extra Virgin Olive Oil Malaysia",
        "brand": "Borges MY",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 sudu besar (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "MY"
      },
      {
        "id": "my-fats-3",
        "name": "Lady's Choice Natural Peanut Butter",
        "brand": "Lady's Choice MY",
        "calories": 190,
        "protein": 7.5,
        "carbs": 7.0,
        "fats": 16.0,
        "serving_size": "2 sudu (32g)",
        "serving_grams": 32,
        "category": "fats",
        "country": "MY"
      },
      {
        "id": "my-fats-4",
        "name": "Santan Kelapa UHT Rendah Lemak Kara",
        "brand": "Kara MY",
        "calories": 75,
        "protein": 1.0,
        "carbs": 2.5,
        "fats": 7.0,
        "serving_size": "50ml",
        "serving_grams": 50,
        "category": "fats",
        "country": "MY"
      }
    ],
    "fastfood": [
      {
        "id": "my-fast-1",
        "name": "Nasi Lemak Ayam Goreng Berempah Dada",
        "brand": "Village Park MY",
        "calories": 590,
        "protein": 38.0,
        "carbs": 65.0,
        "fats": 21.0,
        "serving_size": "1 bungkus (400g)",
        "serving_grams": 400,
        "category": "fastfood",
        "country": "MY"
      },
      {
        "id": "my-fast-2",
        "name": "Satay Ayam Kajang dengan Kuah Kacang (5 cucuk)",
        "brand": "Sate Kajang MY",
        "calories": 280,
        "protein": 26.0,
        "carbs": 14.0,
        "fats": 12.0,
        "serving_size": "5 cucuk (150g)",
        "serving_grams": 150,
        "category": "fastfood",
        "country": "MY"
      },
      {
        "id": "my-fast-3",
        "name": "Roti Telur Mamak dengan Kuah Dhal",
        "brand": "Restoran Mamak",
        "calories": 290,
        "protein": 10.5,
        "carbs": 38.0,
        "fats": 11.0,
        "serving_size": "1 keping (130g)",
        "serving_grams": 130,
        "category": "fastfood",
        "country": "MY"
      },
      {
        "id": "my-fast-4",
        "name": "Marrybrown Hotouch Fried Chicken Breast",
        "brand": "Marrybrown MY",
        "calories": 320,
        "protein": 28.0,
        "carbs": 14.0,
        "fats": 17.0,
        "serving_size": "1 piece (140g)",
        "serving_grams": 140,
        "category": "fastfood",
        "country": "MY"
      }
    ],
    "drinks": [
      {
        "id": "my-drin-1",
        "name": "Air Kelapa Pandan Muda Asli",
        "brand": "Gerai Kelapa MY",
        "calories": 45,
        "protein": 1.0,
        "carbs": 10.5,
        "fats": 0.2,
        "serving_size": "1 biji (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "MY"
      },
      {
        "id": "my-drin-2",
        "name": "Teh Tarik Kurang Manis Mamak",
        "brand": "Restoran Mamak",
        "calories": 110,
        "protein": 3.5,
        "carbs": 17.0,
        "fats": 3.2,
        "serving_size": "1 gelas (220ml)",
        "serving_grams": 220,
        "category": "drinks",
        "country": "MY"
      },
      {
        "id": "my-drin-3",
        "name": "100 Plus Active Isotonic Drink No Gas",
        "brand": "F&N 100 Plus MY",
        "calories": 60,
        "protein": 0.0,
        "carbs": 15.0,
        "fats": 0.0,
        "serving_size": "325ml can",
        "serving_grams": 325,
        "category": "drinks",
        "country": "MY"
      },
      {
        "id": "my-drin-4",
        "name": "Kopi-O Kosong Panas Tanpa Gula",
        "brand": "Kopitiam MY",
        "calories": 5,
        "protein": 0.3,
        "carbs": 0.5,
        "fats": 0.0,
        "serving_size": "1 cawan (180ml)",
        "serving_grams": 180,
        "category": "drinks",
        "country": "MY"
      }
    ]
  },
  "TH": {
    "protein": [
      {
        "id": "th-prot-1",
        "name": "Ok Gai Steamed Chicken Breast (อกไก่ต้ม)",
        "brand": "7-Eleven Thailand",
        "calories": 130,
        "protein": 28.0,
        "carbs": 0.5,
        "fats": 1.5,
        "serving_size": "1 pack (120g)",
        "serving_grams": 120,
        "category": "protein",
        "country": "TH"
      },
      {
        "id": "th-prot-2",
        "name": "Pla Krapong Steamed Seabass with Lime & Garlic (ปลากะพงนึ่งมะนาว)",
        "brand": "Thai Kitchen",
        "calories": 140,
        "protein": 25.0,
        "carbs": 3.0,
        "fats": 3.0,
        "serving_size": "150g serve",
        "serving_grams": 150,
        "category": "protein",
        "country": "TH"
      },
      {
        "id": "th-prot-3",
        "name": "Fresh Farm Boiled Eggs (ไข่ต้มยางมะตูม 2 ฟอง)",
        "brand": "Betagro TH",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "TH"
      },
      {
        "id": "th-prot-4",
        "name": "Tofusan High Protein Soy Milk No Added Sugar",
        "brand": "Tofusan TH",
        "calories": 140,
        "protein": 15.0,
        "carbs": 8.0,
        "fats": 4.5,
        "serving_size": "350ml bottle",
        "serving_grams": 350,
        "category": "protein",
        "country": "TH"
      },
      {
        "id": "th-prot-5",
        "name": "Fresh Boiled White Prawns (กุ้งขาวลวก)",
        "brand": "Talat Thai",
        "calories": 95,
        "protein": 21.0,
        "carbs": 0.5,
        "fats": 1.0,
        "serving_size": "100g peeled",
        "serving_grams": 100,
        "category": "protein",
        "country": "TH"
      },
      {
        "id": "th-prot-6",
        "name": "Grilled Moo Ping Pork Skewers Lean (หมูปิ้งไร้มัน 3 ไม้)",
        "brand": "Street Stall TH",
        "calories": 210,
        "protein": 24.0,
        "carbs": 6.0,
        "fats": 9.5,
        "serving_size": "3 skewers (120g)",
        "serving_grams": 120,
        "category": "protein",
        "country": "TH"
      }
    ],
    "carbs": [
      {
        "id": "th-carb-1",
        "name": "Thai Hom Mali Jasmine Rice (ข้าวหอมมะลิ)",
        "brand": "Royal Umbrella TH",
        "calories": 175,
        "protein": 3.2,
        "carbs": 38.0,
        "fats": 0.4,
        "serving_size": "1 plate (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "TH"
      },
      {
        "id": "th-carb-2",
        "name": "Riceberry Organic Purple Antioxidant Rice (ข้าวไรซ์เบอร์รี่)",
        "brand": "Organic Thai",
        "calories": 165,
        "protein": 3.8,
        "carbs": 35.0,
        "fats": 1.0,
        "serving_size": "1 plate (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "TH"
      },
      {
        "id": "th-carb-3",
        "name": "Steamed Sticky Rice (ข้าวเหนียวนึ่ง)",
        "brand": "Street Stall TH",
        "calories": 190,
        "protein": 3.5,
        "carbs": 42.0,
        "fats": 0.5,
        "serving_size": "1 packet (100g)",
        "serving_grams": 100,
        "category": "carbs",
        "country": "TH"
      },
      {
        "id": "th-carb-4",
        "name": "Steamed Japanese Sweet Purple Potato (มันหวานญี่ปุ่น)",
        "brand": "7-Eleven TH",
        "calories": 120,
        "protein": 1.8,
        "carbs": 28.0,
        "fats": 0.2,
        "serving_size": "1 piece (110g)",
        "serving_grams": 110,
        "category": "carbs",
        "country": "TH"
      },
      {
        "id": "th-carb-5",
        "name": "Boiled Sweet Yellow Corn (ข้าวโพดหวานต้ม)",
        "brand": "Street Market TH",
        "calories": 110,
        "protein": 3.8,
        "carbs": 24.0,
        "fats": 1.2,
        "serving_size": "1 cob (120g)",
        "serving_grams": 120,
        "category": "carbs",
        "country": "TH"
      }
    ],
    "fats": [
      {
        "id": "th-fats-1",
        "name": "Agrilife 100% Cold Pressed Organic Coconut Oil",
        "brand": "Agrilife TH",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "TH"
      },
      {
        "id": "th-fats-2",
        "name": "Tong Garden Salted Roasted Cashew Nuts",
        "brand": "Tong Garden TH",
        "calories": 175,
        "protein": 5.5,
        "carbs": 9.0,
        "fats": 14.0,
        "serving_size": "30g pack",
        "serving_grams": 30,
        "category": "fats",
        "country": "TH"
      },
      {
        "id": "th-fats-3",
        "name": "Fresh Hass Avocado",
        "brand": "Tops Supermarket TH",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "TH"
      },
      {
        "id": "th-fats-4",
        "name": "Pure White Sesame Oil Dragon Brand",
        "brand": "Dragon Brand TH",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "TH"
      }
    ],
    "fastfood": [
      {
        "id": "th-fast-1",
        "name": "Pad Krapow Gai Basil Chicken with Rice (ผัดกะเพราไก่)",
        "brand": "Street Vendor TH",
        "calories": 480,
        "protein": 36.0,
        "carbs": 56.0,
        "fats": 13.0,
        "serving_size": "1 plate (350g)",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "TH"
      },
      {
        "id": "th-fast-2",
        "name": "Som Tum Thai Spicy Papaya Salad with Peanuts (ส้มตำไทย)",
        "brand": "Isan Kitchen TH",
        "calories": 140,
        "protein": 4.0,
        "carbs": 26.0,
        "fats": 3.0,
        "serving_size": "1 dish (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "TH"
      },
      {
        "id": "th-fast-3",
        "name": "Gai Yang Five Star Grilled Chicken Quarter (ไก่ย่างห้าดาว)",
        "brand": "Five Star TH",
        "calories": 260,
        "protein": 34.0,
        "carbs": 1.0,
        "fats": 13.0,
        "serving_size": "1 quarter (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "TH"
      },
      {
        "id": "th-fast-4",
        "name": "Tom Yum Goong Spicy & Sour Prawn Soup (ต้มยำกุ้ง)",
        "brand": "Thai Seafood",
        "calories": 160,
        "protein": 20.0,
        "carbs": 8.0,
        "fats": 5.0,
        "serving_size": "1 bowl (300g)",
        "serving_grams": 300,
        "category": "fastfood",
        "country": "TH"
      }
    ],
    "drinks": [
      {
        "id": "th-drin-1",
        "name": "Fresh Young Thai Coconut Water Direct (น้ำมะพร้าวสด)",
        "brand": "Fresh Farm TH",
        "calories": 45,
        "protein": 1.0,
        "carbs": 10.5,
        "fats": 0.2,
        "serving_size": "1 coconut (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "TH"
      },
      {
        "id": "th-drin-2",
        "name": "Singha Soda Water Carbonated Water Zero (สิงห์โซดา)",
        "brand": "Singha TH",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "325ml bottle",
        "serving_grams": 325,
        "category": "drinks",
        "country": "TH"
      },
      {
        "id": "th-drin-3",
        "name": "Oishi Green Tea Honey Lemon 0 Kcal",
        "brand": "Oishi TH",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "380ml bottle",
        "serving_grams": 380,
        "category": "drinks",
        "country": "TH"
      },
      {
        "id": "th-drin-4",
        "name": "Cha Tra Mue Thai Iced Tea Low Sweetness",
        "brand": "Cha Tra Mue TH",
        "calories": 95,
        "protein": 2.5,
        "carbs": 16.0,
        "fats": 2.0,
        "serving_size": "1 cup (350ml)",
        "serving_grams": 350,
        "category": "drinks",
        "country": "TH"
      }
    ]
  },
  "PH": {
    "protein": [
      {
        "id": "ph-prot-1",
        "name": "Magnolia Fresh Skinless Chicken Breast",
        "brand": "Magnolia PH",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "PH"
      },
      {
        "id": "ph-prot-2",
        "name": "Inihaw na Bangus Grilled Boneless Milkfish",
        "brand": "Dampa Seafood PH",
        "calories": 180,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 9.0,
        "serving_size": "150g fillet",
        "serving_grams": 150,
        "category": "protein",
        "country": "PH"
      },
      {
        "id": "ph-prot-3",
        "name": "Century Tuna Flakes in Water Light",
        "brand": "Century Pacific PH",
        "calories": 110,
        "protein": 25.0,
        "carbs": 0.0,
        "fats": 1.0,
        "serving_size": "1 can (155g)",
        "serving_grams": 155,
        "category": "protein",
        "country": "PH"
      },
      {
        "id": "ph-prot-4",
        "name": "San Marino Corned Tuna Chili",
        "brand": "San Marino PH",
        "calories": 140,
        "protein": 18.0,
        "carbs": 4.0,
        "fats": 6.0,
        "serving_size": "1 can (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "PH"
      },
      {
        "id": "ph-prot-5",
        "name": "Tokwa Extra Firm Tofu Slices (Cooked)",
        "brand": "Palengke PH",
        "calories": 120,
        "protein": 13.0,
        "carbs": 2.5,
        "fats": 6.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "PH"
      },
      {
        "id": "ph-prot-6",
        "name": "Farm Fresh Extra Large Eggs (2 eggs)",
        "brand": "Bounty Fresh PH",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "PH"
      }
    ],
    "carbs": [
      {
        "id": "ph-carb-1",
        "name": "Sinandomeng Steamed White Rice",
        "brand": "Harvester's PH",
        "calories": 175,
        "protein": 3.2,
        "carbs": 38.0,
        "fats": 0.4,
        "serving_size": "1 cup (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "PH"
      },
      {
        "id": "ph-carb-2",
        "name": "Dinorado Brown Rice Nutritious",
        "brand": "Harvester's PH",
        "calories": 165,
        "protein": 3.8,
        "carbs": 35.0,
        "fats": 1.0,
        "serving_size": "1 cup (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "PH"
      },
      {
        "id": "ph-carb-3",
        "name": "Boiled Kamote Sweet Potato with Skin",
        "brand": "Palengke PH",
        "calories": 95,
        "protein": 1.6,
        "carbs": 22.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "PH"
      },
      {
        "id": "ph-carb-4",
        "name": "Fresh Pan de Sal Rolls (2 pieces)",
        "brand": "Panaderia PH",
        "calories": 145,
        "protein": 4.5,
        "carbs": 28.0,
        "fats": 2.0,
        "serving_size": "2 pandesal (50g)",
        "serving_grams": 50,
        "category": "carbs",
        "country": "PH"
      },
      {
        "id": "ph-carb-5",
        "name": "Saba Banana Boiled (Nilagang Saba)",
        "brand": "Palengke PH",
        "calories": 105,
        "protein": 1.2,
        "carbs": 26.0,
        "fats": 0.2,
        "serving_size": "1 banana (110g)",
        "serving_grams": 110,
        "category": "carbs",
        "country": "PH"
      }
    ],
    "fats": [
      {
        "id": "ph-fats-1",
        "name": "Minola 100% Pure Premium Coconut Cooking Oil",
        "brand": "Minola PH",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "PH"
      },
      {
        "id": "ph-fats-2",
        "name": "Bicolano Raw Natural Pili Nuts",
        "brand": "Pili Bicol PH",
        "calories": 210,
        "protein": 3.5,
        "carbs": 1.5,
        "fats": 23.0,
        "serving_size": "30g",
        "serving_grams": 30,
        "category": "fats",
        "country": "PH"
      },
      {
        "id": "ph-fats-3",
        "name": "Fresh Ripe Hass Avocado",
        "brand": "SM Supermarket PH",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "PH"
      },
      {
        "id": "ph-fats-4",
        "name": "Skippy Creamy All Natural Peanut Butter",
        "brand": "Skippy PH",
        "calories": 190,
        "protein": 7.5,
        "carbs": 7.0,
        "fats": 16.0,
        "serving_size": "2 tbsp (32g)",
        "serving_grams": 32,
        "category": "fats",
        "country": "PH"
      }
    ],
    "fastfood": [
      {
        "id": "ph-fast-1",
        "name": "Jollibee Chickenjoy Breast Fillet with Rice",
        "brand": "Jollibee PH",
        "calories": 460,
        "protein": 32.0,
        "carbs": 44.0,
        "fats": 18.0,
        "serving_size": "1 meal (260g)",
        "serving_grams": 260,
        "category": "fastfood",
        "country": "PH"
      },
      {
        "id": "ph-fast-2",
        "name": "Mang Inasal Pecho Large Grilled Chicken with Rice",
        "brand": "Mang Inasal PH",
        "calories": 490,
        "protein": 46.0,
        "carbs": 48.0,
        "fats": 12.0,
        "serving_size": "1 meal (340g)",
        "serving_grams": 340,
        "category": "fastfood",
        "country": "PH"
      },
      {
        "id": "ph-fast-3",
        "name": "Andok's Litson Manok Roasted Chicken Quarter",
        "brand": "Andok's PH",
        "calories": 270,
        "protein": 36.0,
        "carbs": 1.0,
        "fats": 13.5,
        "serving_size": "1 quarter (190g)",
        "serving_grams": 190,
        "category": "fastfood",
        "country": "PH"
      },
      {
        "id": "ph-fast-4",
        "name": "Jollibee Regular Yumburger with Dressing",
        "brand": "Jollibee PH",
        "calories": 250,
        "protein": 11.0,
        "carbs": 31.0,
        "fats": 9.0,
        "serving_size": "1 burger (115g)",
        "serving_grams": 115,
        "category": "fastfood",
        "country": "PH"
      }
    ],
    "drinks": [
      {
        "id": "ph-drin-1",
        "name": "Fresh Buko Juice Young Coconut with Meat",
        "brand": "Buko Stall PH",
        "calories": 50,
        "protein": 1.0,
        "carbs": 11.5,
        "fats": 0.2,
        "serving_size": "300ml cup",
        "serving_grams": 300,
        "category": "drinks",
        "country": "PH"
      },
      {
        "id": "ph-drin-2",
        "name": "C2 Cool & Clean Green Tea Apple Zero Sugar",
        "brand": "Universal Robina PH",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "355ml bottle",
        "serving_grams": 355,
        "category": "drinks",
        "country": "PH"
      },
      {
        "id": "ph-drin-3",
        "name": "Fresh Calamansi Honey Juice Ice Cold",
        "brand": "Palengke PH",
        "calories": 65,
        "protein": 0.5,
        "carbs": 16.0,
        "fats": 0.0,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "PH"
      },
      {
        "id": "ph-drin-4",
        "name": "San Miguel Pale Pilsen 0.0% Non-Alcoholic",
        "brand": "San Miguel Brewery PH",
        "calories": 45,
        "protein": 0.5,
        "carbs": 10.0,
        "fats": 0.0,
        "serving_size": "330ml bottle",
        "serving_grams": 330,
        "category": "drinks",
        "country": "PH"
      }
    ]
  }
};
