import { RegionalFoodMap } from './types';

export const EUROPE_FOODS: RegionalFoodMap = {
  "GB": {
    "protein": [
      {
        "id": "gb-prot-1",
        "name": "Myprotein Impact Whey Isolate Chocolate Smooth",
        "brand": "Myprotein UK",
        "calories": 95,
        "protein": 22.0,
        "carbs": 0.6,
        "fats": 0.3,
        "serving_size": "1 scoop (25g)",
        "serving_grams": 25,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-2",
        "name": "Grenade Carb Killa High Protein Bar Caramel Chaos",
        "brand": "Grenade UK",
        "calories": 215,
        "protein": 20.0,
        "carbs": 15.0,
        "fats": 8.0,
        "serving_size": "1 bar (60g)",
        "serving_grams": 60,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-3",
        "name": "Tesco British Diced Chicken Breast Fillets",
        "brand": "Tesco UK",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-4",
        "name": "Arla Protein Vanilla High Protein Yogurt Pouch",
        "brand": "Arla UK",
        "calories": 140,
        "protein": 20.0,
        "carbs": 14.0,
        "fats": 0.4,
        "serving_size": "200g pouch",
        "serving_grams": 200,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-5",
        "name": "M&S British 5% Fat Lean Beef Steak Mince",
        "brand": "Marks & Spencer UK",
        "calories": 135,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 5.0,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-6",
        "name": "John West No Drain Tuna Steak in Spring Water",
        "brand": "John West UK",
        "calories": 120,
        "protein": 28.0,
        "carbs": 0.0,
        "fats": 0.8,
        "serving_size": "1 can (110g)",
        "serving_grams": 110,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-7",
        "name": "Fage Total 0% Fat Authentic Greek Strained Yoghurt",
        "brand": "Fage UK",
        "calories": 90,
        "protein": 15.5,
        "carbs": 6.0,
        "fats": 0.0,
        "serving_size": "170g pot",
        "serving_grams": 170,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-8",
        "name": "Birds Eye Wild Pink Salmon Fillets",
        "brand": "Birds Eye UK",
        "calories": 185,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 11.0,
        "serving_size": "1 fillet (110g)",
        "serving_grams": 110,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-9",
        "name": "Two Chicks Liquid Free Range Egg Whites",
        "brand": "Two Chicks UK",
        "calories": 48,
        "protein": 10.5,
        "carbs": 0.8,
        "fats": 0.1,
        "serving_size": "100g serve",
        "serving_grams": 100,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-10",
        "name": "Heck 97% Pure Pork Gluten Free Sausages (2 sausages)",
        "brand": "Heck UK",
        "calories": 160,
        "protein": 17.0,
        "carbs": 1.2,
        "fats": 9.8,
        "serving_size": "2 sausages (70g)",
        "serving_grams": 70,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-11",
        "name": "Quorn Vegetarian Mince Meatless",
        "brand": "Quorn UK",
        "calories": 105,
        "protein": 14.5,
        "carbs": 4.5,
        "fats": 2.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "GB"
      },
      {
        "id": "gb-prot-12",
        "name": "Huel Black Edition High Protein Complete Nutrition",
        "brand": "Huel UK",
        "calories": 400,
        "protein": 40.0,
        "carbs": 17.0,
        "fats": 18.0,
        "serving_size": "2 scoops (90g)",
        "serving_grams": 90,
        "category": "protein",
        "country": "GB"
      }
    ],
    "carbs": [
      {
        "id": "gb-carb-1",
        "name": "Quaker Rolled Traditional Porridge Oats",
        "brand": "Quaker UK",
        "calories": 150,
        "protein": 5.0,
        "carbs": 27.0,
        "fats": 2.5,
        "serving_size": "1 portion (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-2",
        "name": "Warburtons Wholemeal Medium Sliced Bread",
        "brand": "Warburtons UK",
        "calories": 168,
        "protein": 7.8,
        "carbs": 29.5,
        "fats": 1.8,
        "serving_size": "2 slices (76g)",
        "serving_grams": 76,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-3",
        "name": "Tilda Pure Steamed Basmati Rice Pouch",
        "brand": "Tilda UK",
        "calories": 170,
        "protein": 3.5,
        "carbs": 36.0,
        "fats": 1.2,
        "serving_size": "1/2 pouch (125g)",
        "serving_grams": 125,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-4",
        "name": "Albert Bartlett British Rooster Potatoes Boiled",
        "brand": "Albert Bartlett UK",
        "calories": 130,
        "protein": 3.0,
        "carbs": 29.0,
        "fats": 0.2,
        "serving_size": "1 medium (160g)",
        "serving_grams": 160,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-5",
        "name": "M&S British Sweet Potatoes Steamed",
        "brand": "Marks & Spencer UK",
        "calories": 90,
        "protein": 1.8,
        "carbs": 21.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-6",
        "name": "Weetabix Original 100% Whole Wheat Cereal (2 biscuits)",
        "brand": "Weetabix UK",
        "calories": 136,
        "protein": 4.5,
        "carbs": 26.0,
        "fats": 0.8,
        "serving_size": "2 biscuits (37.5g)",
        "serving_grams": 38,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-7",
        "name": "Ryvita Dark Rye Wholegrain Crispbread (2 slices)",
        "brand": "Ryvita UK",
        "calories": 70,
        "protein": 2.2,
        "carbs": 13.6,
        "fats": 0.4,
        "serving_size": "2 slices (20g)",
        "serving_grams": 20,
        "category": "carbs",
        "country": "GB"
      },
      {
        "id": "gb-carb-8",
        "name": "Napolina Whole Wheat Penne Rigate",
        "brand": "Napolina UK",
        "calories": 175,
        "protein": 6.5,
        "carbs": 34.0,
        "fats": 1.2,
        "serving_size": "50g dry",
        "serving_grams": 50,
        "category": "carbs",
        "country": "GB"
      }
    ],
    "fats": [
      {
        "id": "gb-fats-1",
        "name": "Whole Earth Crunchy 100% Pure Peanut Butter",
        "brand": "Whole Earth UK",
        "calories": 98,
        "protein": 4.5,
        "carbs": 1.8,
        "fats": 8.2,
        "serving_size": "1 tbsp (16g)",
        "serving_grams": 16,
        "category": "fats",
        "country": "GB"
      },
      {
        "id": "gb-fats-2",
        "name": "Napolina Extra Virgin Cold Pressed Olive Oil",
        "brand": "Napolina UK",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "GB"
      },
      {
        "id": "gb-fats-3",
        "name": "Fresh Ripe Hass Avocado",
        "brand": "Tesco UK",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "GB"
      },
      {
        "id": "gb-fats-4",
        "name": "Whitworths Natural Raw Walnut Halves",
        "brand": "Whitworths UK",
        "calories": 195,
        "protein": 4.4,
        "carbs": 4.0,
        "fats": 19.5,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "GB"
      },
      {
        "id": "gb-fats-5",
        "name": "Pip & Nut All Natural Smooth Almond Butter",
        "brand": "Pip & Nut UK",
        "calories": 102,
        "protein": 3.8,
        "carbs": 2.0,
        "fats": 9.0,
        "serving_size": "1 tbsp (16g)",
        "serving_grams": 16,
        "category": "fats",
        "country": "GB"
      },
      {
        "id": "gb-fats-6",
        "name": "Cathedral City Extra Mature English Cheddar",
        "brand": "Cathedral City UK",
        "calories": 205,
        "protein": 12.5,
        "carbs": 0.1,
        "fats": 17.5,
        "serving_size": "50g serve",
        "serving_grams": 50,
        "category": "fats",
        "country": "GB"
      }
    ],
    "fastfood": [
      {
        "id": "gb-fast-1",
        "name": "Nando's UK Half Peri-Peri Chicken (Medium Lemon & Herb)",
        "brand": "Nando's UK",
        "calories": 540,
        "protein": 58.0,
        "carbs": 1.5,
        "fats": 32.0,
        "serving_size": "1/2 chicken (340g)",
        "serving_grams": 340,
        "category": "fastfood",
        "country": "GB"
      },
      {
        "id": "gb-fast-2",
        "name": "Greggs Warm Fresh Baked Sausage Roll",
        "brand": "Greggs UK",
        "calories": 327,
        "protein": 9.3,
        "carbs": 24.0,
        "fats": 22.0,
        "serving_size": "1 roll (103g)",
        "serving_grams": 103,
        "category": "fastfood",
        "country": "GB"
      },
      {
        "id": "gb-fast-3",
        "name": "Greggs Vegan Sausage Roll",
        "brand": "Greggs UK",
        "calories": 303,
        "protein": 12.0,
        "carbs": 23.0,
        "fats": 18.0,
        "serving_size": "1 roll (101g)",
        "serving_grams": 101,
        "category": "fastfood",
        "country": "GB"
      },
      {
        "id": "gb-fast-4",
        "name": "Wagamama Grilled Chicken Katsu Salad with Dressing",
        "brand": "Wagamama UK",
        "calories": 420,
        "protein": 36.0,
        "carbs": 32.0,
        "fats": 14.0,
        "serving_size": "1 salad bowl",
        "serving_grams": 360,
        "category": "fastfood",
        "country": "GB"
      },
      {
        "id": "gb-fast-5",
        "name": "Pret A Manger Classic Super Club Sandwich",
        "brand": "Pret A Manger UK",
        "calories": 470,
        "protein": 26.0,
        "carbs": 42.0,
        "fats": 21.0,
        "serving_size": "1 sandwich (215g)",
        "serving_grams": 215,
        "category": "fastfood",
        "country": "GB"
      },
      {
        "id": "gb-fast-6",
        "name": "Subway UK 6-Inch Roast Beef on Wheat",
        "brand": "Subway UK",
        "calories": 310,
        "protein": 24.0,
        "carbs": 42.0,
        "fats": 5.0,
        "serving_size": "6-inch (225g)",
        "serving_grams": 225,
        "category": "fastfood",
        "country": "GB"
      }
    ],
    "drinks": [
      {
        "id": "gb-drin-1",
        "name": "Ufit 25g High Protein Shake Chocolate",
        "brand": "Ufit UK",
        "calories": 170,
        "protein": 25.0,
        "carbs": 11.0,
        "fats": 2.2,
        "serving_size": "310ml bottle",
        "serving_grams": 310,
        "category": "drinks",
        "country": "GB"
      },
      {
        "id": "gb-drin-2",
        "name": "Myprotein Clear Whey Isolate Peach Tea Flavour",
        "brand": "Myprotein UK",
        "calories": 85,
        "protein": 20.0,
        "carbs": 0.7,
        "fats": 0.1,
        "serving_size": "1 scoop in 400ml",
        "serving_grams": 400,
        "category": "drinks",
        "country": "GB"
      },
      {
        "id": "gb-drin-3",
        "name": "Innocent Energise Super Smoothie (Guava & Lime)",
        "brand": "Innocent UK",
        "calories": 130,
        "protein": 1.5,
        "carbs": 30.0,
        "fats": 0.2,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "GB"
      },
      {
        "id": "gb-drin-4",
        "name": "Costa Coffee Flat White with Skimmed Milk",
        "brand": "Costa Coffee UK",
        "calories": 70,
        "protein": 6.5,
        "carbs": 9.0,
        "fats": 0.5,
        "serving_size": "Medium (340ml)",
        "serving_grams": 340,
        "category": "drinks",
        "country": "GB"
      },
      {
        "id": "gb-drin-5",
        "name": "Lucozade Sport Isotonic Drink Orange",
        "brand": "Lucozade UK",
        "calories": 140,
        "protein": 0.0,
        "carbs": 33.0,
        "fats": 0.0,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "GB"
      },
      {
        "id": "gb-drin-6",
        "name": "Twinings Traditional Pure English Breakfast Tea",
        "brand": "Twinings UK",
        "calories": 2,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 mug (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "GB"
      }
    ]
  },
  "DE": {
    "protein": [
      {
        "id": "de-prot-1",
        "name": "Magerquark Speisequark Magerstufe (0.2% Fett)",
        "brand": "Ja! / Milram DE",
        "calories": 68,
        "protein": 12.0,
        "carbs": 4.0,
        "fats": 0.2,
        "serving_size": "100g porportion",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-2",
        "name": "ESN Designer Whey Protein Vanilla Ice Cream",
        "brand": "ESN Elite Sports DE",
        "calories": 115,
        "protein": 23.5,
        "carbs": 2.0,
        "fats": 1.5,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-3",
        "name": "Ja! Hähnchenbrustfilet Teilstücke Frisch",
        "brand": "REWE Ja! DE",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g gebraten",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-4",
        "name": "Gut & Günstig Mageres Rinderhackfleisch (max 10%)",
        "brand": "EDEKA DE",
        "calories": 155,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 7.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-5",
        "name": "Milram Skyr Natur Isländische Tradition",
        "brand": "Milram DE",
        "calories": 65,
        "protein": 11.0,
        "carbs": 4.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-6",
        "name": "Thunfischfilets im eigenen Saft und Aufguss",
        "brand": "Saupiquet DE",
        "calories": 110,
        "protein": 26.0,
        "carbs": 0.0,
        "fats": 0.7,
        "serving_size": "1 Dose (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-7",
        "name": "Bio Eier Freilandhaltung Klasse M (2 Eier)",
        "brand": "Bio REWE DE",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 Eier (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-8",
        "name": "Exquisa Fitline 0.2% Kräuter Frischkäse",
        "brand": "Exquisa DE",
        "calories": 62,
        "protein": 10.5,
        "carbs": 4.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-9",
        "name": "Alpro Soja High Protein Quark Alternative",
        "brand": "Alpro DE",
        "calories": 75,
        "protein": 6.0,
        "carbs": 3.0,
        "fats": 3.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      },
      {
        "id": "de-prot-10",
        "name": "Taifun Bio Tofu Natur Fest",
        "brand": "Taifun DE",
        "calories": 135,
        "protein": 15.0,
        "carbs": 1.5,
        "fats": 8.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "DE"
      }
    ],
    "carbs": [
      {
        "id": "de-carb-1",
        "name": "Kölln Flocken Blütenzarte Haferflocken",
        "brand": "Kölln DE",
        "calories": 145,
        "protein": 5.2,
        "carbs": 24.5,
        "fats": 2.8,
        "serving_size": "40g Portion",
        "serving_grams": 40,
        "category": "carbs",
        "country": "DE"
      },
      {
        "id": "de-carb-2",
        "name": "Deutsches Vollkorn-Roggenbrot Frisches",
        "brand": "Bäckerei DE",
        "calories": 185,
        "protein": 6.5,
        "carbs": 34.0,
        "fats": 1.5,
        "serving_size": "2 Scheiben (80g)",
        "serving_grams": 80,
        "category": "carbs",
        "country": "DE"
      },
      {
        "id": "de-carb-3",
        "name": "Deutsche Speisekartoffeln Festkochend Gekocht",
        "brand": "Bioland DE",
        "calories": 72,
        "protein": 2.0,
        "carbs": 15.5,
        "fats": 0.1,
        "serving_size": "100g gekocht",
        "serving_grams": 100,
        "category": "carbs",
        "country": "DE"
      },
      {
        "id": "de-carb-4",
        "name": "Bio Süßkartoffeln aus kontrolliertem Anbau",
        "brand": "EDEKA Bio DE",
        "calories": 88,
        "protein": 1.6,
        "carbs": 20.0,
        "fats": 0.2,
        "serving_size": "100g gebacken",
        "serving_grams": 100,
        "category": "carbs",
        "country": "DE"
      },
      {
        "id": "de-carb-5",
        "name": "Barilla Vollkorn Spaghetti Integrale",
        "brand": "Barilla DE",
        "calories": 175,
        "protein": 6.5,
        "carbs": 33.0,
        "fats": 1.3,
        "serving_size": "50g trocken",
        "serving_grams": 50,
        "category": "carbs",
        "country": "DE"
      },
      {
        "id": "de-carb-6",
        "name": "Frische Münchner Laugenbrezel",
        "brand": "Bäckerei DE",
        "calories": 230,
        "protein": 7.5,
        "carbs": 44.0,
        "fats": 2.5,
        "serving_size": "1 Brezel (85g)",
        "serving_grams": 85,
        "category": "carbs",
        "country": "DE"
      },
      {
        "id": "de-carb-7",
        "name": "Pumpernickel Westfälisches Schwarzbrot",
        "brand": "Mestemacher DE",
        "calories": 120,
        "protein": 4.0,
        "carbs": 22.0,
        "fats": 1.0,
        "serving_size": "1 Scheibe (62g)",
        "serving_grams": 62,
        "category": "carbs",
        "country": "DE"
      }
    ],
    "fats": [
      {
        "id": "de-fats-1",
        "name": "Alnatura Bio Erdnussmus Fein (100% Erdnüsse)",
        "brand": "Alnatura DE",
        "calories": 185,
        "protein": 8.0,
        "carbs": 4.5,
        "fats": 15.5,
        "serving_size": "30g Portion",
        "serving_grams": 30,
        "category": "fats",
        "country": "DE"
      },
      {
        "id": "de-fats-2",
        "name": "Natives Olivenöl Extra Bio Kaltgepresst",
        "brand": "REWE Bio DE",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 EL (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "DE"
      },
      {
        "id": "de-fats-3",
        "name": "Kerrygold Irische Butter Original mit Meersalz",
        "brand": "Kerrygold DE",
        "calories": 108,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 12.0,
        "serving_size": "15g Portion",
        "serving_grams": 15,
        "category": "fats",
        "country": "DE"
      },
      {
        "id": "de-fats-4",
        "name": "Bio Walnusskerne Hälften naturbelassen",
        "brand": "Alnatura DE",
        "calories": 198,
        "protein": 4.5,
        "carbs": 3.8,
        "fats": 19.5,
        "serving_size": "30g Handvoll",
        "serving_grams": 30,
        "category": "fats",
        "country": "DE"
      },
      {
        "id": "de-fats-5",
        "name": "Steirische Kürbiskerne Geröstet",
        "brand": "Seitz DE",
        "calories": 170,
        "protein": 9.0,
        "carbs": 4.0,
        "fats": 14.5,
        "serving_size": "30g Portion",
        "serving_grams": 30,
        "category": "fats",
        "country": "DE"
      },
      {
        "id": "de-fats-6",
        "name": "Frische Hass Avocado Verzehrfertig",
        "brand": "EDEKA DE",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 Avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "DE"
      }
    ],
    "fastfood": [
      {
        "id": "de-fast-1",
        "name": "Berliner Döner Kebab Hähnchenfleisch Komplett",
        "brand": "Döner Imbiss DE",
        "calories": 640,
        "protein": 46.0,
        "carbs": 58.0,
        "fats": 24.0,
        "serving_size": "1 Döner (420g)",
        "serving_grams": 420,
        "category": "fastfood",
        "country": "DE"
      },
      {
        "id": "de-fast-2",
        "name": "Original Berliner Currywurst ohne Darm mit Sauce",
        "brand": "Curry 36 Berlin",
        "calories": 380,
        "protein": 16.0,
        "carbs": 14.0,
        "fats": 29.0,
        "serving_size": "1 Portion (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "DE"
      },
      {
        "id": "de-fast-3",
        "name": "Thüringer Rostbratwurst vom Grill im Brötchen",
        "brand": "Thüringer Grill DE",
        "calories": 420,
        "protein": 18.0,
        "carbs": 32.0,
        "fats": 26.0,
        "serving_size": "1 Wurst + Brötchen",
        "serving_grams": 170,
        "category": "fastfood",
        "country": "DE"
      },
      {
        "id": "de-fast-4",
        "name": "Falafel Dürüm Wrap mit frischem Salat & Tahin",
        "brand": "Orient Imbiss DE",
        "calories": 510,
        "protein": 16.0,
        "carbs": 68.0,
        "fats": 18.0,
        "serving_size": "1 Wrap (350g)",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "DE"
      },
      {
        "id": "de-fast-5",
        "name": "Nordsee Backfisch-Baguette mit Remoulade",
        "brand": "Nordsee DE",
        "calories": 490,
        "protein": 22.0,
        "carbs": 52.0,
        "fats": 21.0,
        "serving_size": "1 Baguette (230g)",
        "serving_grams": 230,
        "category": "fastfood",
        "country": "DE"
      },
      {
        "id": "de-fast-6",
        "name": "Subway Germany Chicken Teriyaki 15cm Vollkorn",
        "brand": "Subway DE",
        "calories": 340,
        "protein": 26.0,
        "carbs": 47.0,
        "fats": 4.5,
        "serving_size": "15cm (235g)",
        "serving_grams": 235,
        "category": "fastfood",
        "country": "DE"
      }
    ],
    "drinks": [
      {
        "id": "de-drin-1",
        "name": "Gerolsteiner Sprudel Natürliches Mineralwasser",
        "brand": "Gerolsteiner DE",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1L Flasche",
        "serving_grams": 1000,
        "category": "drinks",
        "country": "DE"
      },
      {
        "id": "de-drin-2",
        "name": "Fritz-Kola Ohne Zucker Kalorienarm",
        "brand": "Fritz-Kulturgüter DE",
        "calories": 1,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "330ml Flasche",
        "serving_grams": 330,
        "category": "drinks",
        "country": "DE"
      },
      {
        "id": "de-drin-3",
        "name": "Paulaner Spezi Zero Zuckerfreies Cola-Mix",
        "brand": "Paulaner DE",
        "calories": 2,
        "protein": 0.0,
        "carbs": 0.4,
        "fats": 0.0,
        "serving_size": "330ml Dose",
        "serving_grams": 330,
        "category": "drinks",
        "country": "DE"
      },
      {
        "id": "de-drin-4",
        "name": "ESN Iso-Clear Whey Isolate Drink Fresh Peach",
        "brand": "ESN Elite Sports DE",
        "calories": 90,
        "protein": 21.0,
        "carbs": 0.5,
        "fats": 0.1,
        "serving_size": "1 Scoop (25g)",
        "serving_grams": 25,
        "category": "drinks",
        "country": "DE"
      },
      {
        "id": "de-drin-5",
        "name": "Club-Mate Original Koffeinhaltiges Erfrischungsgetränk",
        "brand": "Brauerei Loscher DE",
        "calories": 66,
        "protein": 0.0,
        "carbs": 16.5,
        "fats": 0.0,
        "serving_size": "330ml Flasche",
        "serving_grams": 330,
        "category": "drinks",
        "country": "DE"
      },
      {
        "id": "de-drin-6",
        "name": "Alpro Mandelmilch Ungesüßt 100% Pflanzlich",
        "brand": "Alpro DE",
        "calories": 32,
        "protein": 1.0,
        "carbs": 0.5,
        "fats": 2.8,
        "serving_size": "250ml Glas",
        "serving_grams": 250,
        "category": "drinks",
        "country": "DE"
      }
    ]
  },
  "FR": {
    "protein": [
      {
        "id": "fr-prot-1",
        "name": "Filet de Poulet Blanc Fermier Français Cuit",
        "brand": "Le Gaulois FR",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g cuit",
        "serving_grams": 100,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-2",
        "name": "Fromage Blanc 0% de Matière Grasse Calin",
        "brand": "Yoplait FR",
        "calories": 50,
        "protein": 8.0,
        "carbs": 4.0,
        "fats": 0.1,
        "serving_size": "100g portion",
        "serving_grams": 100,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-3",
        "name": "Steak Haché Pur Boeuf 5% MG Charal",
        "brand": "Charal FR",
        "calories": 130,
        "protein": 23.0,
        "carbs": 0.0,
        "fats": 5.0,
        "serving_size": "1 steak (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-4",
        "name": "Pavé de Saumon Frais Atlantique Label Rouge",
        "brand": "Poissonnier FR",
        "calories": 205,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 13.0,
        "serving_size": "100g pavé",
        "serving_grams": 100,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-5",
        "name": "Thon au Naturel Petit Navire en Boîte",
        "brand": "Petit Navire FR",
        "calories": 115,
        "protein": 27.0,
        "carbs": 0.0,
        "fats": 0.8,
        "serving_size": "1 boite (130g)",
        "serving_grams": 130,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-6",
        "name": "Oeufs Bio Plein Air Gros Calibre (2 oeufs)",
        "brand": "Matines Bio FR",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 oeufs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-7",
        "name": "Jambon Blanc Supérieur Cuit à l'Étouffée",
        "brand": "Fleury Michon FR",
        "calories": 98,
        "protein": 18.0,
        "carbs": 1.0,
        "fats": 2.5,
        "serving_size": "2 tranches (80g)",
        "serving_grams": 80,
        "category": "protein",
        "country": "FR"
      },
      {
        "id": "fr-prot-8",
        "name": "Crevettes Roses Cuites Décortiquées",
        "brand": "Pêche Océan FR",
        "calories": 90,
        "protein": 20.0,
        "carbs": 0.5,
        "fats": 1.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "FR"
      }
    ],
    "carbs": [
      {
        "id": "fr-carb-1",
        "name": "Baguette de Tradition Française Artisanale",
        "brand": "Boulangerie FR",
        "calories": 270,
        "protein": 9.0,
        "carbs": 56.0,
        "fats": 1.0,
        "serving_size": "1/2 baguette (125g)",
        "serving_grams": 125,
        "category": "carbs",
        "country": "FR"
      },
      {
        "id": "fr-carb-2",
        "name": "Flocons d'Avoine Complète Bio",
        "brand": "Bjorg FR",
        "calories": 145,
        "protein": 5.2,
        "carbs": 25.0,
        "fats": 2.8,
        "serving_size": "40g portion",
        "serving_grams": 40,
        "category": "carbs",
        "country": "FR"
      },
      {
        "id": "fr-carb-3",
        "name": "Riz Basmati Blanc Parfumé Lustucru",
        "brand": "Lustucru FR",
        "calories": 170,
        "protein": 3.5,
        "carbs": 36.5,
        "fats": 0.8,
        "serving_size": "100g cuit",
        "serving_grams": 100,
        "category": "carbs",
        "country": "FR"
      },
      {
        "id": "fr-carb-4",
        "name": "Pommes de Terre Françaises Vapeur",
        "brand": "Producteur FR",
        "calories": 75,
        "protein": 2.0,
        "carbs": 16.5,
        "fats": 0.1,
        "serving_size": "100g cuites",
        "serving_grams": 100,
        "category": "carbs",
        "country": "FR"
      },
      {
        "id": "fr-carb-5",
        "name": "Lentilles Vertes du Puy AOP Cuites",
        "brand": "SABAROT FR",
        "calories": 115,
        "protein": 9.0,
        "carbs": 16.5,
        "fats": 0.6,
        "serving_size": "100g cuites",
        "serving_grams": 100,
        "category": "carbs",
        "country": "FR"
      },
      {
        "id": "fr-carb-6",
        "name": "Patate Douce Bio Rôtie au Four",
        "brand": "Bio FR",
        "calories": 90,
        "protein": 1.6,
        "carbs": 21.0,
        "fats": 0.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "FR"
      }
    ],
    "fats": [
      {
        "id": "fr-fats-1",
        "name": "Huile d'Olive Vierge Extra Première Pression Puget",
        "brand": "Puget FR",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 c. à soupe (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "FR"
      },
      {
        "id": "fr-fats-2",
        "name": "Beurre Doux Gastronomique Président",
        "brand": "Président FR",
        "calories": 108,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 12.0,
        "serving_size": "1 portion (15g)",
        "serving_grams": 15,
        "category": "fats",
        "country": "FR"
      },
      {
        "id": "fr-fats-3",
        "name": "Purée de Cacahuète 100% Bio Jean Hervé",
        "brand": "Jean Hervé FR",
        "calories": 185,
        "protein": 8.5,
        "carbs": 4.0,
        "fats": 15.5,
        "serving_size": "30g portion",
        "serving_grams": 30,
        "category": "fats",
        "country": "FR"
      },
      {
        "id": "fr-fats-4",
        "name": "Noix de Grenoble AOP Décortiquées",
        "brand": "Terroir FR",
        "calories": 200,
        "protein": 4.5,
        "carbs": 3.5,
        "fats": 20.0,
        "serving_size": "30g poignée",
        "serving_grams": 30,
        "category": "fats",
        "country": "FR"
      },
      {
        "id": "fr-fats-5",
        "name": "Avocat Hass Frais Prêt à Consommer",
        "brand": "Marché FR",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocat (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "FR"
      }
    ],
    "fastfood": [
      {
        "id": "fr-fast-1",
        "name": "Sandwich Jambon-Beurre Traditionnel Parisien",
        "brand": "Boulangerie FR",
        "calories": 440,
        "protein": 21.0,
        "carbs": 52.0,
        "fats": 16.0,
        "serving_size": "1 sandwich (210g)",
        "serving_grams": 210,
        "category": "fastfood",
        "country": "FR"
      },
      {
        "id": "fr-fast-2",
        "name": "Crêpe Salée Complète Jambon Oeuf Fromage",
        "brand": "Crêperie Bretonne",
        "calories": 360,
        "protein": 20.0,
        "carbs": 28.0,
        "fats": 18.0,
        "serving_size": "1 galette (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "FR"
      },
      {
        "id": "fr-fast-3",
        "name": "Croque-Monsieur Traditionnel au Four",
        "brand": "Brasserie FR",
        "calories": 420,
        "protein": 22.0,
        "carbs": 34.0,
        "fats": 22.0,
        "serving_size": "1 pièce (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "FR"
      },
      {
        "id": "fr-fast-4",
        "name": "Quiche Lorraine Traditionnelle aux Lardons",
        "brand": "Traiteur FR",
        "calories": 380,
        "protein": 12.5,
        "carbs": 24.0,
        "fats": 26.0,
        "serving_size": "1 part (160g)",
        "serving_grams": 160,
        "category": "fastfood",
        "country": "FR"
      },
      {
        "id": "fr-fast-5",
        "name": "O'Tacos French Tacos Poulet Sauce Fromagère M",
        "brand": "O'Tacos FR",
        "calories": 690,
        "protein": 36.0,
        "carbs": 68.0,
        "fats": 31.0,
        "serving_size": "Tacos M (330g)",
        "serving_grams": 330,
        "category": "fastfood",
        "country": "FR"
      }
    ],
    "drinks": [
      {
        "id": "fr-drin-1",
        "name": "Perrier Eau Minérale Gazeuse Naturelle",
        "brand": "Perrier FR",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "330ml bouteille",
        "serving_grams": 330,
        "category": "drinks",
        "country": "FR"
      },
      {
        "id": "fr-drin-2",
        "name": "Evian Eau Minérale Naturelle des Alpes",
        "brand": "Evian FR",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bouteille",
        "serving_grams": 500,
        "category": "drinks",
        "country": "FR"
      },
      {
        "id": "fr-drin-3",
        "name": "Orangina Sanguine Zéro Sucres Ajoutés",
        "brand": "Orangina FR",
        "calories": 5,
        "protein": 0.0,
        "carbs": 1.0,
        "fats": 0.0,
        "serving_size": "330ml canette",
        "serving_grams": 330,
        "category": "drinks",
        "country": "FR"
      },
      {
        "id": "fr-drin-4",
        "name": "Innocent Jus d'Orange Pressé Sans Pulpe",
        "brand": "Innocent FR",
        "calories": 105,
        "protein": 1.8,
        "carbs": 24.0,
        "fats": 0.2,
        "serving_size": "250ml verre",
        "serving_grams": 250,
        "category": "drinks",
        "country": "FR"
      },
      {
        "id": "fr-drin-5",
        "name": "Café Expresso Court Pur Arabica sans sucre",
        "brand": "Café Français",
        "calories": 2,
        "protein": 0.2,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 tasse (40ml)",
        "serving_grams": 40,
        "category": "drinks",
        "country": "FR"
      }
    ]
  },
  "IT": {
    "protein": [
      {
        "id": "it-prot-1",
        "name": "Bresaola della Valtellina IGP Magra",
        "brand": "Rigamonti IT",
        "calories": 150,
        "protein": 32.0,
        "carbs": 0.0,
        "fats": 2.5,
        "serving_size": "100g fette",
        "serving_grams": 100,
        "category": "protein",
        "country": "IT"
      },
      {
        "id": "it-prot-2",
        "name": "Petto di Pollo Grigliato alle Erbe",
        "brand": "Aia IT",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "IT"
      },
      {
        "id": "it-prot-3",
        "name": "Parmigiano Reggiano DOP Stagionato 24 Mesi",
        "brand": "Consorzio Parmigiano",
        "calories": 195,
        "protein": 16.5,
        "carbs": 0.0,
        "fats": 14.5,
        "serving_size": "50g scaglie",
        "serving_grams": 50,
        "category": "protein",
        "country": "IT"
      },
      {
        "id": "it-prot-4",
        "name": "Tonno all'Olio d'Oliva Pescato a Canna",
        "brand": "Rio Mare IT",
        "calories": 180,
        "protein": 25.0,
        "carbs": 0.0,
        "fats": 9.0,
        "serving_size": "1 scatoletta (80g)",
        "serving_grams": 80,
        "category": "protein",
        "country": "IT"
      },
      {
        "id": "it-prot-5",
        "name": "Prosciutto Crudo di Parma DOP Sgrassato",
        "brand": "Parma DOP IT",
        "calories": 160,
        "protein": 28.0,
        "carbs": 0.0,
        "fats": 5.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "IT"
      },
      {
        "id": "it-prot-6",
        "name": "Ricotta Vaccina Fresca Santa Lucia Light",
        "brand": "Galbani IT",
        "calories": 115,
        "protein": 9.5,
        "carbs": 4.0,
        "fats": 6.8,
        "serving_size": "100g porzione",
        "serving_grams": 100,
        "category": "protein",
        "country": "IT"
      },
      {
        "id": "it-prot-7",
        "name": "Filetto di Spigola Branzino Grigliato",
        "brand": "Pescheria IT",
        "calories": 115,
        "protein": 23.0,
        "carbs": 0.0,
        "fats": 2.5,
        "serving_size": "100g filetto",
        "serving_grams": 100,
        "category": "protein",
        "country": "IT"
      }
    ],
    "carbs": [
      {
        "id": "it-carb-1",
        "name": "Pasta Integrale Barilla Penne Rigate",
        "brand": "Barilla IT",
        "calories": 175,
        "protein": 6.5,
        "carbs": 33.0,
        "fats": 1.3,
        "serving_size": "50g a crudo",
        "serving_grams": 50,
        "category": "carbs",
        "country": "IT"
      },
      {
        "id": "it-carb-2",
        "name": "Riso Carnaroli Scotti per Risotto",
        "brand": "Riso Scotti IT",
        "calories": 175,
        "protein": 3.5,
        "carbs": 38.0,
        "fats": 0.5,
        "serving_size": "50g a crudo",
        "serving_grams": 50,
        "category": "carbs",
        "country": "IT"
      },
      {
        "id": "it-carb-3",
        "name": "Pane Casereccio di Genzano IGP a Fette",
        "brand": "Forno Tradizionale IT",
        "calories": 180,
        "protein": 6.5,
        "carbs": 36.0,
        "fats": 1.2,
        "serving_size": "2 fette (75g)",
        "serving_grams": 75,
        "category": "carbs",
        "country": "IT"
      },
      {
        "id": "it-carb-4",
        "name": "Gnocchi di Patate Freschi Giovanni Rana",
        "brand": "Giovanni Rana IT",
        "calories": 160,
        "protein": 4.5,
        "carbs": 33.0,
        "fats": 0.8,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "carbs",
        "country": "IT"
      },
      {
        "id": "it-carb-5",
        "name": "Polenta Gialla Tradizionale Valsugana",
        "brand": "Valsugana IT",
        "calories": 110,
        "protein": 2.5,
        "carbs": 24.0,
        "fats": 0.5,
        "serving_size": "100g cotta",
        "serving_grams": 100,
        "category": "carbs",
        "country": "IT"
      }
    ],
    "fats": [
      {
        "id": "it-fats-1",
        "name": "Olio Extra Vergine di Oliva Monini Classico",
        "brand": "Monini IT",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 cucchiaio (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "IT"
      },
      {
        "id": "it-fats-2",
        "name": "Noci Secche di Sorrento Sgusciate",
        "brand": "Frutta Secca IT",
        "calories": 198,
        "protein": 4.5,
        "carbs": 3.8,
        "fats": 19.5,
        "serving_size": "30g porzione",
        "serving_grams": 30,
        "category": "fats",
        "country": "IT"
      },
      {
        "id": "it-fats-3",
        "name": "Mandorle Pelate di Sicilia Tostate",
        "brand": "Sicilia Frutta IT",
        "calories": 175,
        "protein": 6.5,
        "carbs": 5.5,
        "fats": 15.0,
        "serving_size": "30g porzione",
        "serving_grams": 30,
        "category": "fats",
        "country": "IT"
      },
      {
        "id": "it-fats-4",
        "name": "Pesto alla Genovese Fresco con Basilico DOP",
        "brand": "Giovanni Rana IT",
        "calories": 145,
        "protein": 2.0,
        "carbs": 2.5,
        "fats": 14.5,
        "serving_size": "30g cucchiaio",
        "serving_grams": 30,
        "category": "fats",
        "country": "IT"
      }
    ],
    "fastfood": [
      {
        "id": "it-fast-1",
        "name": "Pizza Margherita al Taglio da Forno a Legna",
        "brand": "Pizzeria Romana IT",
        "calories": 480,
        "protein": 20.0,
        "carbs": 62.0,
        "fats": 16.0,
        "serving_size": "1 trancio (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "IT"
      },
      {
        "id": "it-fast-2",
        "name": "Piadina Romagnola con Prosciutto Crudo e Rucola",
        "brand": "Chiosco Piadina IT",
        "calories": 440,
        "protein": 22.0,
        "carbs": 48.0,
        "fats": 17.0,
        "serving_size": "1 piadina (190g)",
        "serving_grams": 190,
        "category": "fastfood",
        "country": "IT"
      },
      {
        "id": "it-fast-3",
        "name": "Panino con Porchetta d'Ariccia Calda",
        "brand": "Paninoteca IT",
        "calories": 460,
        "protein": 26.0,
        "carbs": 42.0,
        "fats": 20.0,
        "serving_size": "1 panino (200g)",
        "serving_grams": 200,
        "category": "fastfood",
        "country": "IT"
      },
      {
        "id": "it-fast-4",
        "name": "Arancino di Riso Siciliano al Ragù al Forno",
        "brand": "Tavola Calda IT",
        "calories": 340,
        "protein": 11.0,
        "carbs": 44.0,
        "fats": 13.0,
        "serving_size": "1 pezzo (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "IT"
      }
    ],
    "drinks": [
      {
        "id": "it-drin-1",
        "name": "San Pellegrino Acqua Minerale Frizzante",
        "brand": "San Pellegrino IT",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml bottiglia",
        "serving_grams": 500,
        "category": "drinks",
        "country": "IT"
      },
      {
        "id": "it-drin-2",
        "name": "Espresso Bar Tradizionale Italiano",
        "brand": "Illy / Lavazza IT",
        "calories": 2,
        "protein": 0.2,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 tazzina (30ml)",
        "serving_grams": 30,
        "category": "drinks",
        "country": "IT"
      },
      {
        "id": "it-drin-3",
        "name": "Chinotto Neri Analcolico Tradizionale",
        "brand": "Neri IT",
        "calories": 110,
        "protein": 0.0,
        "carbs": 28.0,
        "fats": 0.0,
        "serving_size": "200ml bottiglietta",
        "serving_grams": 200,
        "category": "drinks",
        "country": "IT"
      },
      {
        "id": "it-drin-4",
        "name": "San Benedetto Tè al Limone Zero Zucchero",
        "brand": "San Benedetto IT",
        "calories": 2,
        "protein": 0.0,
        "carbs": 0.4,
        "fats": 0.0,
        "serving_size": "330ml lattina",
        "serving_grams": 330,
        "category": "drinks",
        "country": "IT"
      }
    ]
  },
  "ES": {
    "protein": [
      {
        "id": "es-prot-1",
        "name": "Jamón Ibérico de Bellota 100% Loncheado",
        "brand": "Cinco Jotas ES",
        "calories": 175,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 9.0,
        "serving_size": "60g ración",
        "serving_grams": 60,
        "category": "protein",
        "country": "ES"
      },
      {
        "id": "es-prot-2",
        "name": "Pechuga de Pollo Corral Fresca Hacendado",
        "brand": "Mercadona ES",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g cocinada",
        "serving_grams": 100,
        "category": "protein",
        "country": "ES"
      },
      {
        "id": "es-prot-3",
        "name": "Solomillo de Ternera Gallega Magro",
        "brand": "Ternera Gallega ES",
        "calories": 155,
        "protein": 27.0,
        "carbs": 0.0,
        "fats": 5.0,
        "serving_size": "100g filete",
        "serving_grams": 100,
        "category": "protein",
        "country": "ES"
      },
      {
        "id": "es-prot-4",
        "name": "Atún Claro Calvo al Natural en Lata",
        "brand": "Calvo ES",
        "calories": 105,
        "protein": 25.0,
        "carbs": 0.0,
        "fats": 0.8,
        "serving_size": "1 lata (112g)",
        "serving_grams": 112,
        "category": "protein",
        "country": "ES"
      },
      {
        "id": "es-prot-5",
        "name": "Queso Fresco Desnatado 0% Burgo de Arias",
        "brand": "Burgo de Arias ES",
        "calories": 68,
        "protein": 12.0,
        "carbs": 3.5,
        "fats": 0.5,
        "serving_size": "100g porción",
        "serving_grams": 100,
        "category": "protein",
        "country": "ES"
      },
      {
        "id": "es-prot-6",
        "name": "Huevos Camperos Clase L (2 huevos)",
        "brand": "Hacendado ES",
        "calories": 145,
        "protein": 13.0,
        "carbs": 0.8,
        "fats": 10.0,
        "serving_size": "2 huevos (110g)",
        "serving_grams": 110,
        "category": "protein",
        "country": "ES"
      },
      {
        "id": "es-prot-7",
        "name": "Pulpo Cocido a la Gallega Cortado",
        "brand": "Lonja de Galicia ES",
        "calories": 95,
        "protein": 20.0,
        "carbs": 0.5,
        "fats": 1.2,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "ES"
      }
    ],
    "carbs": [
      {
        "id": "es-carb-1",
        "name": "Arroz Bomba SOS para Paella Tradicional",
        "brand": "SOS Arroz ES",
        "calories": 175,
        "protein": 3.8,
        "carbs": 38.0,
        "fats": 0.5,
        "serving_size": "50g en crudo",
        "serving_grams": 50,
        "category": "carbs",
        "country": "ES"
      },
      {
        "id": "es-carb-2",
        "name": "Pan Rústico de Masa Madre Gallego",
        "brand": "Panadería ES",
        "calories": 190,
        "protein": 7.0,
        "carbs": 38.0,
        "fats": 1.2,
        "serving_size": "2 rebanadas (80g)",
        "serving_grams": 80,
        "category": "carbs",
        "country": "ES"
      },
      {
        "id": "es-carb-3",
        "name": "Copos de Avena Integral Suaves Hacendado",
        "brand": "Mercadona ES",
        "calories": 145,
        "protein": 5.0,
        "carbs": 26.0,
        "fats": 2.5,
        "serving_size": "40g ración",
        "serving_grams": 40,
        "category": "carbs",
        "country": "ES"
      },
      {
        "id": "es-carb-4",
        "name": "Patatas Nuevas Gallegas Cocidas",
        "brand": "Patata Gallega ES",
        "calories": 78,
        "protein": 2.1,
        "carbs": 17.0,
        "fats": 0.1,
        "serving_size": "100g cocidas",
        "serving_grams": 100,
        "category": "carbs",
        "country": "ES"
      },
      {
        "id": "es-carb-5",
        "name": "Garbanzos Cocidos Luengo Selección Extra",
        "brand": "Luengo ES",
        "calories": 120,
        "protein": 7.5,
        "carbs": 18.0,
        "fats": 2.0,
        "serving_size": "100g escurridos",
        "serving_grams": 100,
        "category": "carbs",
        "country": "ES"
      }
    ],
    "fats": [
      {
        "id": "es-fats-1",
        "name": "Aceite de Oliva Virgen Extra Carbonell Gran Selección",
        "brand": "Carbonell ES",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 cucharada (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "ES"
      },
      {
        "id": "es-fats-2",
        "name": "Almendras Marconas Fritas con Sal",
        "brand": "Borges ES",
        "calories": 190,
        "protein": 6.0,
        "carbs": 4.0,
        "fats": 17.0,
        "serving_size": "30g ración",
        "serving_grams": 30,
        "category": "fats",
        "country": "ES"
      },
      {
        "id": "es-fats-3",
        "name": "Aguacate de la Axarquía Malagueña",
        "brand": "Axarquía ES",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 aguacate (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "ES"
      },
      {
        "id": "es-fats-4",
        "name": "Nueces Selección del País Hacendado",
        "brand": "Mercadona ES",
        "calories": 195,
        "protein": 4.5,
        "carbs": 4.0,
        "fats": 19.5,
        "serving_size": "30g puñado",
        "serving_grams": 30,
        "category": "fats",
        "country": "ES"
      }
    ],
    "fastfood": [
      {
        "id": "es-fast-1",
        "name": "Bocadillo de Jamón Serrano con Tomate Rallado",
        "brand": "Bar Español",
        "calories": 420,
        "protein": 24.0,
        "carbs": 52.0,
        "fats": 13.0,
        "serving_size": "1 bocadillo (220g)",
        "serving_grams": 220,
        "category": "fastfood",
        "country": "ES"
      },
      {
        "id": "es-fast-2",
        "name": "Pincho de Tortilla de Patatas Casera",
        "brand": "Taberna ES",
        "calories": 280,
        "protein": 8.5,
        "carbs": 24.0,
        "fats": 16.5,
        "serving_size": "1 pincho (160g)",
        "serving_grams": 160,
        "category": "fastfood",
        "country": "ES"
      },
      {
        "id": "es-fast-3",
        "name": "Croquetas Caseras de Jamón Ibérico (3 unidades)",
        "brand": "Tapas ES",
        "calories": 240,
        "protein": 9.0,
        "carbs": 22.0,
        "fats": 13.0,
        "serving_size": "3 croquetas (120g)",
        "serving_grams": 120,
        "category": "fastfood",
        "country": "ES"
      },
      {
        "id": "es-fast-4",
        "name": "Montadito de Pollo con Pimientos 100 Montaditos",
        "brand": "100 Montaditos ES",
        "calories": 185,
        "protein": 11.0,
        "carbs": 22.0,
        "fats": 5.5,
        "serving_size": "1 montadito (85g)",
        "serving_grams": 85,
        "category": "fastfood",
        "country": "ES"
      }
    ],
    "drinks": [
      {
        "id": "es-drin-1",
        "name": "Gazpacho Fresco Tradicional Alvalle",
        "brand": "Alvalle ES",
        "calories": 85,
        "protein": 2.0,
        "carbs": 8.0,
        "fats": 5.0,
        "serving_size": "200ml vaso",
        "serving_grams": 200,
        "category": "drinks",
        "country": "ES"
      },
      {
        "id": "es-drin-2",
        "name": "Zumo de Naranja Recién Exprimido 100%",
        "brand": "Mercadona ES",
        "calories": 105,
        "protein": 1.8,
        "carbs": 24.0,
        "fats": 0.2,
        "serving_size": "250ml vaso",
        "serving_grams": 250,
        "category": "drinks",
        "country": "ES"
      },
      {
        "id": "es-drin-3",
        "name": "Agua Mineral Natural con Gas Vichy Catalán",
        "brand": "Vichy Catalán ES",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml botella",
        "serving_grams": 500,
        "category": "drinks",
        "country": "ES"
      },
      {
        "id": "es-drin-4",
        "name": "Aquarius Limón Zero Azúcar Bebida Isotónica",
        "brand": "Coca-Cola ES",
        "calories": 4,
        "protein": 0.0,
        "carbs": 0.8,
        "fats": 0.0,
        "serving_size": "330ml lata",
        "serving_grams": 330,
        "category": "drinks",
        "country": "ES"
      }
    ]
  },
  "NL": {
    "protein": [
      {
        "id": "nl-prot-1",
        "name": "Mager Franse Kwark Zuivelhoeve (0% Vet)",
        "brand": "Albert Heijn NL",
        "calories": 52,
        "protein": 9.0,
        "carbs": 4.0,
        "fats": 0.1,
        "serving_size": "100g portie",
        "serving_grams": 100,
        "category": "protein",
        "country": "NL"
      },
      {
        "id": "nl-prot-2",
        "name": "XXL Nutrition Delicious Whey Protein Isolate",
        "brand": "XXL Nutrition NL",
        "calories": 112,
        "protein": 25.5,
        "carbs": 1.2,
        "fats": 0.6,
        "serving_size": "1 maatschep (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "NL"
      },
      {
        "id": "nl-prot-3",
        "name": "Biologische Kipfilet Vers Albert Heijn",
        "brand": "Albert Heijn NL",
        "calories": 160,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.5,
        "serving_size": "100g gebakken",
        "serving_grams": 100,
        "category": "protein",
        "country": "NL"
      },
      {
        "id": "nl-prot-4",
        "name": "Hollandse Nieuwe Haring met Uitjes (1 haring)",
        "brand": "Visboer NL",
        "calories": 170,
        "protein": 14.5,
        "carbs": 0.5,
        "fats": 12.5,
        "serving_size": "1 haring (80g)",
        "serving_grams": 80,
        "category": "protein",
        "country": "NL"
      },
      {
        "id": "nl-prot-5",
        "name": "Mager Rundergehakt 100% Rundvlees",
        "brand": "Jumbo NL",
        "calories": 155,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 7.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "NL"
      },
      {
        "id": "nl-prot-6",
        "name": "Verse Scharreleieren Beter Leven (2 eieren)",
        "brand": "Beter Leven NL",
        "calories": 140,
        "protein": 12.5,
        "carbs": 0.8,
        "fats": 9.8,
        "serving_size": "2 eieren (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "NL"
      },
      {
        "id": "nl-prot-7",
        "name": "Hüttenkäse Cottage Cheese Danone",
        "brand": "Danone NL",
        "calories": 92,
        "protein": 12.5,
        "carbs": 2.5,
        "fats": 3.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "NL"
      }
    ],
    "carbs": [
      {
        "id": "nl-carb-1",
        "name": "Quaker Havermout 100% Volle Granen",
        "brand": "Quaker NL",
        "calories": 145,
        "protein": 5.0,
        "carbs": 26.0,
        "fats": 2.5,
        "serving_size": "40g portie",
        "serving_grams": 40,
        "category": "carbs",
        "country": "NL"
      },
      {
        "id": "nl-carb-2",
        "name": "Albert Heijn Liefde & Passie Volkorenbrood",
        "brand": "Albert Heijn NL",
        "calories": 170,
        "protein": 7.5,
        "carbs": 29.0,
        "fats": 2.0,
        "serving_size": "2 boterhammen (70g)",
        "serving_grams": 70,
        "category": "carbs",
        "country": "NL"
      },
      {
        "id": "nl-carb-3",
        "name": "Kruimige Aardappelen Gekookt",
        "brand": "Aardappel NL",
        "calories": 75,
        "protein": 2.0,
        "carbs": 16.5,
        "fats": 0.1,
        "serving_size": "100g gekookt",
        "serving_grams": 100,
        "category": "carbs",
        "country": "NL"
      },
      {
        "id": "nl-carb-4",
        "name": "Lassie Zilvervliesrijst Toverrijst",
        "brand": "Lassie NL",
        "calories": 165,
        "protein": 3.8,
        "carbs": 35.0,
        "fats": 1.2,
        "serving_size": "100g gekookt",
        "serving_grams": 100,
        "category": "carbs",
        "country": "NL"
      },
      {
        "id": "nl-carb-5",
        "name": "Peijnenburg Ontbijtkoek Zero Zonder Toegevoegde Suiker",
        "brand": "Peijnenburg NL",
        "calories": 85,
        "protein": 1.5,
        "carbs": 22.0,
        "fats": 0.5,
        "serving_size": "1 plak (35g)",
        "serving_grams": 35,
        "category": "carbs",
        "country": "NL"
      }
    ],
    "fats": [
      {
        "id": "nl-fats-1",
        "name": "Calvé Pindakaas 100% Pinda's Zonder Toevoegingen",
        "brand": "Calvé NL",
        "calories": 95,
        "protein": 4.2,
        "carbs": 2.0,
        "fats": 8.0,
        "serving_size": "1 eetlepel (16g)",
        "serving_grams": 16,
        "category": "fats",
        "country": "NL"
      },
      {
        "id": "nl-fats-2",
        "name": "Bertolli Extra Vierge Olijfolie Originale",
        "brand": "Bertolli NL",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 eetlepel (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "NL"
      },
      {
        "id": "nl-fats-3",
        "name": "Campina Echte Roomboter Ongezouten",
        "brand": "Campina NL",
        "calories": 108,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 12.0,
        "serving_size": "15g portie",
        "serving_grams": 15,
        "category": "fats",
        "country": "NL"
      },
      {
        "id": "nl-fats-4",
        "name": "Verse Eetrijpe Hass Avocado",
        "brand": "Jumbo NL",
        "calories": 160,
        "protein": 2.0,
        "carbs": 9.0,
        "fats": 15.0,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "NL"
      }
    ],
    "fastfood": [
      {
        "id": "nl-fast-1",
        "name": "Kwekkeboom Rundvleeskroket uit de Muur",
        "brand": "Kwekkeboom NL",
        "calories": 195,
        "protein": 8.5,
        "carbs": 17.0,
        "fats": 10.5,
        "serving_size": "1 kroket (85g)",
        "serving_grams": 85,
        "category": "fastfood",
        "country": "NL"
      },
      {
        "id": "nl-fast-2",
        "name": "Broodje Frikandel Speciaal (Curry & Uitjes)",
        "brand": "Snackbar NL",
        "calories": 320,
        "protein": 12.0,
        "carbs": 28.0,
        "fats": 18.0,
        "serving_size": "1 broodje (150g)",
        "serving_grams": 150,
        "category": "fastfood",
        "country": "NL"
      },
      {
        "id": "nl-fast-3",
        "name": "Verse Kibbeling met Remouladesaus (Kleine portie)",
        "brand": "Viskraam NL",
        "calories": 340,
        "protein": 22.0,
        "carbs": 18.0,
        "fats": 20.0,
        "serving_size": "1 bakje (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "NL"
      },
      {
        "id": "nl-fast-4",
        "name": "HEMA Verse Warme Rookworst Half",
        "brand": "HEMA NL",
        "calories": 360,
        "protein": 14.0,
        "carbs": 3.5,
        "fats": 32.0,
        "serving_size": "Halve worst (125g)",
        "serving_grams": 125,
        "category": "fastfood",
        "country": "NL"
      }
    ],
    "drinks": [
      {
        "id": "nl-drin-1",
        "name": "Chocomel De Enige Echte Halfvol Zonder Suiker",
        "brand": "FrieslandCampina NL",
        "calories": 110,
        "protein": 8.0,
        "carbs": 12.0,
        "fats": 3.2,
        "serving_size": "250ml glas",
        "serving_grams": 250,
        "category": "drinks",
        "country": "NL"
      },
      {
        "id": "nl-drin-2",
        "name": "Spa Blauw Mineraalwater Natuurlijk",
        "brand": "Spa Monopole NL",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "500ml fles",
        "serving_grams": 500,
        "category": "drinks",
        "country": "NL"
      },
      {
        "id": "nl-drin-3",
        "name": "DubbelFrisss Framboos & Cranberry 0% Suiker",
        "brand": "Riedel NL",
        "calories": 3,
        "protein": 0.0,
        "carbs": 0.5,
        "fats": 0.0,
        "serving_size": "250ml glas",
        "serving_grams": 250,
        "category": "drinks",
        "country": "NL"
      },
      {
        "id": "nl-drin-4",
        "name": "Verse Muntthee met Schijfje Citroen",
        "brand": "Café NL",
        "calories": 2,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "1 glas (250ml)",
        "serving_grams": 250,
        "category": "drinks",
        "country": "NL"
      }
    ]
  }
};
