import { RegionalFoodMap } from './types';

export const OCEANIA_FOODS: RegionalFoodMap = {
  "AU": {
    "protein": [
      {
        "id": "au-prot-1",
        "name": "Bulk Nutrients WPC Pure Whey",
        "brand": "Bulk Nutrients AU",
        "calories": 118,
        "protein": 24.0,
        "carbs": 1.8,
        "fats": 1.5,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-2",
        "name": "Aussie Bodies Shape Protein Bar",
        "brand": "Aussie Bodies",
        "calories": 180,
        "protein": 20.0,
        "carbs": 4.5,
        "fats": 5.2,
        "serving_size": "1 bar (50g)",
        "serving_grams": 50,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-3",
        "name": "Grilled RSPCA Chicken Breast Fillet",
        "brand": "Woolworths / Coles AU",
        "calories": 165,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.6,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-4",
        "name": "Macro Organic Kangaroo Fillet",
        "brand": "Macro Meats AU",
        "calories": 102,
        "protein": 22.5,
        "carbs": 0.0,
        "fats": 1.2,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-5",
        "name": "Fresh Tasmanian Salmon Fillet",
        "brand": "Tassal Salmon AU",
        "calories": 208,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 13.0,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-6",
        "name": "Chobani Fit High Protein Greek Yogurt",
        "brand": "Chobani AU",
        "calories": 95,
        "protein": 15.0,
        "carbs": 6.2,
        "fats": 0.2,
        "serving_size": "1 tub (160g)",
        "serving_grams": 160,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-7",
        "name": "YoPRO 15g Protein Yogurt Pot",
        "brand": "Danone YoPRO AU",
        "calories": 92,
        "protein": 15.0,
        "carbs": 5.4,
        "fats": 0.3,
        "serving_size": "1 tub (160g)",
        "serving_grams": 160,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-8",
        "name": "Sunny Queen Pure Liquid Egg Whites",
        "brand": "Sunny Queen AU",
        "calories": 52,
        "protein": 11.0,
        "carbs": 0.7,
        "fats": 0.2,
        "serving_size": "100ml",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-9",
        "name": "Woolworths Heart Smart 5-Star Beef Mince",
        "brand": "Woolworths Butcher AU",
        "calories": 130,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 4.8,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-10",
        "name": "Cone Bay Barramundi Fillet",
        "brand": "Humpty Doo AU",
        "calories": 112,
        "protein": 21.0,
        "carbs": 0.0,
        "fats": 2.5,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-11",
        "name": "Macro Organic Extra Firm Tofu",
        "brand": "Woolworths Macro AU",
        "calories": 125,
        "protein": 14.5,
        "carbs": 1.2,
        "fats": 7.0,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-12",
        "name": "Steggles Turkey Breast Steaks",
        "brand": "Steggles AU",
        "calories": 105,
        "protein": 24.0,
        "carbs": 0.0,
        "fats": 1.1,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-13",
        "name": "Australian Pasture-Fed Lamb Chops",
        "brand": "Coles Butcher AU",
        "calories": 220,
        "protein": 20.0,
        "carbs": 0.0,
        "fats": 15.5,
        "serving_size": "100g grilled",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-14",
        "name": "John West Tuna in Springwater",
        "brand": "John West AU",
        "calories": 109,
        "protein": 25.5,
        "carbs": 0.0,
        "fats": 0.8,
        "serving_size": "1 can (95g)",
        "serving_grams": 95,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-15",
        "name": "Coles Free Range Whole Eggs (2 eggs)",
        "brand": "Coles AU",
        "calories": 143,
        "protein": 12.6,
        "carbs": 0.8,
        "fats": 9.9,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-16",
        "name": "Musashi High Protein Bar 45g",
        "brand": "Musashi AU",
        "calories": 338,
        "protein": 45.5,
        "carbs": 2.6,
        "fats": 9.1,
        "serving_size": "1 bar (90g)",
        "serving_grams": 90,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-17",
        "name": "BSC Clean Pea Protein Vegan",
        "brand": "BodyScience AU",
        "calories": 120,
        "protein": 23.5,
        "carbs": 2.1,
        "fats": 1.8,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-18",
        "name": "Australian Tiger Prawns Boiled",
        "brand": "Sydney Fish Market",
        "calories": 99,
        "protein": 21.5,
        "carbs": 0.5,
        "fats": 1.1,
        "serving_size": "100g peeled",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-19",
        "name": "Primo Lean Shaved Ham 97% Fat Free",
        "brand": "Primo AU",
        "calories": 98,
        "protein": 17.5,
        "carbs": 1.2,
        "fats": 2.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      },
      {
        "id": "au-prot-20",
        "name": "Bega Country Light 50% Less Fat Cheese",
        "brand": "Bega Cheese AU",
        "calories": 260,
        "protein": 31.5,
        "carbs": 0.5,
        "fats": 14.5,
        "serving_size": "100g",
        "serving_grams": 100,
        "category": "protein",
        "country": "AU"
      }
    ],
    "carbs": [
      {
        "id": "au-carb-1",
        "name": "SunRice Microwave Brown Rice Cup",
        "brand": "SunRice AU",
        "calories": 175,
        "protein": 4.1,
        "carbs": 35.0,
        "fats": 1.9,
        "serving_size": "1 cup (125g)",
        "serving_grams": 125,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-2",
        "name": "Carman's 5-Grain Gourmet Porridge Oats",
        "brand": "Carman's AU",
        "calories": 160,
        "protein": 5.5,
        "carbs": 25.4,
        "fats": 3.2,
        "serving_size": "1 sachet (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-3",
        "name": "Spud Lite Lower Carb Brushed Potatoes",
        "brand": "Spud Lite AU",
        "calories": 50,
        "protein": 1.8,
        "carbs": 8.9,
        "fats": 0.1,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-4",
        "name": "Helga's Traditional White Sourdough",
        "brand": "Helga's AU",
        "calories": 185,
        "protein": 6.8,
        "carbs": 34.2,
        "fats": 1.8,
        "serving_size": "2 slices (82g)",
        "serving_grams": 82,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-5",
        "name": "Australian Golden Sweet Potato",
        "brand": "Woolworths Fresh AU",
        "calories": 86,
        "protein": 1.6,
        "carbs": 20.1,
        "fats": 0.1,
        "serving_size": "100g baked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-6",
        "name": "Macro Organic Tri-Colour Quinoa",
        "brand": "Woolworths Macro AU",
        "calories": 120,
        "protein": 4.4,
        "carbs": 21.3,
        "fats": 1.9,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-7",
        "name": "Australian Cavendish Fresh Banana",
        "brand": "Coles Fresh Produce",
        "calories": 105,
        "protein": 1.3,
        "carbs": 27.0,
        "fats": 0.3,
        "serving_size": "1 medium (118g)",
        "serving_grams": 118,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-8",
        "name": "Sanitarium Weet-Bix Original (2 biscuits)",
        "brand": "Sanitarium AU",
        "calories": 107,
        "protein": 3.7,
        "carbs": 20.1,
        "fats": 0.4,
        "serving_size": "2 biscuits (30g)",
        "serving_grams": 30,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-9",
        "name": "Golden Crumpets Original (2 pack)",
        "brand": "Golden AU",
        "calories": 196,
        "protein": 6.2,
        "carbs": 39.0,
        "fats": 0.8,
        "serving_size": "2 crumpets (100g)",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-10",
        "name": "Mission Wholegrain Wrap Tortilla",
        "brand": "Mission Foods AU",
        "calories": 137,
        "protein": 4.2,
        "carbs": 21.5,
        "fats": 3.1,
        "serving_size": "1 wrap (47g)",
        "serving_grams": 47,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-11",
        "name": "Barilla Penne Rigate Durum Wheat",
        "brand": "Barilla AU",
        "calories": 356,
        "protein": 12.5,
        "carbs": 71.2,
        "fats": 1.5,
        "serving_size": "100g dry",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-12",
        "name": "Uncle Tobys Traditional Rolled Oats",
        "brand": "Uncle Tobys AU",
        "calories": 152,
        "protein": 5.2,
        "carbs": 24.1,
        "fats": 3.4,
        "serving_size": "1 serve (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-13",
        "name": "Tip Top The One Wholemeal Bread",
        "brand": "Tip Top AU",
        "calories": 188,
        "protein": 7.8,
        "carbs": 31.0,
        "fats": 2.2,
        "serving_size": "2 slices (74g)",
        "serving_grams": 74,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-14",
        "name": "SunRice Australian Jasmine Fragrant Rice",
        "brand": "SunRice AU",
        "calories": 170,
        "protein": 3.2,
        "carbs": 37.5,
        "fats": 0.4,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-15",
        "name": "Coles Canned Black Beans in Brine",
        "brand": "Coles AU",
        "calories": 110,
        "protein": 8.2,
        "carbs": 14.5,
        "fats": 0.6,
        "serving_size": "130g drained",
        "serving_grams": 130,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-16",
        "name": "Fresh Australian Pink Lady Apple",
        "brand": "Woolworths Fresh AU",
        "calories": 72,
        "protein": 0.4,
        "carbs": 19.0,
        "fats": 0.2,
        "serving_size": "1 medium (150g)",
        "serving_grams": 150,
        "category": "carbs",
        "country": "AU"
      },
      {
        "id": "au-carb-17",
        "name": "Macro Organic Rolled Barley",
        "brand": "Macro AU",
        "calories": 145,
        "protein": 4.8,
        "carbs": 28.0,
        "fats": 1.1,
        "serving_size": "40g dry",
        "serving_grams": 40,
        "category": "carbs",
        "country": "AU"
      }
    ],
    "fats": [
      {
        "id": "au-fats-1",
        "name": "Cobram Estate Robust Extra Virgin Olive Oil",
        "brand": "Cobram Estate AU",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 13.8,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-2",
        "name": "Mayver's Smunchy 100% Pure Peanut Butter",
        "brand": "Mayver's AU",
        "calories": 95,
        "protein": 4.2,
        "carbs": 2.1,
        "fats": 7.8,
        "serving_size": "1 tbsp (16g)",
        "serving_grams": 16,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-3",
        "name": "Australian Shepard/Hass Avocado",
        "brand": "Woolworths Fresh AU",
        "calories": 160,
        "protein": 2.0,
        "carbs": 8.5,
        "fats": 14.7,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-4",
        "name": "Australian Raw Macadamia Halves",
        "brand": "Nutworks AU",
        "calories": 204,
        "protein": 2.2,
        "carbs": 3.9,
        "fats": 21.5,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-5",
        "name": "Macro Organic Raw Walnuts",
        "brand": "Macro Meats AU",
        "calories": 196,
        "protein": 4.5,
        "carbs": 4.1,
        "fats": 19.6,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-6",
        "name": "Lucky California Raw Almonds",
        "brand": "Lucky Nuts AU",
        "calories": 175,
        "protein": 6.3,
        "carbs": 5.8,
        "fats": 15.2,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-7",
        "name": "Melrose 100% MCT Oil Pro Brain Fuel",
        "brand": "Melrose Health AU",
        "calories": 125,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 14.0,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-8",
        "name": "Nuttelex Original Table Spread",
        "brand": "Nuttelex AU",
        "calories": 52,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 5.9,
        "serving_size": "10g portion",
        "serving_grams": 10,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-9",
        "name": "The Chia Co Black Australian Chia Seeds",
        "brand": "The Chia Co AU",
        "calories": 135,
        "protein": 4.9,
        "carbs": 1.1,
        "fats": 8.7,
        "serving_size": "1 tbsp (28g)",
        "serving_grams": 28,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-10",
        "name": "Lurpak Salted Dairy Butter",
        "brand": "Lurpak AU",
        "calories": 108,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 12.0,
        "serving_size": "1 pat (15g)",
        "serving_grams": 15,
        "category": "fats",
        "country": "AU"
      },
      {
        "id": "au-fats-11",
        "name": "Woolworths Natural Pumpkin Pepitas",
        "brand": "Woolworths AU",
        "calories": 168,
        "protein": 8.8,
        "carbs": 4.2,
        "fats": 14.1,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "AU"
      }
    ],
    "fastfood": [
      {
        "id": "au-fast-1",
        "name": "GYG Grilled Chicken Burrito Bowl (Brown Rice)",
        "brand": "Guzman y Gomez AU",
        "calories": 540,
        "protein": 42.0,
        "carbs": 58.0,
        "fats": 14.0,
        "serving_size": "1 bowl (420g)",
        "serving_grams": 420,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-2",
        "name": "GYG Shredded Beef Mild Taco (Hard Shell)",
        "brand": "Guzman y Gomez AU",
        "calories": 185,
        "protein": 12.5,
        "carbs": 14.0,
        "fats": 8.5,
        "serving_size": "1 taco (110g)",
        "serving_grams": 110,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-3",
        "name": "Grill'd Simply Grill'd Beef Burger (Low Carb Bun)",
        "brand": "Grill'd AU",
        "calories": 460,
        "protein": 36.0,
        "carbs": 12.8,
        "fats": 28.0,
        "serving_size": "1 burger (260g)",
        "serving_grams": 260,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-4",
        "name": "Grill'd Sweet Potato Chips with Herb Mayo",
        "brand": "Grill'd AU",
        "calories": 380,
        "protein": 4.2,
        "carbs": 48.0,
        "fats": 18.0,
        "serving_size": "Regular serve (160g)",
        "serving_grams": 160,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-5",
        "name": "Schnitz Classic Chicken Schnitzel Wrap",
        "brand": "Schnitz AU",
        "calories": 590,
        "protein": 38.0,
        "carbs": 52.0,
        "fats": 23.0,
        "serving_size": "1 wrap (340g)",
        "serving_grams": 340,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-6",
        "name": "Oporto Single Bondi Burger (Original Chilli)",
        "brand": "Oporto AU",
        "calories": 495,
        "protein": 31.0,
        "carbs": 46.0,
        "fats": 19.0,
        "serving_size": "1 burger (225g)",
        "serving_grams": 225,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-7",
        "name": "Subway 6-Inch Oven Roasted Chicken Breast Sub",
        "brand": "Subway AU",
        "calories": 310,
        "protein": 24.0,
        "carbs": 43.0,
        "fats": 4.5,
        "serving_size": "6-inch (230g)",
        "serving_grams": 230,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-8",
        "name": "McDonald's AU McChicken Burger",
        "brand": "McDonald's AU",
        "calories": 468,
        "protein": 21.8,
        "carbs": 45.4,
        "fats": 21.8,
        "serving_size": "1 burger (185g)",
        "serving_grams": 185,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-9",
        "name": "Red Rooster Roast Chicken 1/4 (Skin Off)",
        "brand": "Red Rooster AU",
        "calories": 260,
        "protein": 34.0,
        "carbs": 0.5,
        "fats": 13.0,
        "serving_size": "1 quarter (180g)",
        "serving_grams": 180,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-10",
        "name": "Zambrero Slow Cooked Pork Power Bowl",
        "brand": "Zambrero AU",
        "calories": 520,
        "protein": 38.0,
        "carbs": 46.0,
        "fats": 19.0,
        "serving_size": "1 bowl (400g)",
        "serving_grams": 400,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-11",
        "name": "Sushi Hub Salmon Avocado Hand Roll",
        "brand": "Sushi Hub AU",
        "calories": 182,
        "protein": 7.2,
        "carbs": 26.0,
        "fats": 4.8,
        "serving_size": "1 roll (110g)",
        "serving_grams": 110,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-12",
        "name": "Mad Mex Grilled Steak Naked Burrito",
        "brand": "Mad Mex AU",
        "calories": 490,
        "protein": 36.0,
        "carbs": 48.0,
        "fats": 16.0,
        "serving_size": "1 bowl (380g)",
        "serving_grams": 380,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-13",
        "name": "KFC Original Recipe Chicken Piece (Thigh)",
        "brand": "KFC AU",
        "calories": 280,
        "protein": 20.0,
        "carbs": 8.0,
        "fats": 18.0,
        "serving_size": "1 piece (115g)",
        "serving_grams": 115,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-14",
        "name": "KFC Zinger Burger",
        "brand": "KFC AU",
        "calories": 510,
        "protein": 28.0,
        "carbs": 48.0,
        "fats": 22.0,
        "serving_size": "1 burger (210g)",
        "serving_grams": 210,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-15",
        "name": "KFC Original Recipe Popcorn Chicken Regular",
        "brand": "KFC AU",
        "calories": 430,
        "protein": 24.0,
        "carbs": 26.0,
        "fats": 25.0,
        "serving_size": "Regular box (130g)",
        "serving_grams": 130,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-16",
        "name": "Hungry Jack's Whopper",
        "brand": "Hungry Jack's AU",
        "calories": 670,
        "protein": 29.0,
        "carbs": 50.0,
        "fats": 38.0,
        "serving_size": "1 burger (290g)",
        "serving_grams": 290,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-17",
        "name": "Hungry Jack's Grilled Chicken Burger",
        "brand": "Hungry Jack's AU",
        "calories": 430,
        "protein": 32.0,
        "carbs": 41.0,
        "fats": 14.0,
        "serving_size": "1 burger (210g)",
        "serving_grams": 210,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-18",
        "name": "McDonald's AU Big Mac",
        "brand": "McDonald's AU",
        "calories": 563,
        "protein": 26.0,
        "carbs": 44.0,
        "fats": 31.0,
        "serving_size": "1 burger (219g)",
        "serving_grams": 219,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-19",
        "name": "McDonald's AU Chicken McNuggets (6 piece)",
        "brand": "McDonald's AU",
        "calories": 250,
        "protein": 14.0,
        "carbs": 15.0,
        "fats": 15.0,
        "serving_size": "6 pcs (97g)",
        "serving_grams": 97,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-20",
        "name": "Nando's 1/4 Chicken Lemon & Herb (No Chips)",
        "brand": "Nando's AU",
        "calories": 250,
        "protein": 32.0,
        "carbs": 1.0,
        "fats": 13.0,
        "serving_size": "1/4 bird (170g)",
        "serving_grams": 170,
        "category": "fastfood",
        "country": "AU"
      },
      {
        "id": "au-fast-21",
        "name": "GYG Chicken Burrito (No Cheese, Extra Veg)",
        "brand": "Guzman y Gomez AU",
        "calories": 620,
        "protein": 42.0,
        "carbs": 58.0,
        "fats": 22.0,
        "serving_size": "1 burrito (430g)",
        "serving_grams": 430,
        "category": "fastfood",
        "country": "AU"
      }
    ],
    "drinks": [
      {
        "id": "au-drin-1",
        "name": "Oak Light Chocolate Flavoured Milk",
        "brand": "Parmalat Oak AU",
        "calories": 145,
        "protein": 11.2,
        "carbs": 18.5,
        "fats": 2.5,
        "serving_size": "300ml bottle",
        "serving_grams": 300,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-2",
        "name": "Sanitarium Up & Go Liquid Breakfast Choc Ice",
        "brand": "Sanitarium AU",
        "calories": 195,
        "protein": 8.2,
        "carbs": 29.8,
        "fats": 3.8,
        "serving_size": "250ml tetra pack",
        "serving_grams": 250,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-3",
        "name": "Bundaberg Diet Ginger Beer (Zero Sugar)",
        "brand": "Bundaberg Brewed Drinks",
        "calories": 5,
        "protein": 0.0,
        "carbs": 1.2,
        "fats": 0.0,
        "serving_size": "1 bottle (375ml)",
        "serving_grams": 375,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-4",
        "name": "Rokeby Farms High Protein Vanilla Smoothie",
        "brand": "Rokeby Farms AU",
        "calories": 220,
        "protein": 30.0,
        "carbs": 16.0,
        "fats": 2.8,
        "serving_size": "425ml bottle",
        "serving_grams": 425,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-5",
        "name": "Daily Juice Pulp Free Orange 100% Juice",
        "brand": "Daily Juice AU",
        "calories": 110,
        "protein": 1.8,
        "carbs": 24.0,
        "fats": 0.2,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-6",
        "name": "Hydralyte Electrolyte Effervescent Orange",
        "brand": "Hydralyte AU",
        "calories": 18,
        "protein": 0.0,
        "carbs": 3.8,
        "fats": 0.0,
        "serving_size": "1 tablet in 200ml",
        "serving_grams": 200,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-7",
        "name": "Dare Iced Coffee No Added Sugar 500ml",
        "brand": "Dare Iced Coffee AU",
        "calories": 195,
        "protein": 14.5,
        "carbs": 16.0,
        "fats": 7.5,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-8",
        "name": "H2Coco Pure Coconut Water 100%",
        "brand": "H2Coco AU",
        "calories": 65,
        "protein": 0.5,
        "carbs": 15.0,
        "fats": 0.0,
        "serving_size": "330ml carton",
        "serving_grams": 330,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-9",
        "name": "V Energy Blue Sugarfree Energy Drink",
        "brand": "Frucor V AU",
        "calories": 12,
        "protein": 0.4,
        "carbs": 1.8,
        "fats": 0.0,
        "serving_size": "250ml can",
        "serving_grams": 250,
        "category": "drinks",
        "country": "AU"
      },
      {
        "id": "au-drin-10",
        "name": "Maximus Sports Drink Red vs Blue",
        "brand": "Maximus AU",
        "calories": 120,
        "protein": 0.0,
        "carbs": 28.0,
        "fats": 0.0,
        "serving_size": "1 bottle (1000ml)",
        "serving_grams": 1000,
        "category": "drinks",
        "country": "AU"
      }
    ]
  },
  "NZ": {
    "protein": [
      {
        "id": "nz-prot-1",
        "name": "Anchor Protein+ Milk Chocolate 500ml",
        "brand": "Anchor NZ",
        "calories": 295,
        "protein": 30.0,
        "carbs": 26.0,
        "fats": 7.5,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-2",
        "name": "Tegel NZ Fresh Skinless Chicken Breast",
        "brand": "Tegel NZ",
        "calories": 165,
        "protein": 31.0,
        "carbs": 0.0,
        "fats": 3.6,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-3",
        "name": "Silver Fern Farms Beef Sirloin Steak",
        "brand": "Silver Fern Farms",
        "calories": 195,
        "protein": 27.0,
        "carbs": 0.0,
        "fats": 9.5,
        "serving_size": "100g grilled",
        "serving_grams": 100,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-4",
        "name": "Meadow Fresh Kalo Authentic Greek Yoghurt",
        "brand": "Meadow Fresh NZ",
        "calories": 105,
        "protein": 13.5,
        "carbs": 6.0,
        "fats": 2.5,
        "serving_size": "1 tub (150g)",
        "serving_grams": 150,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-5",
        "name": "Sealord Wild Alaskan Salmon Fillets",
        "brand": "Sealord NZ",
        "calories": 188,
        "protein": 22.0,
        "carbs": 0.0,
        "fats": 11.0,
        "serving_size": "1 fillet (120g)",
        "serving_grams": 120,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-6",
        "name": "Woodland Free Range Eggs Large (2 eggs)",
        "brand": "Woodland NZ",
        "calories": 145,
        "protein": 13.0,
        "carbs": 0.8,
        "fats": 10.0,
        "serving_size": "2 eggs (100g)",
        "serving_grams": 100,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-7",
        "name": "Sealord Tuna in Spring Water 185g",
        "brand": "Sealord NZ",
        "calories": 175,
        "protein": 41.0,
        "carbs": 0.0,
        "fats": 1.2,
        "serving_size": "1 can (185g)",
        "serving_grams": 185,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-8",
        "name": "Mainland Special Reserve Tasty Cheddar",
        "brand": "Mainland NZ",
        "calories": 205,
        "protein": 12.5,
        "carbs": 0.1,
        "fats": 17.0,
        "serving_size": "50g serve",
        "serving_grams": 50,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-9",
        "name": "Nothing Naughty Pure NZ Whey Isolate",
        "brand": "Nothing Naughty NZ",
        "calories": 116,
        "protein": 26.5,
        "carbs": 1.1,
        "fats": 0.8,
        "serving_size": "1 scoop (30g)",
        "serving_grams": 30,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-10",
        "name": "First Light Grass-Fed Venison Medallions",
        "brand": "First Light NZ",
        "calories": 120,
        "protein": 24.5,
        "carbs": 0.0,
        "fats": 2.0,
        "serving_size": "100g raw",
        "serving_grams": 100,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-11",
        "name": "Sanitarium So Good High Protein Soy Milk",
        "brand": "Sanitarium NZ",
        "calories": 130,
        "protein": 10.0,
        "carbs": 5.5,
        "fats": 7.5,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "protein",
        "country": "NZ"
      },
      {
        "id": "nz-prot-12",
        "name": "Moana New Zealand Green Shell Mussels",
        "brand": "Moana NZ",
        "calories": 86,
        "protein": 11.9,
        "carbs": 3.7,
        "fats": 2.2,
        "serving_size": "100g steamed",
        "serving_grams": 100,
        "category": "protein",
        "country": "NZ"
      }
    ],
    "carbs": [
      {
        "id": "nz-carb-1",
        "name": "Harraways Traditional NZ Rolled Oats",
        "brand": "Harraways NZ",
        "calories": 155,
        "protein": 5.4,
        "carbs": 25.0,
        "fats": 3.5,
        "serving_size": "1 serve (40g)",
        "serving_grams": 40,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-2",
        "name": "New Zealand Orange Kumara (Sweet Potato)",
        "brand": "Countdown NZ",
        "calories": 92,
        "protein": 1.8,
        "carbs": 21.0,
        "fats": 0.2,
        "serving_size": "100g roasted",
        "serving_grams": 100,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-3",
        "name": "Vogels Original Mixed Grain Bread",
        "brand": "Vogels NZ",
        "calories": 192,
        "protein": 9.4,
        "carbs": 30.2,
        "fats": 3.2,
        "serving_size": "2 slices (86g)",
        "serving_grams": 86,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-4",
        "name": "Sanitarium Weet-Bix Original NZ",
        "brand": "Sanitarium NZ",
        "calories": 107,
        "protein": 3.7,
        "carbs": 20.1,
        "fats": 0.4,
        "serving_size": "2 biscuits (30g)",
        "serving_grams": 30,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-5",
        "name": "New Zealand Agria Brushed Potatoes",
        "brand": "Pak'nSave Fresh",
        "calories": 75,
        "protein": 2.0,
        "carbs": 17.0,
        "fats": 0.1,
        "serving_size": "100g boiled",
        "serving_grams": 100,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-6",
        "name": "SunRice Long Grain White Rice",
        "brand": "SunRice NZ",
        "calories": 170,
        "protein": 3.2,
        "carbs": 37.5,
        "fats": 0.4,
        "serving_size": "100g cooked",
        "serving_grams": 100,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-7",
        "name": "Pure New Zealand Clover Honey",
        "brand": "Airborne Honey NZ",
        "calories": 64,
        "protein": 0.1,
        "carbs": 17.0,
        "fats": 0.0,
        "serving_size": "1 tbsp (20g)",
        "serving_grams": 20,
        "category": "carbs",
        "country": "NZ"
      },
      {
        "id": "nz-carb-8",
        "name": "Diamond Macaroni Durum Wheat",
        "brand": "Diamond NZ",
        "calories": 180,
        "protein": 6.2,
        "carbs": 36.0,
        "fats": 0.8,
        "serving_size": "50g dry",
        "serving_grams": 50,
        "category": "carbs",
        "country": "NZ"
      }
    ],
    "fats": [
      {
        "id": "nz-fats-1",
        "name": "Fix & Fogg Super Nutty Peanut Butter",
        "brand": "Fix & Fogg NZ",
        "calories": 100,
        "protein": 4.5,
        "carbs": 2.4,
        "fats": 8.2,
        "serving_size": "1 tbsp (16g)",
        "serving_grams": 16,
        "category": "fats",
        "country": "NZ"
      },
      {
        "id": "nz-fats-2",
        "name": "Olivado Extra Virgin Cold Pressed Avocado Oil",
        "brand": "Olivado NZ",
        "calories": 120,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 13.8,
        "serving_size": "1 tbsp (15ml)",
        "serving_grams": 15,
        "category": "fats",
        "country": "NZ"
      },
      {
        "id": "nz-fats-3",
        "name": "Anchor Pure New Zealand Grass-Fed Butter",
        "brand": "Anchor NZ",
        "calories": 108,
        "protein": 0.1,
        "carbs": 0.1,
        "fats": 12.0,
        "serving_size": "1 pat (15g)",
        "serving_grams": 15,
        "category": "fats",
        "country": "NZ"
      },
      {
        "id": "nz-fats-4",
        "name": "New Zealand Fresh Ripe Hass Avocado",
        "brand": "Fresh NZ",
        "calories": 160,
        "protein": 2.0,
        "carbs": 8.5,
        "fats": 14.7,
        "serving_size": "1/2 avocado (100g)",
        "serving_grams": 100,
        "category": "fats",
        "country": "NZ"
      },
      {
        "id": "nz-fats-5",
        "name": "Mother Earth Raw Natural Walnuts",
        "brand": "Mother Earth NZ",
        "calories": 198,
        "protein": 4.4,
        "carbs": 4.0,
        "fats": 19.8,
        "serving_size": "30g handful",
        "serving_grams": 30,
        "category": "fats",
        "country": "NZ"
      },
      {
        "id": "nz-fats-6",
        "name": "Fix & Fogg Everything Butter (Seeds & Nuts)",
        "brand": "Fix & Fogg NZ",
        "calories": 105,
        "protein": 4.2,
        "carbs": 2.6,
        "fats": 8.8,
        "serving_size": "1 tbsp (16g)",
        "serving_grams": 16,
        "category": "fats",
        "country": "NZ"
      }
    ],
    "fastfood": [
      {
        "id": "nz-fast-1",
        "name": "Fergburger The Fergburger Classic Beef",
        "brand": "Fergburger Queenstown",
        "calories": 720,
        "protein": 48.0,
        "carbs": 62.0,
        "fats": 32.0,
        "serving_size": "1 burger (380g)",
        "serving_grams": 380,
        "category": "fastfood",
        "country": "NZ"
      },
      {
        "id": "nz-fast-2",
        "name": "Pita Pit Grilled Chicken Breast Regular",
        "brand": "Pita Pit NZ",
        "calories": 420,
        "protein": 36.0,
        "carbs": 44.0,
        "fats": 10.5,
        "serving_size": "1 pita (320g)",
        "serving_grams": 320,
        "category": "fastfood",
        "country": "NZ"
      },
      {
        "id": "nz-fast-3",
        "name": "Gourmet Bakery Steak & Cheese Mince Pie",
        "brand": "Irvines / Mrs Macs NZ",
        "calories": 480,
        "protein": 18.0,
        "carbs": 42.0,
        "fats": 26.0,
        "serving_size": "1 pie (190g)",
        "serving_grams": 190,
        "category": "fastfood",
        "country": "NZ"
      },
      {
        "id": "nz-fast-4",
        "name": "BurgerFuel Bastard Classic Beef Burger",
        "brand": "BurgerFuel NZ",
        "calories": 680,
        "protein": 44.0,
        "carbs": 52.0,
        "fats": 32.0,
        "serving_size": "1 burger (350g)",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "NZ"
      },
      {
        "id": "nz-fast-5",
        "name": "Traditional Battered Snapper Fish & Chips",
        "brand": "Kiwi Takeaways NZ",
        "calories": 610,
        "protein": 32.0,
        "carbs": 68.0,
        "fats": 22.0,
        "serving_size": "1 fillet + chips",
        "serving_grams": 350,
        "category": "fastfood",
        "country": "NZ"
      },
      {
        "id": "nz-fast-6",
        "name": "Subway NZ Roast Beef 6-Inch Multigrain",
        "brand": "Subway NZ",
        "calories": 320,
        "protein": 25.0,
        "carbs": 44.0,
        "fats": 5.0,
        "serving_size": "6-inch (235g)",
        "serving_grams": 235,
        "category": "fastfood",
        "country": "NZ"
      }
    ],
    "drinks": [
      {
        "id": "nz-drin-1",
        "name": "L&P Lemon & Paeroa Zero Sugar",
        "brand": "Coca-Cola Amatil NZ",
        "calories": 3,
        "protein": 0.0,
        "carbs": 0.5,
        "fats": 0.0,
        "serving_size": "330ml can",
        "serving_grams": 330,
        "category": "drinks",
        "country": "NZ"
      },
      {
        "id": "nz-drin-2",
        "name": "Anchor Protein+ Vanilla High Protein Drink",
        "brand": "Anchor NZ",
        "calories": 290,
        "protein": 30.0,
        "carbs": 25.0,
        "fats": 7.5,
        "serving_size": "500ml bottle",
        "serving_grams": 500,
        "category": "drinks",
        "country": "NZ"
      },
      {
        "id": "nz-drin-3",
        "name": "Phoenix Organic Ginger Beer Zero",
        "brand": "Phoenix Organics NZ",
        "calories": 8,
        "protein": 0.0,
        "carbs": 2.0,
        "fats": 0.0,
        "serving_size": "330ml bottle",
        "serving_grams": 330,
        "category": "drinks",
        "country": "NZ"
      },
      {
        "id": "nz-drin-4",
        "name": "Charlie's Honest Squeezed Orange Juice",
        "brand": "Charlie's NZ",
        "calories": 115,
        "protein": 1.8,
        "carbs": 25.0,
        "fats": 0.2,
        "serving_size": "250ml glass",
        "serving_grams": 250,
        "category": "drinks",
        "country": "NZ"
      },
      {
        "id": "nz-drin-5",
        "name": "V Energy Zero Sugar NZ Green Can",
        "brand": "Frucor Suntory NZ",
        "calories": 12,
        "protein": 0.4,
        "carbs": 1.8,
        "fats": 0.0,
        "serving_size": "250ml can",
        "serving_grams": 250,
        "category": "drinks",
        "country": "NZ"
      },
      {
        "id": "nz-drin-6",
        "name": "Pure New Zealand Spring Water 750ml",
        "brand": "Pump Water NZ",
        "calories": 0,
        "protein": 0.0,
        "carbs": 0.0,
        "fats": 0.0,
        "serving_size": "750ml bottle",
        "serving_grams": 750,
        "category": "drinks",
        "country": "NZ"
      }
    ]
  }
};
