/*
# Create Tandem (Friend Mode) tables

## Overview
Adds the database schema for the "Tandem" training partner feature. Two authenticated
users pair via a 6-digit code and can then share goals, send workouts to each other,
and track each other's daily activity.

## New Tables

### tandem_pairs
- id (uuid, PK)
- user_a (uuid, NOT NULL, references auth.users)
- user_b (uuid, nullable until partner accepts)
- invite_code (text, unique 6-char code generated by user_a)
- status (text: 'pending' | 'active' | 'dissolved')
- created_at (timestamptz)
- paired_at (timestamptz, set when partner joins)

### tandem_goals
- id (uuid, PK)
- pair_id (uuid, FK -> tandem_pairs)
- title (text, goal description)
- target_value (numeric, the combined target)
- current_value_a (numeric, user_a contribution)
- current_value_b (numeric, user_b contribution)
- unit (text, e.g. 'sessions', 'kg', 'steps')
- deadline (date, optional)
- completed (boolean)
- created_at (timestamptz)

### tandem_workouts
- id (uuid, PK)
- pair_id (uuid, FK -> tandem_pairs)
- sender_id (uuid, FK -> auth.users, who built the workout)
- receiver_id (uuid, FK -> auth.users, who receives it)
- title (text)
- exercises (jsonb, array of exercise objects)
- notes (text, optional instructions)
- status (text: 'pending' | 'accepted' | 'completed' | 'declined')
- created_at (timestamptz)
- completed_at (timestamptz)

### tandem_activity
- id (uuid, PK)
- pair_id (uuid, FK -> tandem_pairs)
- user_id (uuid, FK -> auth.users)
- activity_type (text: 'workout_logged' | 'goal_contribution' | 'streak_check')
- description (text)
- created_at (timestamptz)

## Security
- RLS enabled on all tables.
- Users can only access rows where they are user_a or user_b in the pair.
- Tandem workouts: sender and receiver can access.
- Activity: both pair members can view.

## Important Notes
1. invite_code has a unique index for fast lookup during pairing.
2. Pair membership is checked via EXISTS subquery on tandem_pairs.
3. All user_id columns default to auth.uid() where applicable.
*/

-- tandem_pairs
CREATE TABLE IF NOT EXISTS tandem_pairs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_a uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  user_b uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  invite_code text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','dissolved')),
  created_at timestamptz NOT NULL DEFAULT now(),
  paired_at timestamptz
);

ALTER TABLE tandem_pairs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_pairs" ON tandem_pairs;
CREATE POLICY "select_own_pairs" ON tandem_pairs FOR SELECT
  TO authenticated USING (auth.uid() = user_a OR auth.uid() = user_b);

DROP POLICY IF EXISTS "insert_own_pairs" ON tandem_pairs;
CREATE POLICY "insert_own_pairs" ON tandem_pairs FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_a);

DROP POLICY IF EXISTS "update_own_pairs" ON tandem_pairs;
CREATE POLICY "update_own_pairs" ON tandem_pairs FOR UPDATE
  TO authenticated USING (auth.uid() = user_a OR auth.uid() = user_b)
  WITH CHECK (auth.uid() = user_a OR auth.uid() = user_b);

DROP POLICY IF EXISTS "delete_own_pairs" ON tandem_pairs;
CREATE POLICY "delete_own_pairs" ON tandem_pairs FOR DELETE
  TO authenticated USING (auth.uid() = user_a);

-- tandem_goals
CREATE TABLE IF NOT EXISTS tandem_goals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id uuid NOT NULL REFERENCES tandem_pairs(id) ON DELETE CASCADE,
  title text NOT NULL,
  target_value numeric NOT NULL DEFAULT 0,
  current_value_a numeric NOT NULL DEFAULT 0,
  current_value_b numeric NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'sessions',
  deadline date,
  completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE tandem_goals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_pair_goals" ON tandem_goals;
CREATE POLICY "select_pair_goals" ON tandem_goals FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM tandem_pairs WHERE tandem_pairs.id = tandem_goals.pair_id
      AND (tandem_pairs.user_a = auth.uid() OR tandem_pairs.user_b = auth.uid()))
  );

DROP POLICY IF EXISTS "insert_pair_goals" ON tandem_goals;
CREATE POLICY "insert_pair_goals" ON tandem_goals FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM tandem_pairs WHERE tandem_pairs.id = tandem_goals.pair_id
      AND (tandem_pairs.user_a = auth.uid() OR tandem_pairs.user_b = auth.uid()))
  );

DROP POLICY IF EXISTS "update_pair_goals" ON tandem_goals;
CREATE POLICY "update_pair_goals" ON tandem_goals FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM tandem_pairs WHERE tandem_pairs.id = tandem_goals.pair_id
      AND (tandem_pairs.user_a = auth.uid() OR tandem_pairs.user_b = auth.uid()))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM tandem_pairs WHERE tandem_pairs.id = tandem_goals.pair_id
      AND (tandem_pairs.user_a = auth.uid() OR tandem_pairs.user_b = auth.uid()))
  );

DROP POLICY IF EXISTS "delete_pair_goals" ON tandem_goals;
CREATE POLICY "delete_pair_goals" ON tandem_goals FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM tandem_pairs WHERE tandem_pairs.id = tandem_goals.pair_id
      AND (tandem_pairs.user_a = auth.uid() OR tandem_pairs.user_b = auth.uid()))
  );

-- tandem_workouts
CREATE TABLE IF NOT EXISTS tandem_workouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id uuid NOT NULL REFERENCES tandem_pairs(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  exercises jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','completed','declined')),
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

ALTER TABLE tandem_workouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_workouts" ON tandem_workouts;
CREATE POLICY "select_own_workouts" ON tandem_workouts FOR SELECT
  TO authenticated USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "insert_own_workouts" ON tandem_workouts;
CREATE POLICY "insert_own_workouts" ON tandem_workouts FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "update_own_workouts" ON tandem_workouts;
CREATE POLICY "update_own_workouts" ON tandem_workouts FOR UPDATE
  TO authenticated USING (auth.uid() = sender_id OR auth.uid() = receiver_id)
  WITH CHECK (auth.uid() = sender_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "delete_own_workouts" ON tandem_workouts;
CREATE POLICY "delete_own_workouts" ON tandem_workouts FOR DELETE
  TO authenticated USING (auth.uid() = sender_id);

-- tandem_activity
CREATE TABLE IF NOT EXISTS tandem_activity (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id uuid NOT NULL REFERENCES tandem_pairs(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  activity_type text NOT NULL CHECK (activity_type IN ('workout_logged','goal_contribution','streak_check')),
  description text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE tandem_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_pair_activity" ON tandem_activity;
CREATE POLICY "select_pair_activity" ON tandem_activity FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM tandem_pairs WHERE tandem_pairs.id = tandem_activity.pair_id
      AND (tandem_pairs.user_a = auth.uid() OR tandem_pairs.user_b = auth.uid()))
  );

DROP POLICY IF EXISTS "insert_pair_activity" ON tandem_activity;
CREATE POLICY "insert_pair_activity" ON tandem_activity FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_pair_activity" ON tandem_activity;
CREATE POLICY "update_pair_activity" ON tandem_activity FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_pair_activity" ON tandem_activity;
CREATE POLICY "delete_pair_activity" ON tandem_activity FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tandem_pairs_invite_code ON tandem_pairs(invite_code);
CREATE INDEX IF NOT EXISTS idx_tandem_pairs_user_a ON tandem_pairs(user_a);
CREATE INDEX IF NOT EXISTS idx_tandem_pairs_user_b ON tandem_pairs(user_b);
CREATE INDEX IF NOT EXISTS idx_tandem_goals_pair_id ON tandem_goals(pair_id);
CREATE INDEX IF NOT EXISTS idx_tandem_workouts_pair_id ON tandem_workouts(pair_id);
CREATE INDEX IF NOT EXISTS idx_tandem_workouts_receiver ON tandem_workouts(receiver_id);
CREATE INDEX IF NOT EXISTS idx_tandem_activity_pair_id ON tandem_activity(pair_id);
